export {
  computeGuardEarnings,
  computeGuardPay,
  computeGuardPayoutCents,
  computeJobBilling,
  computePlatformFee,
  DEFAULT_CLIENT_FEE_SCHEDULES,
  DEFAULT_PLATFORM_FEE_CONFIG,
  describePlatformFeeAtRate,
  feeGuardTypeFromJobType,
  feePreviewRates,
  LEGACY_PLATFORM_FEE_PER_HOUR,
  normalizeAgreementFeeConfig,
  normalizeClientPlatformFeeSchedules,
  normalizePlatformFeeConfig,
  PLATFORM_FEE_GUARD_TYPE_LABELS,
  PLATFORM_FEE_GUARD_TYPES,
  platformFeeModelLabel,
  resolveAgreementPlatformFeePerHour,
  resolveClientJobFeeConfig,
  resolvePlatformFeePerHour,
  TIERED_PLATFORM_FEE_PRESET,
  type AgreementPlatformFeeConfig,
  type ClientFeeAccountKind,
  type ClientPlatformFeeSchedule,
  type ClientPlatformFeeSchedules,
  type PlatformFeeConfig,
  type PlatformFeeGuardType,
  type PlatformFeeModel,
  type PlatformFeeTier,
} from '../../lib/platformFees';

/** @deprecated Use resolvePlatformFeePerHour() or per-job platformFeePerHour. */
export { LEGACY_PLATFORM_FEE_PER_HOUR as PLATFORM_FEE_PER_HOUR } from '../../lib/platformFees';
