import type { SecurityGuard, StaffRole, StaffSideRole } from '../types';
import { ROLE_LABELS, staffRoleToPlatformRole } from './permissions';
import { formatPersonName, resolvePersonNameParts } from './personName';
import { looksLikeStaffBadge } from './staffBadgeNumber';

/** Platform operations areas staff can highlight on their profile. */
export const STAFF_FOCUS_OPTIONS = [
  'Guard verification',
  'Client onboarding',
  'Job operations',
  'Payments & payouts',
  'Disputes & incidents',
  'City markets',
  'Support desk',
  'Analytics & reporting',
  'Integrations',
  'Team leadership',
] as const;

export type StaffFocusArea = (typeof STAFF_FOCUS_OPTIONS)[number];

const AUTO_BIO_PATTERN =
  /^.+ — (Platform operations(\s*\(Finance side role\))?|Payment desk)\.?$/;

export function isAutoGeneratedStaffBio(bio?: string | null): boolean {
  return Boolean(bio?.trim() && AUTO_BIO_PATTERN.test(bio.trim()));
}

export function defaultStaffHeadline(staffRole?: StaffRole | null, sideRole?: string | null): string {
  if (!staffRole && sideRole === 'Finance') return 'Finance — Payment desk';
  if (!staffRole) return 'Platform operations';
  const platformRole = staffRoleToPlatformRole(staffRole);
  return `${staffRole} — ${ROLE_LABELS[platformRole]}`;
}

/** Human-readable requested role for applications and review badges (Finance desk aware). */
export function getStaffRequestedRoleLabel(
  member: Pick<SecurityGuard, 'staffRole' | 'sideRole' | 'requestedStaffRole' | 'userStatus'>,
): string {
  const sideRole = member.sideRole as StaffSideRole | null | undefined;
  if (
    member.requestedStaffRole &&
    member.userStatus === 'pending' &&
    (!member.staffRole || member.staffRole === 'Support')
  ) {
    const requested = member.requestedStaffRole;
    const platformRole = staffRoleToPlatformRole(requested);
    const roleTitle = ROLE_LABELS[platformRole];
    return roleTitle === requested ? `${requested} (requested)` : `${requested} — ${roleTitle} (requested)`;
  }
  const isFinanceDesk = !member.staffRole && sideRole === 'Finance';
  const staffRole = member.staffRole || (isFinanceDesk ? null : 'Support');
  if (isFinanceDesk) {
    return `Finance desk — ${ROLE_LABELS.finance}`;
  }
  if (!staffRole) {
    return ROLE_LABELS.finance;
  }
  const platformRole = staffRoleToPlatformRole(staffRole);
  const roleTitle = ROLE_LABELS[platformRole];
  if (sideRole === 'Finance') {
    return `${staffRole} + Finance — ${roleTitle}`;
  }
  return roleTitle === staffRole ? staffRole : `${staffRole} — ${roleTitle}`;
}

export function getStaffDisplayName(
  member: Pick<SecurityGuard, 'name' | 'badgeNumber' | 'firstName' | 'middleName' | 'lastName'>
): string {
  const resolved = resolvePersonNameParts({
    firstName: member.firstName,
    middleName: member.middleName,
    lastName: member.lastName,
    name: member.name,
  });
  const formatted = formatPersonName(resolved);
  if (formatted.trim() && !looksLikeStaffBadge(formatted) && formatted !== member.badgeNumber) {
    return formatted;
  }
  const name = member.name?.trim();
  if (name && !looksLikeStaffBadge(name) && name !== member.badgeNumber) {
    return name;
  }
  return member.badgeNumber || 'Staff member';
}

export function getStaffDisplayHeadline(
  member: Pick<SecurityGuard, 'headline' | 'staffRole'>
): string {
  const headline = member.headline?.trim();
  if (headline) return headline;
  return defaultStaffHeadline(member.staffRole);
}

export function getStaffProfileSnippet(
  member: Pick<SecurityGuard, 'summary' | 'about' | 'bio' | 'staffRole'>
): string {
  const summary = member.summary?.trim();
  if (summary) return summary;
  const about = member.about?.trim();
  if (about) return about.split('\n')[0]?.trim() ?? '';
  const bio = member.bio?.trim();
  if (bio && !isAutoGeneratedStaffBio(bio)) return bio;
  return defaultStaffHeadline(member.staffRole);
}

export function staffProfileHasContent(
  member: Pick<SecurityGuard, 'headline' | 'summary' | 'about' | 'bio' | 'specialties'>
): boolean {
  return Boolean(
    member.headline?.trim() ||
      member.summary?.trim() ||
      member.about?.trim() ||
      (member.bio?.trim() && !isAutoGeneratedStaffBio(member.bio)) ||
      (member.specialties?.length ?? 0) > 0
  );
}
