import assert from 'node:assert/strict';
import test from 'node:test';
import {
  defaultStaffHeadline,
  getStaffDisplayHeadline,
  getStaffDisplayName,
  getStaffProfileSnippet,
  isAutoGeneratedStaffBio,
  staffProfileHasContent,
} from './staffProfile';

test('detects auto-generated bios', () => {
  assert.equal(isAutoGeneratedStaffBio('Director — Platform operations.'), true);
  assert.equal(isAutoGeneratedStaffBio('Founder — Platform operations'), true);
  assert.equal(isAutoGeneratedStaffBio('Runs guard verification and payouts.'), false);
});

test('prefers custom headline and summary', () => {
  const member = {
    name: 'Tyrone Johnson',
    badgeNumber: 'DIR-00002',
    headline: 'Director of Platform Operations',
    summary: 'Keeps the command center moving.',
    about: 'Longer background text.',
    bio: 'Director — Platform operations.',
    staffRole: 'Director' as const,
    specialties: ['Payments & payouts'],
  };

  assert.equal(getStaffDisplayName(member), 'Tyrone Johnson');
  assert.equal(getStaffDisplayHeadline(member), 'Director of Platform Operations');
  assert.equal(getStaffProfileSnippet(member), 'Keeps the command center moving.');
  assert.equal(staffProfileHasContent(member), true);
});

test('falls back to role-based headline', () => {
  assert.equal(defaultStaffHeadline('Moderator'), 'Moderator — Moderator');
  assert.equal(
    getStaffDisplayHeadline({
      headline: '',
      staffRole: 'Support',
    }),
    'Support — Support'
  );
});
