import assert from 'node:assert/strict';
import test from 'node:test';
import {
  defaultStaffHeadline,
  getStaffDisplayHeadline,
  getStaffDisplayName,
  getStaffProfileSnippet,
  getStaffRequestedRoleLabel,
  isAutoGeneratedStaffBio,
  staffProfileHasContent,
} from './staffProfile';

test('detects auto-generated bios', () => {
  assert.equal(isAutoGeneratedStaffBio('Director — Platform operations.'), true);
  assert.equal(isAutoGeneratedStaffBio('Founder — Platform operations'), true);
  assert.equal(isAutoGeneratedStaffBio('Runs guard verification and payouts.'), false);
});

test('prefers real names over badge ids', () => {
  const member = {
    name: 'ADM-00003',
    badgeNumber: 'ADM-00003',
    firstName: 'Khalid',
    lastName: 'Lovett',
    headline: 'Director of Platform Operations',
    summary: 'Keeps the command center moving.',
    about: 'Longer background text.',
    bio: 'Director — Platform operations.',
    staffRole: 'Administrator' as const,
    specialties: ['Payments & payouts'],
  };

  assert.equal(getStaffDisplayName(member), 'Khalid Lovett');
  assert.equal(getStaffDisplayHeadline(member), 'Director of Platform Operations');
  assert.equal(getStaffProfileSnippet(member), 'Keeps the command center moving.');
  assert.equal(staffProfileHasContent(member), true);
});

test('falls back to role-based headline', () => {
  assert.equal(defaultStaffHeadline('Moderator'), 'Moderator — Moderator');
  assert.equal(
    getStaffDisplayHeadline({
      headline: '',
      staffRole: 'Support',
    }),
    'Support — Support'
  );
});

test('getStaffRequestedRoleLabel handles Finance desk and ladder roles', () => {
  assert.equal(
    getStaffRequestedRoleLabel({ staffRole: null, sideRole: 'Finance' }),
    'Finance desk — Finance',
  );
  assert.equal(
    getStaffRequestedRoleLabel({ staffRole: 'Director', sideRole: 'Finance' }),
    'Director + Finance — Director',
  );
  assert.equal(getStaffRequestedRoleLabel({ staffRole: 'Support' }), 'Support');
  assert.match(
    getStaffRequestedRoleLabel({
      staffRole: 'Support',
      requestedStaffRole: 'Director',
      userStatus: 'pending',
    }),
    /Director.*requested/i,
  );
});
