// Generated by scripts/bundle-push-handlers.mjs — do not edit.
// @ts-nocheck

// api/_push/config.ts
function isPushConfigured() {
  return !!(process.env.VAPID_PUBLIC_KEY?.trim() && process.env.VAPID_PRIVATE_KEY?.trim());
}

// api/_push/dedup.ts
var DEDUP_TTL_MS = 25 * 60 * 60 * 1e3;
function missedCheckinDedupKey(requestId, hourBucket) {
  return `missed_checkin:${requestId}:${hourBucket}`;
}
async function claimNotificationDedup(db, dedupKey, notificationType) {
  const { data: existing } = await db.from("push_notification_dedup").select("id").eq("id", dedupKey).maybeSingle();
  if (existing?.id) return true;
  const { error } = await db.from("push_notification_dedup").insert({
    id: dedupKey,
    notification_type: notificationType
  });
  if (error) {
    if (error.code === "23505") return true;
    throw new Error(error.message);
  }
  return false;
}

// api/_push/routing.ts
function pushRoleToPlatformRole(pushRole) {
  switch (pushRole) {
    case "guard":
      return "guard";
    case "client":
      return "client";
    case "dispatch":
    case "admin":
      return "administrator";
    default:
      return "administrator";
  }
}
function resolveNotificationUrl(type, options = {}) {
  switch (type) {
    case "missed_checkin":
    case "guard_checkin":
    case "guard_clockout":
    case "guard_arrived":
    case "guard_left_site":
    case "guard_break_start":
    case "guard_break_end":
      return options.requestId ? `/staff/jobs?j=${encodeURIComponent(options.requestId)}` : "/staff/jobs";
    case "job_open_to_guards":
      return options.requestId ? `/guard/map?jc=${encodeURIComponent(options.requestId)}` : "/guard/map";
    case "client_cash_payment_requested":
    case "guard_cash_payout_requested":
    case "stripe_payment_complete":
      return options.requestId ? `/staff/payments?j=${encodeURIComponent(options.requestId)}` : "/staff/payments";
    case "assignment":
      return options.requestId ? `/guard/my-jobs?jc=${encodeURIComponent(options.requestId)}` : "/guard/my-jobs";
    case "emergency_alert":
      if (options.requestId) {
        return `/staff/jobs?j=${encodeURIComponent(options.requestId)}`;
      }
      if (options.ticketId) {
        return `/staff/support?st=${encodeURIComponent(options.ticketId)}`;
      }
      return "/staff/incidents";
    case "support_message":
      return options.ticketId ? `/staff/support?st=${encodeURIComponent(options.ticketId)}` : "/staff/support";
    case "job_chat_message":
      return options.requestId ? `/staff/messages?mtab=jobs&jc=${encodeURIComponent(options.requestId)}` : "/staff/messages?mtab=jobs";
    case "staff_message":
      return "/staff/messages?mtab=team";
    case "guard_message":
      return "/guard/guard-chat";
    case "job_submitted":
      return options.requestId ? `/staff/jobs?j=${encodeURIComponent(options.requestId)}` : "/staff/approvals?aq=job-offers";
    case "guard_application":
      return options.requestId ? `/staff/jobs?j=${encodeURIComponent(options.requestId)}` : "/staff/approvals?aq=applications";
    case "guard_pending_approval":
      return options.guardId ? `/staff/guards?g=${encodeURIComponent(options.guardId)}` : "/staff/approvals?aq=accounts";
    case "client_pending_approval":
      return "/staff/approvals?aq=accounts";
    case "credential_pending":
      return options.guardId ? `/staff/approvals?aq=credentials&g=${encodeURIComponent(options.guardId)}` : "/staff/approvals?aq=credentials";
    case "payment_attention":
      return options.requestId ? `/staff/payments?j=${encodeURIComponent(options.requestId)}` : "/staff/payments";
    case "support_ticket":
    case "support_ticket_status":
      return options.ticketId ? `/staff/messages?mtab=support&st=${encodeURIComponent(options.ticketId)}` : "/staff/messages?mtab=support";
    case "dispute_update":
      return options.ticketId ? `/staff/disputes?st=${encodeURIComponent(options.ticketId)}` : "/staff/disputes";
    case "guard_trusted_status":
      return options.guardId ? `/guard/profile?g=${encodeURIComponent(options.guardId)}` : "/guard/profile";
    case "client_trusted_status":
      return "/client/profile";
    case "job_relisted":
      return options.requestId ? `/client/requests?jc=${encodeURIComponent(options.requestId)}` : "/client/requests";
    case "job_schedule_changed":
      return options.requestId ? `/guard/my-jobs?jc=${encodeURIComponent(options.requestId)}` : "/guard/my-jobs";
    case "team_chat_message":
      return options.requestId ? `/staff/messages?mtab=team&jc=${encodeURIComponent(options.requestId)}` : "/staff/messages?mtab=team";
    case "test":
      return "/";
    default:
      return "/";
  }
}
function resolveNotificationUrlForRole(type, role, options = {}) {
  const isStaff = role === "moderator" || role === "administrator" || role === "director" || role === "owner";
  switch (type) {
    case "guard_arrived":
    case "guard_left_site":
      if (role === "client") {
        return options.requestId ? `/client/map?jc=${encodeURIComponent(options.requestId)}` : "/client/map";
      }
      if (role === "guard") {
        return options.requestId ? `/guard/my-jobs?jc=${encodeURIComponent(options.requestId)}` : "/guard/my-jobs";
      }
      return options.requestId ? `/staff/jobs?j=${encodeURIComponent(options.requestId)}` : "/staff/jobs";
    case "job_open_to_guards":
      return options.requestId ? `/guard/map?jc=${encodeURIComponent(options.requestId)}` : "/guard/map";
    case "client_cash_payment_requested":
    case "guard_cash_payout_requested":
    case "stripe_payment_complete":
      if (role === "client") {
        return options.requestId ? `/client/requests?jc=${encodeURIComponent(options.requestId)}` : "/client/requests";
      }
      if (role === "guard") {
        return "/guard/earnings";
      }
      return options.requestId ? `/staff/payments?j=${encodeURIComponent(options.requestId)}` : "/staff/payments";
    case "payment_attention":
      if (role === "client") {
        return options.requestId ? `/client/requests?jc=${encodeURIComponent(options.requestId)}` : "/client/requests";
      }
      if (role === "guard") {
        return "/guard/earnings";
      }
      return options.requestId ? `/staff/payments?j=${encodeURIComponent(options.requestId)}` : "/staff/payments";
    case "support_message":
      if (role === "client") {
        return options.ticketId ? `/client/support?st=${encodeURIComponent(options.ticketId)}` : "/client/support";
      }
      if (role === "guard") {
        return options.ticketId ? `/guard/support?st=${encodeURIComponent(options.ticketId)}` : "/guard/support";
      }
      return options.ticketId ? `/staff/support?st=${encodeURIComponent(options.ticketId)}` : "/staff/support";
    case "job_chat_message":
      if (role === "client") {
        return options.requestId ? `/client/map?jc=${encodeURIComponent(options.requestId)}&chat=1` : "/client/messages";
      }
      if (role === "guard") {
        return options.requestId ? `/guard/my-jobs?jc=${encodeURIComponent(options.requestId)}&chat=1` : "/guard/my-jobs";
      }
      return options.requestId ? `/staff/messages?mtab=jobs&jc=${encodeURIComponent(options.requestId)}` : "/staff/messages?mtab=jobs";
    case "emergency_alert":
      if (role === "client") {
        return options.requestId ? `/client/map?jc=${encodeURIComponent(options.requestId)}` : "/client/map";
      }
      if (role === "guard") {
        return options.requestId ? `/guard/my-jobs?jc=${encodeURIComponent(options.requestId)}` : "/guard/my-jobs";
      }
      if (options.requestId) {
        return `/staff/jobs?j=${encodeURIComponent(options.requestId)}`;
      }
      if (options.ticketId) {
        return `/staff/support?st=${encodeURIComponent(options.ticketId)}`;
      }
      return "/staff/incidents";
    case "missed_checkin":
    case "guard_checkin":
    case "guard_clockout":
    case "guard_break_start":
    case "guard_break_end":
      if (role === "guard") {
        return options.requestId ? `/guard/my-jobs?jc=${encodeURIComponent(options.requestId)}` : "/guard/my-jobs";
      }
      if (role === "client") {
        return options.requestId ? `/client/map?jc=${encodeURIComponent(options.requestId)}` : "/client/map";
      }
      return options.requestId ? `/staff/jobs?j=${encodeURIComponent(options.requestId)}` : "/staff/jobs";
    case "staff_message":
      return "/staff/messages?mtab=team";
    case "guard_message":
      return "/guard/guard-chat";
    case "support_ticket":
    case "support_ticket_status":
      if (role === "client" && options.requestId) {
        return `/client/requests?jc=${encodeURIComponent(options.requestId)}`;
      }
      if (role === "client") {
        return options.ticketId ? `/client/support?st=${encodeURIComponent(options.ticketId)}` : "/client/support";
      }
      if (role === "guard") {
        return options.ticketId ? `/guard/support?st=${encodeURIComponent(options.ticketId)}` : "/guard/support";
      }
      return options.ticketId ? `/staff/messages?mtab=support&st=${encodeURIComponent(options.ticketId)}` : "/staff/messages?mtab=support";
    case "dispute_update":
      if (role === "client") {
        return options.ticketId ? `/client/support?st=${encodeURIComponent(options.ticketId)}` : "/client/support";
      }
      if (role === "guard") {
        return options.ticketId ? `/guard/support?st=${encodeURIComponent(options.ticketId)}` : "/guard/support";
      }
      return options.ticketId ? `/staff/disputes?st=${encodeURIComponent(options.ticketId)}` : "/staff/disputes";
    case "assignment":
    case "guard_application":
      if (role === "client") {
        return options.requestId ? `/client/requests?jc=${encodeURIComponent(options.requestId)}` : "/client/requests";
      }
      if (type === "guard_application") {
        return options.requestId ? `/staff/jobs?j=${encodeURIComponent(options.requestId)}` : "/staff/approvals?aq=applications";
      }
      return options.requestId ? `/guard/my-jobs?jc=${encodeURIComponent(options.requestId)}` : "/guard/my-jobs";
    case "guard_trusted_status":
      return "/guard/profile";
    case "client_trusted_status":
      return "/client/profile";
    case "job_relisted":
      return options.requestId ? `/client/requests?jc=${encodeURIComponent(options.requestId)}` : "/client/requests";
    case "job_schedule_changed":
      return options.requestId ? `/guard/my-jobs?jc=${encodeURIComponent(options.requestId)}` : "/guard/my-jobs";
    case "team_chat_message":
      if (role === "guard") {
        return options.requestId ? `/guard/messages?jc=${encodeURIComponent(options.requestId)}` : "/guard/messages";
      }
      return options.requestId ? `/staff/messages?mtab=team&jc=${encodeURIComponent(options.requestId)}` : "/staff/messages?mtab=team";
    default:
      if (isStaff) return resolveNotificationUrl(type, options);
      if (role === "client") return "/client/home";
      if (role === "guard") return "/guard/map";
      return resolveNotificationUrl(type, options);
  }
}
function rolesForNotificationType(type) {
  switch (type) {
    case "missed_checkin":
    case "guard_checkin":
    case "guard_clockout":
    case "guard_arrived":
    case "guard_left_site":
    case "guard_break_start":
    case "guard_break_end":
      return ["dispatch", "admin"];
    case "job_open_to_guards":
      return ["guard"];
    case "client_cash_payment_requested":
    case "guard_cash_payout_requested":
    case "stripe_payment_complete":
      return ["dispatch", "admin"];
    case "assignment":
      return ["guard"];
    case "guard_application":
      return ["dispatch", "admin"];
    case "emergency_alert":
      return ["guard", "client", "dispatch", "admin"];
    case "support_message":
      return ["dispatch", "admin", "client", "guard"];
    case "job_chat_message":
      return ["client", "guard", "dispatch", "admin"];
    case "staff_message":
      return ["dispatch", "admin"];
    case "guard_message":
      return ["guard"];
    case "job_submitted":
    case "guard_pending_approval":
    case "client_pending_approval":
    case "credential_pending":
    case "payment_attention":
      return ["dispatch", "admin"];
    case "support_ticket":
      return ["dispatch", "admin"];
    case "support_ticket_status":
      return ["client", "guard"];
    case "dispute_update":
      return ["dispatch", "admin", "client", "guard"];
    case "guard_trusted_status":
      return ["guard"];
    case "client_trusted_status":
      return ["client"];
    case "job_relisted":
      return ["client"];
    case "job_schedule_changed":
      return ["guard"];
    case "team_chat_message":
      return ["guard", "dispatch", "admin"];
    case "test":
      return [];
    default:
      return ["guard", "dispatch"];
  }
}
function buildNotificationData(type, options = {}) {
  const urlOptions = {
    guardId: options.guardId,
    requestId: options.requestId,
    ticketId: options.ticketId
  };
  const url = options.url ?? (options.role ? resolveNotificationUrlForRole(type, options.role, urlOptions) : resolveNotificationUrl(type, urlOptions));
  return {
    type,
    url,
    siteId: options.siteId,
    guardId: options.guardId,
    requestId: options.requestId,
    ticketId: options.ticketId,
    priority: options.priority ?? (type === "emergency_alert" ? "high" : "normal")
  };
}

// api/_push/delivery.ts
var PREF_COLUMN = {
  assignment: "assignment",
  guard_checkin: "guard_checkin",
  guard_clockout: "guard_clockout",
  guard_arrived: "guard_arrived",
  guard_left_site: "guard_left_site",
  guard_break_start: "guard_break_start",
  guard_break_end: "guard_break_end",
  missed_checkin: "missed_checkin",
  emergency_alert: "emergency_alert",
  support_message: "support_message",
  job_chat_message: "job_chat_message",
  staff_message: "staff_message",
  guard_message: "guard_message",
  job_submitted: "job_submitted",
  job_open_to_guards: "job_open_to_guards",
  guard_application: "guard_application",
  guard_pending_approval: "guard_pending_approval",
  client_pending_approval: "client_pending_approval",
  credential_pending: "credential_pending",
  payment_attention: "payment_attention",
  client_cash_payment_requested: "payment_attention",
  guard_cash_payout_requested: "payment_attention",
  stripe_payment_complete: "payment_attention",
  support_ticket: "support_ticket",
  support_ticket_status: "support_ticket_status",
  dispute_update: "dispute_update",
  guard_trusted_status: "guard_trusted_status",
  client_trusted_status: "client_trusted_status",
  job_relisted: "job_relisted",
  job_schedule_changed: "assignment",
  team_chat_message: "team_chat_message"
};
async function isTypeEnabledForUser(db, userId, type) {
  const column = PREF_COLUMN[type];
  if (!column) return true;
  const { data, error } = await db.from("notification_preferences").select(column).eq("user_id", userId).maybeSingle();
  if (error || !data) return true;
  return data[column] !== false;
}
var MAX_RETRIES = 2;
var RETRY_DELAY_MS = 500;
var vapidConfigured = false;
var webPushModule = null;
async function getWebPush() {
  if (!webPushModule) {
    const mod = await import("web-push");
    webPushModule = "default" in mod && mod.default ? mod.default : mod;
  }
  return webPushModule;
}
async function ensureVapidConfigured() {
  const publicKey = process.env.VAPID_PUBLIC_KEY?.trim();
  const privateKey = process.env.VAPID_PRIVATE_KEY?.trim();
  const subject = process.env.VAPID_SUBJECT?.trim() || "mailto:support@guardr.co";
  if (!publicKey || !privateKey) return false;
  if (vapidConfigured) return true;
  const webpush = await getWebPush();
  webpush.setVapidDetails(subject, publicKey, privateKey);
  vapidConfigured = true;
  return true;
}
function isInQuietHours(quietStart, quietEnd, now = /* @__PURE__ */ new Date()) {
  if (!quietStart || !quietEnd) return false;
  const toMinutes = (time) => {
    const [h, m] = time.split(":").map(Number);
    return h * 60 + m;
  };
  const current = now.getHours() * 60 + now.getMinutes();
  const start = toMinutes(quietStart);
  const end = toMinutes(quietEnd);
  if (start === end) return false;
  if (start < end) return current >= start && current < end;
  return current >= start || current < end;
}
async function sleep(ms) {
  await new Promise((resolve) => setTimeout(resolve, ms));
}
async function sendToSubscription(subscription, payload, attempt = 0) {
  if (!await ensureVapidConfigured()) {
    return { ok: false, endpoint: subscription.endpoint };
  }
  try {
    const webpush = await getWebPush();
    await webpush.sendNotification(
      {
        endpoint: subscription.endpoint,
        keys: { p256dh: subscription.p256dh, auth: subscription.auth }
      },
      JSON.stringify(payload),
      {
        TTL: 60 * 60,
        urgency: payload.priority === "high" ? "high" : "normal"
      }
    );
    return { ok: true };
  } catch (err) {
    const statusCode = err && typeof err === "object" && "statusCode" in err ? Number(err.statusCode) : void 0;
    if (attempt < MAX_RETRIES && statusCode !== 404 && statusCode !== 410) {
      await sleep(RETRY_DELAY_MS * (attempt + 1));
      return sendToSubscription(subscription, payload, attempt + 1);
    }
    return { ok: false, statusCode, endpoint: subscription.endpoint };
  }
}
async function removeInvalidSubscriptions(db, endpoints) {
  if (!endpoints.length) return;
  await db.from("push_subscriptions").delete().in("endpoint", endpoints);
}
async function deliverToSubscriptions(db, subscriptions, payload) {
  if (!subscriptions.length) return { sent: 0, failed: 0 };
  if (!await ensureVapidConfigured()) return { sent: 0, failed: subscriptions.length };
  const prefCache = /* @__PURE__ */ new Map();
  const filtered = [];
  for (const sub of subscriptions) {
    if (payload.excludeUserId && sub.user_id === payload.excludeUserId) {
      continue;
    }
    if (!sub.user_id) {
      filtered.push(sub);
      continue;
    }
    let enabled = prefCache.get(sub.user_id);
    if (enabled === void 0) {
      enabled = await isTypeEnabledForUser(db, sub.user_id, payload.type);
      prefCache.set(sub.user_id, enabled);
    }
    if (enabled) filtered.push(sub);
  }
  if (!filtered.length) return { sent: 0, failed: 0 };
  const urlOptions = {
    guardId: payload.guardId,
    requestId: payload.requestId,
    ticketId: payload.ticketId
  };
  let sent = 0;
  let failed = 0;
  const staleEndpoints = [];
  for (const sub of filtered) {
    if (payload.type !== "emergency_alert" && payload.priority !== "high" && isInQuietHours(sub.quiet_hours_start, sub.quiet_hours_end)) {
      continue;
    }
    const platformRole = pushRoleToPlatformRole(sub.push_role);
    const data = buildNotificationData(payload.type, {
      url: payload.url ?? resolveNotificationUrlForRole(payload.type, platformRole, urlOptions),
      siteId: payload.siteId,
      guardId: payload.guardId,
      requestId: payload.requestId,
      ticketId: payload.ticketId,
      priority: payload.priority,
      role: platformRole
    });
    const message = {
      title: payload.title,
      body: payload.body,
      url: data.url,
      eventType: payload.type,
      data,
      tag: payload.siteId ? `${payload.type}-${payload.siteId}` : payload.type,
      priority: data.priority
    };
    const result = await sendToSubscription(sub, message);
    if (result.ok) {
      sent += 1;
    } else {
      failed += 1;
      if (result.statusCode === 404 || result.statusCode === 410) {
        staleEndpoints.push(result.endpoint);
      }
    }
  }
  await removeInvalidSubscriptions(db, staleEndpoints);
  return { sent, failed };
}
async function sendNotificationToUser(db, userId, payload) {
  const enabled = await isTypeEnabledForUser(db, userId, payload.type);
  if (!enabled) return { sent: 0, failed: 0 };
  const { data: subscriptions, error } = await db.from("push_subscriptions").select("endpoint, p256dh, auth, quiet_hours_start, quiet_hours_end, user_id, push_role").eq("user_id", userId);
  if (error) throw new Error(error.message);
  return deliverToSubscriptions(db, subscriptions ?? [], payload);
}
async function sendNotificationToRole(db, role, payload) {
  const roles = role === "dispatch" ? ["dispatch", "admin"] : [role];
  const { data: subscriptions, error } = await db.from("push_subscriptions").select("endpoint, p256dh, auth, quiet_hours_start, quiet_hours_end, user_id, push_role").in("push_role", roles);
  if (error) throw new Error(error.message);
  return deliverToSubscriptions(db, subscriptions ?? [], payload);
}
async function dispatchPushNotification(db, payload) {
  if (payload.userId) {
    return sendNotificationToUser(db, payload.userId, payload);
  }
  if (payload.role) {
    return sendNotificationToRole(db, payload.role, payload);
  }
  const roles = rolesForNotificationType(payload.type);
  let sent = 0;
  let failed = 0;
  for (const role of roles) {
    const result = await sendNotificationToRole(db, role, payload);
    sent += result.sent;
    failed += result.failed;
  }
  return { sent, failed };
}

// api/_push/eventDispatch.ts
var EVENT_DEFAULTS = {
  guard_checkin: (event) => ({
    title: "Guard check-in",
    body: event.guardName ? `${event.guardName} checked in${event.location ? ` at ${event.location}` : ""}` : "A guard completed a check-in"
  }),
  guard_clockout: (event) => ({
    title: "Guard clock-out",
    body: event.guardName ? `${event.guardName} clocked out${event.location ? ` at ${event.location}` : ""}` : "A guard clocked out"
  }),
  guard_arrived: (event) => ({
    title: "Guard arrived on site",
    body: event.guardName ? `${event.guardName} arrived${event.location ? ` at ${event.location}` : ""}` : "Your guard arrived on site"
  }),
  guard_left_site: (event) => ({
    title: "Guard left job site",
    body: event.guardName ? `${event.guardName} left the job site${event.location ? ` at ${event.location}` : ""}` : "A guard left the job site during an active shift"
  }),
  guard_break_start: (event) => ({
    title: "Guard on break",
    body: event.guardName ? `${event.guardName} started a break${event.location ? ` at ${event.location}` : ""}` : "A guard started a break"
  }),
  guard_break_end: (event) => ({
    title: "Guard back on duty",
    body: event.guardName ? `${event.guardName} ended break and is back on duty${event.location ? ` at ${event.location}` : ""}` : "A guard ended a break"
  }),
  missed_checkin: (event) => ({
    title: "Missed check-in",
    body: event.guardName ? `${event.guardName} missed an hourly check-in` : "A guard missed an hourly check-in"
  }),
  assignment: (event) => ({
    title: "New assignment",
    body: event.body ?? (event.location ? `You have a new assignment at ${event.location}` : "You have a new assignment update")
  }),
  emergency_alert: (event) => ({
    title: "Emergency alert",
    body: event.body || "Immediate attention required on an active shift"
  }),
  support_message: (event) => ({
    title: "Support message",
    body: event.body || "You have a new support message"
  }),
  job_chat_message: (event) => ({
    title: "Job chat",
    body: event.body || "New message on an active job"
  }),
  staff_message: (event) => ({
    title: "Staff chat",
    body: event.body || "New message from the Guardr team"
  }),
  guard_message: (event) => ({
    title: "Guard chat",
    body: event.body || "New message from another guard"
  }),
  job_submitted: (event) => ({
    title: "New job request",
    body: event.body || "A client submitted a job awaiting staff review"
  }),
  guard_application: (event) => ({
    title: "Guard application",
    body: event.body || "A guard applied to an open job offer"
  }),
  guard_pending_approval: (event) => ({
    title: "Guard pending approval",
    body: event.body || "A guard account needs staff review"
  }),
  client_pending_approval: (event) => ({
    title: "Client pending approval",
    body: event.body || "A client account needs staff review"
  }),
  credential_pending: (event) => ({
    title: "Credential review",
    body: event.body || "A guard submitted credentials for review"
  }),
  payment_attention: (event) => ({
    title: "Payment attention",
    body: event.body || "A payment or payout needs staff action"
  }),
  client_cash_payment_requested: (event) => ({
    title: "Client cash payment request",
    body: event.body || "A client requested to pay in cash"
  }),
  guard_cash_payout_requested: (event) => ({
    title: "Guard cash payout request",
    body: event.body || "A guard requested cash payout"
  }),
  stripe_payment_complete: (event) => ({
    title: "Stripe payment received",
    body: event.body || "A card payment completed successfully"
  }),
  job_open_to_guards: (event) => ({
    title: "New job on the map",
    body: event.body || "A paid job is now open for guards"
  }),
  support_ticket: (event) => ({
    title: "Support ticket",
    body: event.body || "A new support ticket needs staff attention"
  }),
  support_ticket_status: (event) => ({
    title: "Support update",
    body: event.body || "Your support ticket status changed"
  }),
  dispute_update: (event) => ({
    title: "Dispute update",
    body: event.body || "A dispute needs your attention"
  }),
  guard_trusted_status: (event) => ({
    title: event.title ?? "Trusted guard update",
    body: event.body || "Your trusted guard status changed"
  }),
  client_trusted_status: (event) => ({
    title: event.title ?? "Trusted client update",
    body: event.body || "Your trusted client status changed"
  }),
  job_relisted: (event) => ({
    title: "Job back on marketplace",
    body: event.body || "A job was re-listed and is open for guards again"
  }),
  job_schedule_changed: (event) => ({
    title: "Shift time changed",
    body: event.body || "Your job schedule was updated"
  }),
  team_chat_message: (event) => ({
    title: "Crew chat",
    body: event.body || "New message in crew chat"
  })
};
function basePayload(event) {
  const fallbackFn = EVENT_DEFAULTS[event.type];
  const fallback = fallbackFn ? fallbackFn(event) : { title: "Guardr alert", body: event.body || "Operational update" };
  return {
    title: event.title ?? fallback.title,
    body: event.body ?? fallback.body,
    type: event.type,
    guardId: event.guardId,
    requestId: event.requestId,
    ticketId: event.ticketId,
    siteId: event.siteId,
    priority: event.type === "emergency_alert" ? "high" : event.priority ?? "normal",
    excludeUserId: event.excludeUserId
  };
}
async function loadJobParticipants(db, requestId) {
  const { data } = await db.from("security_requests").select("client_id, assigned_guard_id").eq("id", requestId).maybeSingle();
  return {
    clientId: data?.client_id ?? null,
    guardId: data?.assigned_guard_id ?? null
  };
}
async function buildEventDispatchPayloads(db, event) {
  const payload = basePayload(event);
  if (event.type === "assignment") {
    if (event.recipientUserId) {
      return [{ ...payload, userId: event.recipientUserId }];
    }
    if (event.guardId) {
      return [{ ...payload, userId: event.guardId }];
    }
    return [{ ...payload, role: "guard" }];
  }
  if (event.type === "support_message" && event.recipientUserId) {
    return [{ ...payload, userId: event.recipientUserId }];
  }
  if (event.type === "job_chat_message" && event.recipientUserId) {
    return [{ ...payload, userId: event.recipientUserId }];
  }
  if (event.type === "emergency_alert" && event.requestId) {
    const { clientId, guardId } = await loadJobParticipants(db, event.requestId);
    const payloads = [{ ...payload, role: "dispatch" }];
    if (guardId) payloads.push({ ...payload, userId: guardId });
    if (clientId) payloads.push({ ...payload, userId: clientId });
    return payloads;
  }
  if (event.type === "missed_checkin") {
    const payloads = [{ ...payload, role: "dispatch" }];
    if (event.guardId) {
      payloads.push({
        ...payload,
        userId: event.guardId,
        title: "Missed check-in reminder",
        body: event.location ? `You missed your hourly check-in at ${event.location}` : "You missed your hourly check-in \u2014 please check in now"
      });
    }
    return payloads;
  }
  if (event.type === "support_ticket_status" && event.recipientUserId) {
    return [{ ...payload, userId: event.recipientUserId }];
  }
  if ((event.type === "guard_trusted_status" || event.type === "client_trusted_status" || event.type === "job_relisted" || event.type === "job_schedule_changed") && event.recipientUserId) {
    return [{ ...payload, userId: event.recipientUserId }];
  }
  if (event.type === "team_chat_message") {
    if (event.recipientUserId) {
      return [{ ...payload, userId: event.recipientUserId }];
    }
    return [{ ...payload, role: "dispatch" }];
  }
  if (event.type === "job_submitted" && event.recipientUserId) {
    return [{ ...payload, userId: event.recipientUserId }];
  }
  if (event.type === "job_open_to_guards") {
    return [{ ...payload, role: "guard" }];
  }
  if (event.type === "guard_application") {
    const payloads = [{ ...payload, role: "dispatch" }];
    if (event.recipientUserId) {
      payloads.push({ ...payload, userId: event.recipientUserId });
    } else if (event.clientId) {
      payloads.push({ ...payload, userId: event.clientId });
    }
    return payloads;
  }
  if (event.type === "stripe_payment_complete" || event.type === "client_cash_payment_requested" || event.type === "guard_cash_payout_requested") {
    return [{ ...payload, role: "dispatch" }];
  }
  if (event.type === "support_ticket") {
    return [{ ...payload, role: "dispatch" }];
  }
  if (event.type === "dispute_update") {
    const payloads = [{ ...payload, role: "dispatch" }];
    if (event.guardId) payloads.push({ ...payload, userId: event.guardId });
    if (event.clientId) payloads.push({ ...payload, userId: event.clientId });
    else if (event.recipientUserId) payloads.push({ ...payload, userId: event.recipientUserId });
    return payloads;
  }
  if (event.type === "staff_message" || event.type === "job_submitted" || event.type === "guard_pending_approval" || event.type === "client_pending_approval" || event.type === "credential_pending" || event.type === "payment_attention" || event.type === "support_message" && !event.recipientUserId || event.type === "job_chat_message" && !event.recipientUserId) {
    return [{ ...payload, role: "dispatch" }];
  }
  if (event.type === "guard_message") {
    return [{ ...payload, role: "guard" }];
  }
  if (event.type === "guard_checkin" || event.type === "guard_clockout" || event.type === "guard_arrived" || event.type === "guard_break_start" || event.type === "guard_break_end" || event.type === "guard_left_site") {
    const payloads = [{ ...payload, role: "dispatch" }];
    if (event.requestId) {
      const { clientId, guardId } = await loadJobParticipants(db, event.requestId);
      if (clientId) payloads.push({ ...payload, userId: clientId });
      if (event.type === "guard_left_site" && guardId) {
        payloads.push({
          ...payload,
          userId: guardId,
          title: "You left the job site",
          body: event.location ? `You moved away from ${event.location} during your shift` : "You left the job site during your active shift"
        });
      }
    } else if (event.recipientUserId) {
      payloads.push({ ...payload, userId: event.recipientUserId });
    }
    return payloads;
  }
  return [payload];
}

// api/_push/eventAuth.ts
var STAFF_ROLES = /* @__PURE__ */ new Set(["moderator", "administrator", "director", "owner", "staff", "auditor"]);
function isStaffSession(session) {
  return STAFF_ROLES.has(session.platformRole) || STAFF_ROLES.has(session.role);
}
async function isJobParticipant(db, requestId, userId) {
  const { data } = await db.from("security_requests").select("client_id, assigned_guard_id").eq("id", requestId).maybeSingle();
  if (!data) return false;
  return data.client_id === userId || data.assigned_guard_id === userId;
}
async function isSupportTicketParticipant(db, ticketId, userId) {
  const { data } = await db.from("support_tickets").select("user_id").eq("id", ticketId).maybeSingle();
  return data?.user_id === userId;
}
async function authorizePushEvent(db, session, event) {
  const { type } = event;
  switch (type) {
    case "test":
      return "Test notifications must use /api/push/test";
    case "staff_message":
      return isStaffSession(session) ? null : "Only staff can send this notification type";
    case "client_pending_approval":
      if (isStaffSession(session)) return null;
      if (session.platformRole === "client") return null;
      return "Only staff or the registering client can notify about pending approval";
    case "guard_pending_approval":
      if (isStaffSession(session)) return null;
      if (session.platformRole === "guard" && (!event.guardId || event.guardId === session.userId)) {
        return null;
      }
      return "Only staff or the registering guard can notify about pending approval";
    case "credential_pending":
      if (isStaffSession(session)) return null;
      if (session.platformRole === "guard" && event.guardId === session.userId) return null;
      return "Only staff or the submitting guard can send credential review notifications";
    case "job_submitted":
      if (isStaffSession(session)) return null;
      if (session.platformRole === "client") return null;
      if (event.requestId && await isJobParticipant(db, event.requestId, session.userId)) {
        return null;
      }
      return "Only staff or the submitting client can notify about new jobs";
    case "guard_application":
      if (isStaffSession(session)) return null;
      if (session.platformRole === "guard" && event.guardId === session.userId) return null;
      return "Only staff or the applying guard can send application notifications";
    case "guard_message":
      return session.platformRole === "guard" ? null : "Only guards can post to guard chat";
    case "guard_checkin":
    case "guard_clockout":
    case "guard_arrived":
    case "guard_left_site":
    case "guard_break_start":
    case "guard_break_end":
    case "missed_checkin":
      if (isStaffSession(session)) return null;
      if (event.guardId && event.guardId === session.userId) return null;
      if (event.requestId && await isJobParticipant(db, event.requestId, session.userId)) {
        return null;
      }
      return "Not authorized to report shift events for this job";
    case "job_open_to_guards":
      if (isStaffSession(session)) return null;
      if (session.platformRole === "client") return null;
      if (event.requestId && await isJobParticipant(db, event.requestId, session.userId)) {
        return null;
      }
      return "Only staff or the job client can notify guards of open positions";
    case "client_cash_payment_requested":
      if (isStaffSession(session)) return null;
      if (session.platformRole === "client") return null;
      if (event.requestId && await isJobParticipant(db, event.requestId, session.userId)) {
        return null;
      }
      return "Only staff or the job client can send cash payment request notifications";
    case "guard_cash_payout_requested":
      if (isStaffSession(session)) return null;
      if (session.platformRole === "guard") return null;
      return "Only staff or guards can send payout request notifications";
    case "stripe_payment_complete":
      return isStaffSession(session) ? null : "Only staff can send payment completion notifications";
    case "payment_attention":
      if (isStaffSession(session)) return null;
      if (session.platformRole === "guard") return null;
      if (event.requestId && await isJobParticipant(db, event.requestId, session.userId)) {
        return null;
      }
      return "Only staff, guards, or job participants can send payment attention notifications";
    case "assignment":
      if (isStaffSession(session)) return null;
      if (event.guardId && event.guardId === session.userId) return null;
      if (event.recipientUserId && event.recipientUserId === session.userId) return null;
      if (event.requestId && await isJobParticipant(db, event.requestId, session.userId)) {
        return null;
      }
      return "Not authorized to send assignment notifications for this job";
    case "emergency_alert":
      if (isStaffSession(session)) return null;
      if (event.requestId && await isJobParticipant(db, event.requestId, session.userId)) {
        return null;
      }
      if (event.ticketId && await isSupportTicketParticipant(db, event.ticketId, session.userId)) {
        return null;
      }
      return "Not authorized to send emergency alerts for this context";
    case "support_message":
      if (isStaffSession(session)) return null;
      if (event.recipientUserId && event.recipientUserId === session.userId) return null;
      if (event.ticketId && await isSupportTicketParticipant(db, event.ticketId, session.userId)) {
        return null;
      }
      return "Not authorized to send support messages for this ticket";
    case "job_chat_message":
      if (isStaffSession(session)) return null;
      if (event.requestId && await isJobParticipant(db, event.requestId, session.userId)) {
        return null;
      }
      return "Not authorized to send job chat messages for this job";
    case "support_ticket":
      if (isStaffSession(session)) return null;
      if (event.ticketId && await isSupportTicketParticipant(db, event.ticketId, session.userId)) {
        return null;
      }
      return "Not authorized to file this support ticket";
    case "support_ticket_status":
      return isStaffSession(session) ? null : "Only staff can send support status updates";
    case "dispute_update":
      if (isStaffSession(session)) return null;
      if (event.ticketId && await isSupportTicketParticipant(db, event.ticketId, session.userId)) {
        return null;
      }
      if (event.requestId && await isJobParticipant(db, event.requestId, session.userId)) {
        return null;
      }
      return "Not authorized to send dispute updates for this context";
    case "guard_trusted_status":
    case "client_trusted_status":
      return isStaffSession(session) ? null : "Only staff can send trusted status notifications";
    case "job_relisted":
      if (isStaffSession(session)) return null;
      if (event.recipientUserId && event.recipientUserId === session.userId) return null;
      if (event.requestId && await isJobParticipant(db, event.requestId, session.userId)) {
        return null;
      }
      return "Not authorized to send job re-list notifications";
    case "job_schedule_changed":
      if (isStaffSession(session)) return null;
      if (event.recipientUserId && event.recipientUserId === session.userId) return null;
      if (event.requestId && await isJobParticipant(db, event.requestId, session.userId)) {
        return null;
      }
      return "Not authorized to send schedule change notifications for this job";
    case "team_chat_message":
      if (isStaffSession(session)) return null;
      if (event.recipientUserId && event.recipientUserId === session.userId) return null;
      if (event.requestId && await isJobParticipant(db, event.requestId, session.userId)) {
        return null;
      }
      return "Not authorized to send crew chat notifications for this job";
    default:
      return "Unknown notification type";
  }
}

// api/_push/accountSessionAuth.ts
var STAFF_PLATFORM_ROLES = /* @__PURE__ */ new Set([
  "owner",
  "director",
  "administrator",
  "moderator",
  "staff",
  "auditor"
]);
function resolvePlatformRole(input) {
  if (input.legacyRole === "client") return "client";
  if (input.isStaff && input.staffRole) {
    switch (input.staffRole) {
      case "Founder":
      case "Owner":
        return "owner";
      case "Director":
        return "director";
      case "Administrator":
        return "administrator";
      case "Moderator":
        return "moderator";
    }
  }
  if (input.legacyRole === "auditor") return "moderator";
  if (input.legacyRole === "staff") return "administrator";
  return "guard";
}
async function verifyStaffSession(db, userId, email) {
  const { data, error } = await db.from("staff").select("id, email, staff_role").eq("id", userId).maybeSingle();
  if (error || !data || data.email?.toLowerCase() !== email) return null;
  const platformRole = resolvePlatformRole({
    isStaff: true,
    staffRole: data.staff_role ?? void 0,
    legacyRole: "staff"
  });
  return { userId, email, role: platformRole, platformRole };
}
async function verifyFieldGuardSession(db, userId, email, credentialsRole) {
  const { data, error } = await db.from("guards").select("id, email").eq("id", userId).maybeSingle();
  if (error || !data || data.email?.toLowerCase() !== email) return null;
  const platformRole = resolvePlatformRole({
    legacyRole: "guard"
  });
  if (platformRole !== credentialsRole && credentialsRole !== "staff" && credentialsRole !== "auditor") {
    console.warn(`Session role mismatch for ${email}: client sent ${credentialsRole}, db has ${platformRole}`);
  }
  return { userId, email, role: platformRole, platformRole };
}
async function verifyAccountSession(db, credentials) {
  if (!credentials?.userId || !credentials?.email || !credentials?.role) {
    return null;
  }
  const email = credentials.email.trim().toLowerCase();
  const { userId, role } = credentials;
  if (role === "client") {
    const { data } = await db.from("clients").select("id, email").eq("id", userId).maybeSingle();
    if (!data || data.email?.toLowerCase() !== email) return null;
    return { userId, email, role: "client", platformRole: "client" };
  }
  if (STAFF_PLATFORM_ROLES.has(role)) {
    const staffSession = await verifyStaffSession(db, userId, email);
    if (staffSession) return staffSession;
  }
  return verifyFieldGuardSession(db, userId, email, role);
}

// api/_push/sessionAuth.ts
async function verifySession(db, credentials) {
  return verifyAccountSession(db, credentials);
}

// api/_push/handlers.ts
function pushNotConfiguredResponse() {
  return { status: 503, body: { error: "Web Push is not configured. Set VAPID_PUBLIC_KEY and VAPID_PRIVATE_KEY." } };
}
async function dispatchPushEvent(db, event, options) {
  if (!event.type) {
    throw new Error("Notification type is required");
  }
  if (!isPushConfigured()) {
    throw new Error("Web Push is not configured");
  }
  const session = await verifySession(db, event);
  if (!session && !options?.skipAuth) {
    throw new Error("Unauthorized \u2014 invalid session");
  }
  if (session && !options?.skipAuth) {
    const authError = await authorizePushEvent(db, session, {
      type: event.type,
      guardId: event.guardId,
      requestId: event.requestId,
      recipientUserId: event.recipientUserId,
      ticketId: event.ticketId
    });
    if (authError) {
      throw new Error(authError);
    }
  }
  if (event.type === "missed_checkin" && event.requestId) {
    const hourBucket = Math.floor(Date.now() / (60 * 60 * 1e3));
    const dedupKey = missedCheckinDedupKey(event.requestId, hourBucket);
    const alreadySent = await claimNotificationDedup(db, dedupKey, "missed_checkin");
    if (alreadySent) {
      return { sent: 0, failed: 0 };
    }
  }
  const excludeUserId = event.type === "guard_message" || event.type === "staff_message" ? session?.userId : void 0;
  const payloads = await buildEventDispatchPayloads(db, {
    ...event,
    type: event.type,
    excludeUserId,
    clientId: event.clientId,
    priority: event.priority
  });
  let sent = 0;
  let failed = 0;
  for (const payload of payloads) {
    const result = await dispatchPushNotification(db, payload);
    sent += result.sent;
    failed += result.failed;
  }
  return { sent, failed };
}
async function handlePushEvent(db, body) {
  const session = await verifySession(db, body);
  if (!session) {
    return { status: 401, body: { error: "Unauthorized \u2014 invalid session" } };
  }
  if (!body.type) {
    return { status: 400, body: { error: "Notification type is required" } };
  }
  if (!isPushConfigured()) {
    return pushNotConfiguredResponse();
  }
  try {
    const result = await dispatchPushEvent(db, body);
    return { status: 200, body: { ok: true, ...result } };
  } catch (err) {
    const message = err instanceof Error ? err.message : "Push event failed";
    const status = message.startsWith("Unauthorized") || message.includes("Not authorized") ? 403 : 500;
    return { status, body: { error: message } };
  }
}

// api/_push/entries/events.ts
async function getSupabaseAdmin() {
  const url = process.env.SUPABASE_URL || process.env.NEXT_PUBLIC_SUPABASE_URL || process.env.VITE_SUPABASE_URL;
  const serviceKey = process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.SUPABASE_KEY;
  if (!url || !serviceKey) return null;
  const { createClient } = await import("@supabase/supabase-js");
  return createClient(url, serviceKey, {
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
async function handler(req, res) {
  if (req.method !== "POST") {
    return res.status(405).json({ error: "Method not allowed" });
  }
  try {
    const db = await getSupabaseAdmin();
    if (!db) {
      return res.status(503).json({ error: "Database is not configured" });
    }
    const result = await handlePushEvent(db, req.body ?? {});
    return res.status(result.status).json(result.body);
  } catch (err) {
    const message = err instanceof Error ? err.message : "Push event failed";
    console.error("Push events error:", message, err);
    return res.status(500).json({ error: message });
  }
}
export {
  handler as default
};
