// Generated by scripts/bundle-push-handlers.mjs — do not edit.
// @ts-nocheck

// api/_push/apiCors.ts
var GUARDR_ORIGIN = /^https:\/\/([a-z0-9-]+\.)?guardr\.co$/i;
var CAPACITOR_ORIGIN = /^https:\/\/localhost(?::\d+)?$/i;
function isAllowedApiOrigin(origin) {
  return GUARDR_ORIGIN.test(origin) || CAPACITOR_ORIGIN.test(origin) || /^capacitor:\/\//i.test(origin);
}
function applyApiCors(req, res) {
  const origin = req.headers.origin;
  if (origin && isAllowedApiOrigin(origin)) {
    res.setHeader("Access-Control-Allow-Origin", origin);
    res.setHeader("Access-Control-Allow-Credentials", "true");
    res.setHeader("Vary", "Origin");
  }
  if (req.method === "OPTIONS") {
    res.setHeader("Access-Control-Allow-Methods", "GET, POST, PUT, PATCH, DELETE, OPTIONS");
    res.setHeader("Access-Control-Allow-Headers", "Content-Type, Authorization");
    res.status(204).end();
    return true;
  }
  return false;
}

// lib/push/fcm.ts
import { createSign } from "node:crypto";
var FCM_NATIVE_ENDPOINT_PREFIX = "fcm-native:";
var cachedAccessToken = null;
function parseServiceAccountJson() {
  const raw = process.env.FCM_SERVICE_ACCOUNT_JSON?.trim();
  if (!raw) return null;
  try {
    const parsed = JSON.parse(raw);
    if (parsed.project_id && parsed.client_email && parsed.private_key) {
      return {
        project_id: parsed.project_id,
        client_email: parsed.client_email,
        private_key: parsed.private_key
      };
    }
  } catch {
  }
  return null;
}
function isFcmConfigured() {
  return !!process.env.FCM_SERVER_KEY?.trim() || !!parseServiceAccountJson();
}
function isFcmNativeEndpoint(endpoint) {
  return endpoint.startsWith(FCM_NATIVE_ENDPOINT_PREFIX);
}
function fcmTokenFromEndpoint(endpoint) {
  if (!isFcmNativeEndpoint(endpoint)) return null;
  const token = endpoint.slice(FCM_NATIVE_ENDPOINT_PREFIX.length).trim();
  return token || null;
}
function stringifyDataValue(value) {
  if (value == null) return "";
  if (typeof value === "string") return value;
  return JSON.stringify(value);
}
function buildDataPayload(payload) {
  const data = {};
  const nested = payload.data;
  if (nested && typeof nested === "object") {
    for (const [key, value] of Object.entries(nested)) {
      data[key] = stringifyDataValue(value);
    }
  }
  if (payload.url) data.url = stringifyDataValue(payload.url);
  if (payload.eventType) data.eventType = stringifyDataValue(payload.eventType);
  if (payload.priority) data.priority = stringifyDataValue(payload.priority);
  return data;
}
function base64UrlEncode(value) {
  return Buffer.from(value).toString("base64url");
}
async function getFcmAccessToken(serviceAccount) {
  const now = Date.now();
  if (cachedAccessToken && cachedAccessToken.expiresAt > now + 6e4) {
    return cachedAccessToken.token;
  }
  const issuedAt = Math.floor(now / 1e3);
  const header = base64UrlEncode(JSON.stringify({ alg: "RS256", typ: "JWT" }));
  const claim = base64UrlEncode(
    JSON.stringify({
      iss: serviceAccount.client_email,
      scope: "https://www.googleapis.com/auth/firebase.messaging",
      aud: "https://oauth2.googleapis.com/token",
      iat: issuedAt,
      exp: issuedAt + 3600
    })
  );
  const unsigned = `${header}.${claim}`;
  const sign = createSign("RSA-SHA256");
  sign.update(unsigned);
  const signature = sign.sign(serviceAccount.private_key, "base64url");
  const assertion = `${unsigned}.${signature}`;
  try {
    const res = await fetch("https://oauth2.googleapis.com/token", {
      method: "POST",
      headers: { "Content-Type": "application/x-www-form-urlencoded" },
      body: new URLSearchParams({
        grant_type: "urn:ietf:params:oauth:grant-type:jwt-bearer",
        assertion
      })
    });
    const body = await res.json().catch(() => ({}));
    if (!res.ok || !body.access_token) return null;
    cachedAccessToken = {
      token: body.access_token,
      expiresAt: now + (body.expires_in ?? 3600) * 1e3
    };
    return body.access_token;
  } catch {
    return null;
  }
}
async function sendFcmV1Notification(serviceAccount, endpoint, token, payload, attempt = 0) {
  const accessToken = await getFcmAccessToken(serviceAccount);
  if (!accessToken) return { ok: false, endpoint };
  const data = buildDataPayload(payload);
  try {
    const res = await fetch(
      `https://fcm.googleapis.com/v1/projects/${serviceAccount.project_id}/messages:send`,
      {
        method: "POST",
        headers: {
          Authorization: `Bearer ${accessToken}`,
          "Content-Type": "application/json"
        },
        body: JSON.stringify({
          message: {
            token,
            notification: {
              title: String(payload.title ?? "Guardr"),
              body: String(payload.body ?? "")
            },
            data,
            android: {
              priority: payload.priority === "high" ? "high" : "normal"
            }
          }
        })
      }
    );
    if (res.ok) return { ok: true };
    const body = await res.json().catch(() => ({}));
    const errStatus = body.error?.status;
    if (errStatus === "NOT_FOUND" || errStatus === "UNREGISTERED" || errStatus === "INVALID_ARGUMENT") {
      return { ok: false, statusCode: 410, endpoint };
    }
    if (attempt < 2 && res.status >= 500) {
      await new Promise((resolve) => setTimeout(resolve, 500 * (attempt + 1)));
      return sendFcmV1Notification(serviceAccount, endpoint, token, payload, attempt + 1);
    }
    return { ok: false, statusCode: res.status, endpoint };
  } catch {
    if (attempt < 2) {
      await new Promise((resolve) => setTimeout(resolve, 500 * (attempt + 1)));
      return sendFcmV1Notification(serviceAccount, endpoint, token, payload, attempt + 1);
    }
    return { ok: false, endpoint };
  }
}
async function sendFcmLegacyNotification(endpoint, token, payload, serverKey, attempt = 0) {
  const data = buildDataPayload(payload);
  try {
    const res = await fetch("https://fcm.googleapis.com/fcm/send", {
      method: "POST",
      headers: {
        Authorization: `key=${serverKey}`,
        "Content-Type": "application/json"
      },
      body: JSON.stringify({
        to: token,
        notification: {
          title: String(payload.title ?? "Guardr"),
          body: String(payload.body ?? "")
        },
        data,
        priority: payload.priority === "high" ? "high" : "normal"
      })
    });
    const body = await res.json().catch(() => ({}));
    if (res.ok && body.success === 1) return { ok: true };
    const errCode = body.results?.[0]?.error;
    if (errCode === "NotRegistered" || errCode === "InvalidRegistration") {
      return { ok: false, statusCode: 410, endpoint };
    }
    if (attempt < 2 && res.status >= 500) {
      await new Promise((resolve) => setTimeout(resolve, 500 * (attempt + 1)));
      return sendFcmLegacyNotification(endpoint, token, payload, serverKey, attempt + 1);
    }
    return { ok: false, statusCode: res.status, endpoint };
  } catch {
    if (attempt < 2) {
      await new Promise((resolve) => setTimeout(resolve, 500 * (attempt + 1)));
      return sendFcmLegacyNotification(endpoint, token, payload, serverKey, attempt + 1);
    }
    return { ok: false, endpoint };
  }
}
async function sendFcmNativeNotification(endpoint, payload, attempt = 0) {
  const token = fcmTokenFromEndpoint(endpoint);
  if (!token) return { ok: false, endpoint };
  const serviceAccount = parseServiceAccountJson();
  if (serviceAccount) {
    return sendFcmV1Notification(serviceAccount, endpoint, token, payload, attempt);
  }
  const serverKey = process.env.FCM_SERVER_KEY?.trim();
  if (!serverKey) return { ok: false, endpoint };
  return sendFcmLegacyNotification(endpoint, token, payload, serverKey, attempt);
}

// api/_push/config.ts
function isPushConfigured() {
  const vapidReady = !!(process.env.VAPID_PUBLIC_KEY?.trim() && process.env.VAPID_PRIVATE_KEY?.trim());
  return vapidReady || isFcmConfigured();
}

// api/_push/dedup.ts
var DEDUP_TTL_MS = 25 * 60 * 60 * 1e3;
function missedCheckinDedupKey(requestId, hourBucket) {
  return `missed_checkin:${requestId}:${hourBucket}`;
}
function checkInEscalationDedupKey(requestId, dueBucket, tier) {
  return `checkin_esc:${requestId}:${dueBucket}:${tier}`;
}
async function claimNotificationDedup(db, dedupKey, notificationType) {
  const { data: existing } = await db.from("push_notification_dedup").select("id").eq("id", dedupKey).maybeSingle();
  if (existing?.id) return true;
  const { error } = await db.from("push_notification_dedup").insert({
    id: dedupKey,
    notification_type: notificationType
  });
  if (error) {
    if (error.code === "23505") return true;
    throw new Error(error.message);
  }
  return false;
}

// api/_push/routing.ts
function pushRoleToPlatformRole(pushRole) {
  switch (pushRole) {
    case "guard":
      return "guard";
    case "client":
      return "client";
    case "dispatch":
    case "admin":
      return "administrator";
    default:
      return "administrator";
  }
}
function resolveNotificationUrl(type, options = {}) {
  switch (type) {
    case "missed_checkin":
    case "guard_checkin":
    case "guard_clockout":
    case "guard_arrived":
    case "guard_en_route":
    case "guard_left_site":
    case "guard_break_start":
    case "guard_break_end":
      return options.requestId ? `/staff/jobs?j=${encodeURIComponent(options.requestId)}` : "/staff/jobs";
    case "job_open_to_guards":
      return options.requestId ? `/guard/map?jc=${encodeURIComponent(options.requestId)}` : "/guard/map";
    case "client_cash_payment_requested":
    case "guard_cash_payout_requested":
    case "stripe_payment_complete":
      return options.requestId ? `/staff/payments?j=${encodeURIComponent(options.requestId)}` : "/staff/payments";
    case "assignment":
      return options.requestId ? `/guard/my-jobs?jc=${encodeURIComponent(options.requestId)}` : "/guard/my-jobs";
    case "emergency_alert":
      if (options.requestId) {
        return `/staff/jobs?j=${encodeURIComponent(options.requestId)}`;
      }
      if (options.ticketId) {
        return `/staff/support?st=${encodeURIComponent(options.ticketId)}`;
      }
      return "/staff/incidents";
    case "support_message":
      return options.ticketId ? `/staff/support?st=${encodeURIComponent(options.ticketId)}` : "/staff/support";
    case "job_chat_message":
      return options.requestId ? `/staff/messages?mtab=jobs&jc=${encodeURIComponent(options.requestId)}` : "/staff/messages?mtab=jobs";
    case "staff_message":
      return "/staff/messages?mtab=team";
    case "guard_message":
      return "/guard/guard-chat";
    case "client_message":
      return "/client/messages";
    case "job_submitted":
      return options.requestId ? `/staff/jobs?j=${encodeURIComponent(options.requestId)}` : "/staff/jobs";
    case "guard_application":
      return options.requestId ? `/staff/jobs?j=${encodeURIComponent(options.requestId)}` : "/staff/jobs";
    case "crew_lead_request":
      return "/staff/crews";
    case "guard_pending_approval":
      return options.guardId ? `/staff/applications?g=${encodeURIComponent(options.guardId)}` : "/staff/applications";
    case "client_pending_approval":
      return "/staff/applications";
    case "credential_pending":
      return options.guardId ? `/staff/credentials?g=${encodeURIComponent(options.guardId)}` : "/staff/credentials";
    case "payment_attention":
      return options.requestId ? `/staff/payments?j=${encodeURIComponent(options.requestId)}` : "/staff/payments";
    case "client_invoice_ready":
      return options.requestId ? `/client/invoices?inv=${encodeURIComponent(options.requestId)}` : "/client/invoices";
    case "support_ticket":
    case "support_ticket_status":
      return options.ticketId ? `/staff/messages?st=${encodeURIComponent(options.ticketId)}` : "/staff/messages";
    case "account_update":
      return "/staff/settings";
    case "job_status_update":
      return options.requestId ? `/staff/jobs?j=${encodeURIComponent(options.requestId)}` : "/staff/jobs";
    case "payout_ready":
      return "/guard/earnings";
    case "dispute_update":
      return options.ticketId ? `/staff/disputes?st=${encodeURIComponent(options.ticketId)}` : "/staff/disputes";
    case "guard_trusted_status":
      return options.guardId ? `/guard/profile?g=${encodeURIComponent(options.guardId)}` : "/guard/profile";
    case "client_trusted_status":
      return "/client/profile";
    case "job_relisted":
      return options.requestId ? `/client/requests?jc=${encodeURIComponent(options.requestId)}` : "/client/requests";
    case "job_schedule_changed":
      return options.requestId ? `/guard/my-jobs?jc=${encodeURIComponent(options.requestId)}` : "/guard/my-jobs";
    case "team_chat_message":
      return options.requestId ? `/staff/messages?mtab=team&jc=${encodeURIComponent(options.requestId)}` : "/staff/messages?mtab=team";
    case "standing_crew_invite":
      return "/guard/crew";
    case "company_placard_expiry":
      return "/staff/settings";
    case "pre_shift_briefing":
      return options.requestId ? `/guard/map?jc=${encodeURIComponent(options.requestId)}` : "/guard/map";
    case "test":
      return "/";
    default:
      return "/";
  }
}
function resolveNotificationUrlForRole(type, role, options = {}) {
  const isStaff = role === "moderator" || role === "administrator" || role === "director" || role === "owner";
  switch (type) {
    case "guard_arrived":
    case "guard_en_route":
    case "guard_left_site":
      if (role === "client") {
        return options.requestId ? `/client/map?jc=${encodeURIComponent(options.requestId)}` : "/client/map";
      }
      if (role === "guard") {
        return options.requestId ? `/guard/my-jobs?jc=${encodeURIComponent(options.requestId)}` : "/guard/my-jobs";
      }
      return options.requestId ? `/staff/jobs?j=${encodeURIComponent(options.requestId)}` : "/staff/jobs";
    case "job_open_to_guards":
      return options.requestId ? `/guard/map?jc=${encodeURIComponent(options.requestId)}` : "/guard/map";
    case "client_cash_payment_requested":
    case "guard_cash_payout_requested":
    case "stripe_payment_complete":
      if (role === "client") {
        return options.requestId ? `/client/requests?jc=${encodeURIComponent(options.requestId)}` : "/client/requests";
      }
      if (role === "guard") {
        return "/guard/earnings";
      }
      return options.requestId ? `/staff/payments?j=${encodeURIComponent(options.requestId)}` : "/staff/payments";
    case "payment_attention":
      if (role === "client") {
        return options.requestId ? `/client/requests?jc=${encodeURIComponent(options.requestId)}` : "/client/requests";
      }
      if (role === "guard") {
        return "/guard/earnings";
      }
      return options.requestId ? `/staff/payments?j=${encodeURIComponent(options.requestId)}` : "/staff/payments";
    case "support_message":
      if (role === "client") {
        return options.ticketId ? `/client/support?st=${encodeURIComponent(options.ticketId)}` : "/client/support";
      }
      if (role === "guard") {
        return options.ticketId ? `/guard/support?st=${encodeURIComponent(options.ticketId)}` : "/guard/support";
      }
      return options.ticketId ? `/staff/support?st=${encodeURIComponent(options.ticketId)}` : "/staff/support";
    case "job_chat_message":
      if (role === "client") {
        return options.requestId ? `/client/map?jc=${encodeURIComponent(options.requestId)}&chat=1` : "/client/messages";
      }
      if (role === "guard") {
        return options.requestId ? `/guard/my-jobs?jc=${encodeURIComponent(options.requestId)}&chat=1` : "/guard/my-jobs";
      }
      return options.requestId ? `/staff/messages?mtab=jobs&jc=${encodeURIComponent(options.requestId)}` : "/staff/messages?mtab=jobs";
    case "emergency_alert":
      if (role === "client") {
        return options.requestId ? `/client/map?jc=${encodeURIComponent(options.requestId)}` : "/client/map";
      }
      if (role === "guard") {
        return options.requestId ? `/guard/my-jobs?jc=${encodeURIComponent(options.requestId)}` : "/guard/my-jobs";
      }
      if (options.requestId) {
        return `/staff/jobs?j=${encodeURIComponent(options.requestId)}`;
      }
      if (options.ticketId) {
        return `/staff/support?st=${encodeURIComponent(options.ticketId)}`;
      }
      return "/staff/incidents";
    case "missed_checkin":
    case "guard_checkin":
    case "guard_clockout":
    case "guard_break_start":
    case "guard_break_end":
      if (role === "guard") {
        return options.requestId ? `/guard/my-jobs?jc=${encodeURIComponent(options.requestId)}` : "/guard/my-jobs";
      }
      if (role === "client") {
        return options.requestId ? `/client/map?jc=${encodeURIComponent(options.requestId)}` : "/client/map";
      }
      return options.requestId ? `/staff/jobs?j=${encodeURIComponent(options.requestId)}` : "/staff/jobs";
    case "staff_message":
      return "/staff/messages?mtab=team";
    case "guard_message":
      return "/guard/guard-chat";
    case "client_message":
      if (role === "client") return "/client/messages";
      return "/staff/messages?mtab=team";
    case "support_ticket":
    case "support_ticket_status":
      if (role === "client" && options.requestId) {
        return `/client/requests?jc=${encodeURIComponent(options.requestId)}`;
      }
      if (role === "client") {
        return options.ticketId ? `/client/messages?st=${encodeURIComponent(options.ticketId)}` : "/client/messages";
      }
      if (role === "guard") {
        return options.ticketId ? `/guard/messages?st=${encodeURIComponent(options.ticketId)}` : "/guard/messages";
      }
      return options.ticketId ? `/staff/messages?st=${encodeURIComponent(options.ticketId)}` : "/staff/messages";
    case "account_update":
      if (role === "client") return "/client/settings";
      if (role === "guard") return "/guard/settings";
      return "/staff/settings";
    case "job_status_update":
      if (role === "client") {
        return options.requestId ? `/client/requests?jc=${encodeURIComponent(options.requestId)}` : "/client/requests";
      }
      if (role === "guard") {
        return options.requestId ? `/guard/my-jobs?jc=${encodeURIComponent(options.requestId)}` : "/guard/my-jobs";
      }
      return options.requestId ? `/staff/jobs?j=${encodeURIComponent(options.requestId)}` : "/staff/jobs";
    case "client_invoice_ready":
      return options.requestId ? `/client/invoices?inv=${encodeURIComponent(options.requestId)}` : "/client/invoices";
    case "payout_ready":
      return role === "guard" ? "/guard/earnings" : "/staff/payments";
    case "dispute_update":
      if (role === "client") {
        return options.ticketId ? `/client/support?st=${encodeURIComponent(options.ticketId)}` : "/client/support";
      }
      if (role === "guard") {
        return options.ticketId ? `/guard/support?st=${encodeURIComponent(options.ticketId)}` : "/guard/support";
      }
      return options.ticketId ? `/staff/disputes?st=${encodeURIComponent(options.ticketId)}` : "/staff/disputes";
    case "assignment":
    case "guard_application":
      if (role === "client") {
        return options.requestId ? `/client/requests?jc=${encodeURIComponent(options.requestId)}` : "/client/requests";
      }
      if (type === "guard_application") {
        return options.requestId ? `/staff/jobs?j=${encodeURIComponent(options.requestId)}` : "/staff/jobs";
      }
      return options.requestId ? `/guard/my-jobs?jc=${encodeURIComponent(options.requestId)}` : "/guard/my-jobs";
    case "guard_trusted_status":
      return "/guard/profile";
    case "client_trusted_status":
      return "/client/profile";
    case "job_relisted":
      return options.requestId ? `/client/requests?jc=${encodeURIComponent(options.requestId)}` : "/client/requests";
    case "job_schedule_changed":
      return options.requestId ? `/guard/my-jobs?jc=${encodeURIComponent(options.requestId)}` : "/guard/my-jobs";
    case "pre_shift_briefing":
      return options.requestId ? `/guard/map?jc=${encodeURIComponent(options.requestId)}` : "/guard/map";
    case "team_chat_message":
      if (role === "guard") {
        return options.requestId ? `/guard/messages?tc=${encodeURIComponent(options.requestId)}` : "/guard/messages";
      }
      return options.requestId ? `/staff/messages?mtab=team&jc=${encodeURIComponent(options.requestId)}` : "/staff/messages?mtab=team";
    case "standing_crew_invite":
      return "/guard/crew";
    default:
      if (isStaff) return resolveNotificationUrl(type, options);
      if (role === "client") return "/client/home";
      if (role === "guard") return "/guard/map";
      return resolveNotificationUrl(type, options);
  }
}
function rolesForNotificationType(type) {
  switch (type) {
    case "missed_checkin":
    case "guard_checkin":
    case "guard_clockout":
    case "guard_arrived":
    case "guard_en_route":
    case "guard_left_site":
    case "guard_break_start":
    case "guard_break_end":
      return ["dispatch", "admin"];
    case "job_open_to_guards":
      return ["guard"];
    case "client_cash_payment_requested":
    case "guard_cash_payout_requested":
    case "stripe_payment_complete":
      return ["dispatch", "admin"];
    case "assignment":
      return ["guard"];
    case "guard_application":
      return ["dispatch", "admin"];
    case "crew_lead_request":
      return ["dispatch", "admin"];
    case "emergency_alert":
      return ["guard", "client", "dispatch", "admin"];
    case "support_message":
      return ["dispatch", "admin", "client", "guard"];
    case "job_chat_message":
      return ["client", "guard", "dispatch", "admin"];
    case "staff_message":
      return ["dispatch", "admin"];
    case "guard_message":
      return ["guard"];
    case "client_message":
      return ["client"];
    case "job_submitted":
    case "guard_pending_approval":
    case "client_pending_approval":
    case "credential_pending":
    case "payment_attention":
      return ["dispatch", "admin"];
    case "client_invoice_ready":
      return ["client"];
    case "support_ticket":
      return ["dispatch", "admin"];
    case "support_ticket_status":
      return ["client", "guard"];
    case "dispute_update":
      return ["dispatch", "admin", "client", "guard"];
    case "guard_trusted_status":
      return ["guard"];
    case "client_trusted_status":
      return ["client"];
    case "job_relisted":
      return ["client"];
    case "job_schedule_changed":
      return ["guard"];
    case "pre_shift_briefing":
      return ["guard"];
    case "team_chat_message":
      return ["guard", "dispatch", "admin"];
    case "standing_crew_invite":
      return ["guard"];
    case "company_placard_expiry":
      return ["dispatch", "admin"];
    case "test":
      return [];
    default:
      return ["guard", "dispatch"];
  }
}
function buildNotificationData(type, options = {}) {
  const urlOptions = {
    guardId: options.guardId,
    requestId: options.requestId,
    ticketId: options.ticketId
  };
  const url = options.url ?? (options.role ? resolveNotificationUrlForRole(type, options.role, urlOptions) : resolveNotificationUrl(type, urlOptions));
  return {
    type,
    url,
    siteId: options.siteId,
    guardId: options.guardId,
    requestId: options.requestId,
    ticketId: options.ticketId,
    priority: options.priority ?? (type === "emergency_alert" ? "high" : "normal")
  };
}

// api/_push/delivery.ts
var PREF_COLUMN = {
  assignment: "assignment",
  guard_checkin: "guard_checkin",
  guard_clockout: "guard_clockout",
  guard_arrived: "guard_arrived",
  guard_left_site: "guard_left_site",
  guard_break_start: "guard_break_start",
  guard_break_end: "guard_break_end",
  missed_checkin: "missed_checkin",
  emergency_alert: "emergency_alert",
  support_message: "support_message",
  job_chat_message: "job_chat_message",
  staff_message: "staff_message",
  guard_message: "guard_message",
  client_message: "client_message",
  job_submitted: "job_submitted",
  job_open_to_guards: "job_open_to_guards",
  guard_application: "guard_application",
  guard_pending_approval: "guard_pending_approval",
  client_pending_approval: "client_pending_approval",
  credential_pending: "credential_pending",
  payment_attention: "payment_attention",
  client_invoice_ready: "client_invoice_ready",
  client_cash_payment_requested: "payment_attention",
  guard_cash_payout_requested: "payment_attention",
  stripe_payment_complete: "payment_attention",
  support_ticket: "support_ticket",
  support_ticket_status: "support_ticket_status",
  dispute_update: "dispute_update",
  guard_trusted_status: "guard_trusted_status",
  client_trusted_status: "client_trusted_status",
  job_relisted: "job_relisted",
  job_schedule_changed: "job_schedule_changed",
  team_chat_message: "team_chat_message",
  standing_crew_invite: "standing_crew_invite",
  crew_lead_request: "crew_lead_request",
  pre_shift_briefing: "pre_shift_briefing",
  guard_en_route: "guard_arrived",
  account_update: "support_ticket_status",
  job_status_update: "assignment",
  payout_ready: "assignment",
  company_placard_expiry: "company_placard_expiry"
};
async function isTypeEnabledForUser(db, userId, type) {
  const column = PREF_COLUMN[type];
  if (!column) return true;
  const { data, error } = await db.from("notification_preferences").select(column).eq("user_id", userId).maybeSingle();
  if (error || !data) return true;
  return data[column] !== false;
}
var MAX_RETRIES = 2;
var RETRY_DELAY_MS = 500;
var vapidConfigured = false;
var webPushModule = null;
async function getWebPush() {
  if (!webPushModule) {
    const mod = await import("web-push");
    webPushModule = "default" in mod && mod.default ? mod.default : mod;
  }
  return webPushModule;
}
async function ensureVapidConfigured() {
  const publicKey = process.env.VAPID_PUBLIC_KEY?.trim();
  const privateKey = process.env.VAPID_PRIVATE_KEY?.trim();
  const subject = process.env.VAPID_SUBJECT?.trim() || "mailto:support@guardr.co";
  if (!publicKey || !privateKey) return false;
  if (vapidConfigured) return true;
  const webpush = await getWebPush();
  webpush.setVapidDetails(subject, publicKey, privateKey);
  vapidConfigured = true;
  return true;
}
function isInQuietHours(quietStart, quietEnd, now = /* @__PURE__ */ new Date()) {
  if (!quietStart || !quietEnd) return false;
  const toMinutes = (time) => {
    const [h, m] = time.split(":").map(Number);
    return h * 60 + m;
  };
  const current = now.getHours() * 60 + now.getMinutes();
  const start = toMinutes(quietStart);
  const end = toMinutes(quietEnd);
  if (start === end) return false;
  if (start < end) return current >= start && current < end;
  return current >= start || current < end;
}
async function sleep(ms) {
  await new Promise((resolve) => setTimeout(resolve, ms));
}
async function sendToSubscription(subscription, payload, attempt = 0) {
  if (isFcmNativeEndpoint(subscription.endpoint)) {
    return sendFcmNativeNotification(subscription.endpoint, payload, attempt);
  }
  if (!await ensureVapidConfigured()) {
    return { ok: false, endpoint: subscription.endpoint };
  }
  try {
    const webpush = await getWebPush();
    await webpush.sendNotification(
      {
        endpoint: subscription.endpoint,
        keys: { p256dh: subscription.p256dh, auth: subscription.auth }
      },
      JSON.stringify(payload),
      {
        TTL: 60 * 60,
        urgency: payload.priority === "high" ? "high" : "normal"
      }
    );
    return { ok: true };
  } catch (err) {
    const statusCode = err && typeof err === "object" && "statusCode" in err ? Number(err.statusCode) : void 0;
    if (attempt < MAX_RETRIES && statusCode !== 404 && statusCode !== 410) {
      await sleep(RETRY_DELAY_MS * (attempt + 1));
      return sendToSubscription(subscription, payload, attempt + 1);
    }
    return { ok: false, statusCode, endpoint: subscription.endpoint };
  }
}
async function removeInvalidSubscriptions(db, endpoints) {
  if (!endpoints.length) return;
  await db.from("push_subscriptions").delete().in("endpoint", endpoints);
}
async function deliverToSubscriptions(db, subscriptions, payload) {
  if (!subscriptions.length) return { sent: 0, failed: 0 };
  const webPushReady = await ensureVapidConfigured();
  const fcmReady = isFcmConfigured();
  if (!webPushReady && !fcmReady) return { sent: 0, failed: subscriptions.length };
  const prefCache = /* @__PURE__ */ new Map();
  const filtered = [];
  for (const sub of subscriptions) {
    if (payload.excludeUserId && sub.user_id === payload.excludeUserId) {
      continue;
    }
    if (!sub.user_id) {
      filtered.push(sub);
      continue;
    }
    let enabled = prefCache.get(sub.user_id);
    if (enabled === void 0) {
      enabled = await isTypeEnabledForUser(db, sub.user_id, payload.type);
      prefCache.set(sub.user_id, enabled);
    }
    if (enabled) filtered.push(sub);
  }
  if (!filtered.length) return { sent: 0, failed: 0 };
  const urlOptions = {
    guardId: payload.guardId,
    requestId: payload.requestId,
    ticketId: payload.ticketId
  };
  let sent = 0;
  let failed = 0;
  const staleEndpoints = [];
  for (const sub of filtered) {
    if (payload.type !== "emergency_alert" && payload.priority !== "high" && isInQuietHours(sub.quiet_hours_start, sub.quiet_hours_end)) {
      continue;
    }
    const platformRole = pushRoleToPlatformRole(sub.push_role);
    const data = buildNotificationData(payload.type, {
      url: payload.url ?? resolveNotificationUrlForRole(payload.type, platformRole, urlOptions),
      siteId: payload.siteId,
      guardId: payload.guardId,
      requestId: payload.requestId,
      ticketId: payload.ticketId,
      priority: payload.priority,
      role: platformRole
    });
    const message = {
      title: payload.title,
      body: payload.body,
      url: data.url,
      eventType: payload.type,
      data,
      tag: payload.siteId ? `${payload.type}-${payload.siteId}` : payload.type,
      priority: data.priority
    };
    const result = await sendToSubscription(sub, message);
    if (result.ok) {
      sent += 1;
    } else {
      failed += 1;
      if (result.statusCode === 404 || result.statusCode === 410) {
        staleEndpoints.push(result.endpoint);
      }
    }
  }
  await removeInvalidSubscriptions(db, staleEndpoints);
  return { sent, failed };
}
async function sendNotificationToUser(db, userId, payload) {
  const enabled = await isTypeEnabledForUser(db, userId, payload.type);
  if (!enabled) return { sent: 0, failed: 0 };
  const { data: subscriptions, error } = await db.from("push_subscriptions").select("endpoint, p256dh, auth, quiet_hours_start, quiet_hours_end, user_id, push_role").eq("user_id", userId);
  if (error) throw new Error(error.message);
  return deliverToSubscriptions(db, subscriptions ?? [], payload);
}
async function sendNotificationToRole(db, role, payload) {
  const roles = role === "dispatch" ? ["dispatch", "admin"] : [role];
  const { data: subscriptions, error } = await db.from("push_subscriptions").select("endpoint, p256dh, auth, quiet_hours_start, quiet_hours_end, user_id, push_role").in("push_role", roles);
  if (error) throw new Error(error.message);
  return deliverToSubscriptions(db, subscriptions ?? [], payload);
}
async function dispatchPushNotification(db, payload) {
  if (payload.userId) {
    return sendNotificationToUser(db, payload.userId, payload);
  }
  if (payload.role) {
    return sendNotificationToRole(db, payload.role, payload);
  }
  const roles = rolesForNotificationType(payload.type);
  let sent = 0;
  let failed = 0;
  for (const role of roles) {
    const result = await sendNotificationToRole(db, role, payload);
    sent += result.sent;
    failed += result.failed;
  }
  return { sent, failed };
}

// api/_push/eventDispatch.ts
var EVENT_DEFAULTS = {
  guard_checkin: (event) => ({
    title: "Guard check-in",
    body: event.guardName ? `${event.guardName} checked in${event.location ? ` at ${event.location}` : ""}` : "A guard completed a check-in"
  }),
  guard_clockout: (event) => ({
    title: "Guard clock-out",
    body: event.guardName ? `${event.guardName} clocked out${event.location ? ` at ${event.location}` : ""}` : "A guard clocked out"
  }),
  guard_arrived: (event) => ({
    title: "Guard arrived on site",
    body: event.guardName ? `${event.guardName} arrived${event.location ? ` at ${event.location}` : ""}` : "Your guard arrived on site"
  }),
  guard_en_route: (event) => ({
    title: "Guard en route",
    body: event.body ?? (event.guardName ? `${event.guardName} is heading to${event.location ? ` ${event.location}` : " site"}` : "Your guard is en route to the job site")
  }),
  standing_crew_invite: (event) => ({
    title: event.title ?? "Standing crew invitation",
    body: event.body || "You have a standing crew update"
  }),
  guard_left_site: (event) => ({
    title: "Guard left job site",
    body: event.guardName ? `${event.guardName} left the job site${event.location ? ` at ${event.location}` : ""}` : "A guard left the job site during an active shift"
  }),
  guard_break_start: (event) => ({
    title: "Guard on break",
    body: event.guardName ? `${event.guardName} started a break${event.location ? ` at ${event.location}` : ""}` : "A guard started a break"
  }),
  guard_break_end: (event) => ({
    title: "Guard back on duty",
    body: event.guardName ? `${event.guardName} ended break and is back on duty${event.location ? ` at ${event.location}` : ""}` : "A guard ended a break"
  }),
  missed_checkin: (event) => ({
    title: "Missed check-in",
    body: event.guardName ? `${event.guardName} missed an hourly check-in` : "A guard missed an hourly check-in"
  }),
  assignment: (event) => ({
    title: "New assignment",
    body: event.body ?? (event.location ? `You have a new assignment at ${event.location}` : "You have a new assignment update")
  }),
  emergency_alert: (event) => ({
    title: "Emergency alert",
    body: event.body || "Immediate attention required on an active shift"
  }),
  support_message: (event) => ({
    title: "Support message",
    body: event.body || "You have a new support message"
  }),
  job_chat_message: (event) => ({
    title: "Job chat",
    body: event.body || "New message on an active job"
  }),
  staff_message: (event) => ({
    title: "Staff chat",
    body: event.body || "New message from the Guardr team"
  }),
  guard_message: (event) => ({
    title: "Guard chat",
    body: event.body || "New message from another guard"
  }),
  client_message: (event) => ({
    title: "Client chat",
    body: event.body || "New message from another client"
  }),
  job_submitted: (event) => ({
    title: "New job request",
    body: event.body || "A client submitted a job awaiting staff review"
  }),
  guard_application: (event) => ({
    title: "Guard application",
    body: event.body || "A guard applied to an open job offer"
  }),
  crew_lead_request: (event) => ({
    title: "Crew lead request",
    body: event.body || "A trusted guard requested approval to lead their own standing crew"
  }),
  guard_pending_approval: (event) => ({
    title: "Guard pending approval",
    body: event.body || "A guard account needs staff review"
  }),
  client_pending_approval: (event) => ({
    title: "Client pending approval",
    body: event.body || "A client account needs staff review"
  }),
  credential_pending: (event) => ({
    title: "Credential review",
    body: event.body || "A guard submitted credentials for review"
  }),
  payment_attention: (event) => ({
    title: "Payment attention",
    body: event.body || "A payment or payout needs staff action"
  }),
  client_invoice_ready: (event) => ({
    title: event.title ?? "Invoice ready",
    body: event.body || "Your job invoice is ready for payment"
  }),
  client_cash_payment_requested: (event) => ({
    title: "Client cash payment request",
    body: event.body || "A client requested to pay in cash"
  }),
  guard_cash_payout_requested: (event) => ({
    title: "Guard cash payout request",
    body: event.body || "A guard requested cash payout"
  }),
  stripe_payment_complete: (event) => ({
    title: "Stripe payment received",
    body: event.body || "A card payment completed successfully"
  }),
  job_open_to_guards: (event) => ({
    title: "New job on the map",
    body: event.body || "A paid job is now open for guards"
  }),
  support_ticket: (event) => ({
    title: "Support ticket",
    body: event.body || "A new support ticket needs staff attention"
  }),
  support_ticket_status: (event) => ({
    title: "Support update",
    body: event.body || "Your support ticket status changed"
  }),
  dispute_update: (event) => ({
    title: "Dispute update",
    body: event.body || "A dispute needs your attention"
  }),
  guard_trusted_status: (event) => ({
    title: event.title ?? "Trusted guard update",
    body: event.body || "Your trusted guard status changed"
  }),
  client_trusted_status: (event) => ({
    title: event.title ?? "Trusted client update",
    body: event.body || "Your trusted client status changed"
  }),
  job_relisted: (event) => ({
    title: "Job back on marketplace",
    body: event.body || "A job was re-listed and is open for guards again"
  }),
  job_schedule_changed: (event) => ({
    title: "Shift time changed",
    body: event.body || "Your job schedule was updated"
  }),
  team_chat_message: (event) => ({
    title: "Crew chat",
    body: event.body || "New message in crew chat"
  }),
  account_update: (event) => ({
    title: event.title ?? "Account update",
    body: event.body || "Your Guardr account was updated"
  }),
  job_status_update: (event) => ({
    title: event.title ?? "Job update",
    body: event.body || "A job you are involved with was updated"
  }),
  payout_ready: (event) => ({
    title: event.title ?? "Payout ready",
    body: event.body || "Earnings are ready to collect in Pay"
  }),
  company_placard_expiry: (event) => ({
    title: event.title ?? "Company placard reminder",
    body: event.body || "A company credential needs attention in Staff Settings"
  }),
  pre_shift_briefing: (event) => ({
    title: event.title ?? "Shift briefing",
    body: event.body || "Review your pre-shift briefing before heading to site"
  })
};
function basePayload(event) {
  const fallbackFn = EVENT_DEFAULTS[event.type];
  const fallback = fallbackFn ? fallbackFn(event) : { title: "Guardr alert", body: event.body || "Operational update" };
  return {
    title: event.title ?? fallback.title,
    body: event.body ?? fallback.body,
    type: event.type,
    guardId: event.guardId,
    requestId: event.requestId,
    ticketId: event.ticketId,
    siteId: event.siteId,
    url: event.url,
    priority: event.type === "emergency_alert" ? "high" : event.priority ?? "normal",
    excludeUserId: event.excludeUserId
  };
}
async function loadJobParticipants(db, requestId) {
  const { data } = await db.from("security_requests").select("client_id, assigned_guard_id").eq("id", requestId).maybeSingle();
  return {
    clientId: data?.client_id ?? null,
    guardId: data?.assigned_guard_id ?? null
  };
}
async function buildEventDispatchPayloads(db, event) {
  const payload = basePayload(event);
  if (event.type === "assignment") {
    if (event.recipientUserId) {
      return [{ ...payload, userId: event.recipientUserId }];
    }
    if (event.guardId) {
      return [{ ...payload, userId: event.guardId }];
    }
    return [{ ...payload, role: "guard" }];
  }
  if (event.type === "support_message" && event.recipientUserId) {
    return [{ ...payload, userId: event.recipientUserId }];
  }
  if (event.type === "job_chat_message" && event.recipientUserId) {
    return [{ ...payload, userId: event.recipientUserId }];
  }
  if (event.type === "emergency_alert" && event.requestId) {
    const { clientId, guardId } = await loadJobParticipants(db, event.requestId);
    const payloads = [{ ...payload, role: "dispatch" }];
    if (guardId) payloads.push({ ...payload, userId: guardId });
    if (clientId) payloads.push({ ...payload, userId: clientId });
    return payloads;
  }
  if (event.type === "missed_checkin" && event.requestId) {
    const tier = event.checkinEscalationTier ?? "legacy";
    const { clientId, guardId } = await loadJobParticipants(db, event.requestId);
    if (tier === "alert") {
      const payloads2 = [];
      if (guardId) {
        payloads2.push({
          ...payload,
          userId: guardId,
          title: "Hourly check-in overdue",
          body: event.location ? `Check in now \u2014 you are 5+ minutes past due at ${event.location}` : "Check in now \u2014 you are 5+ minutes past your hourly check-in",
          priority: "high"
        });
      }
      if (clientId) {
        payloads2.push({
          ...payload,
          userId: clientId,
          title: "Guard check-in overdue",
          body: event.guardName ? `${event.guardName} is 5+ minutes past due for an hourly check-in${event.location ? ` at ${event.location}` : ""}` : "Your guard is overdue for an hourly check-in"
        });
      }
      return payloads2;
    }
    if (tier === "staff") {
      return [
        {
          ...payload,
          role: "dispatch",
          title: "Check-in overdue \u2014 staff alert",
          body: event.guardName ? `${event.guardName} is 10+ minutes past due for hourly check-in${event.location ? ` at ${event.location}` : ""}` : "A guard is 10+ minutes past due for hourly check-in"
        }
      ];
    }
    if (tier === "escalate") {
      const payloads2 = [
        {
          ...payload,
          role: "dispatch",
          title: "Check-in escalation",
          body: event.guardName ? `ESCALATION: ${event.guardName} missed hourly check-in for 15+ minutes${event.location ? ` at ${event.location}` : ""}` : "ESCALATION: guard missed hourly check-in for 15+ minutes",
          priority: "high"
        }
      ];
      if (clientId) {
        payloads2.push({
          ...payload,
          userId: clientId,
          title: "Check-in escalation",
          body: "Your guard has not completed a required hourly check-in. Guardr staff has been escalated.",
          priority: "high"
        });
      }
      return payloads2;
    }
    const payloads = [{ ...payload, role: "dispatch" }];
    if (guardId) {
      payloads.push({
        ...payload,
        userId: guardId,
        title: "Missed check-in reminder",
        body: event.location ? `You missed your hourly check-in at ${event.location}` : "You missed your hourly check-in \u2014 please check in now"
      });
    }
    return payloads;
  }
  if (event.type === "support_ticket_status" && event.recipientUserId) {
    return [{ ...payload, userId: event.recipientUserId }];
  }
  if (event.type === "client_invoice_ready" && event.recipientUserId) {
    return [{ ...payload, userId: event.recipientUserId }];
  }
  if (event.type === "account_update" && event.recipientUserId) {
    return [{ ...payload, userId: event.recipientUserId }];
  }
  if (event.type === "payout_ready") {
    if (event.recipientUserId) {
      return [{ ...payload, userId: event.recipientUserId }];
    }
    if (event.guardId) {
      return [{ ...payload, userId: event.guardId }];
    }
    return [];
  }
  if (event.type === "company_placard_expiry" && event.recipientUserId) {
    return [{ ...payload, userId: event.recipientUserId }];
  }
  if (event.type === "pre_shift_briefing") {
    const userId = event.recipientUserId ?? event.guardId;
    if (!userId) return [];
    return [{ ...payload, userId }];
  }
  if (event.type === "job_status_update") {
    const payloads = [{ ...payload, role: "dispatch" }];
    if (event.clientId) payloads.push({ ...payload, userId: event.clientId });
    if (event.guardId) payloads.push({ ...payload, userId: event.guardId });
    else if (event.recipientUserId) payloads.push({ ...payload, userId: event.recipientUserId });
    return payloads;
  }
  if ((event.type === "guard_trusted_status" || event.type === "client_trusted_status" || event.type === "job_relisted" || event.type === "job_schedule_changed" || event.type === "standing_crew_invite" || event.type === "crew_lead_request") && event.recipientUserId) {
    return [{ ...payload, userId: event.recipientUserId }];
  }
  if (event.type === "crew_lead_request") {
    return [{ ...payload, role: "dispatch" }];
  }
  if (event.type === "standing_crew_invite" && event.guardId && !event.recipientUserId) {
    return [{ ...payload, userId: event.guardId }];
  }
  if (event.type === "team_chat_message") {
    if (event.recipientUserId) {
      return [{ ...payload, userId: event.recipientUserId }];
    }
    return [{ ...payload, role: "dispatch" }];
  }
  if (event.type === "job_submitted" && event.recipientUserId) {
    return [{ ...payload, userId: event.recipientUserId }];
  }
  if (event.type === "job_open_to_guards") {
    if (event.guardId || event.recipientUserId) {
      const userId = event.recipientUserId ?? event.guardId;
      if (!userId) return [];
      return [
        {
          ...payload,
          userId,
          priority: event.priority ?? "high",
          title: event.title ?? "Priority job for your crew",
          body: event.body ?? "A new job matches your standing crew size \u2014 browse and apply early."
        }
      ];
    }
    return [{ ...payload, role: "guard" }];
  }
  if (event.type === "guard_application") {
    const payloads = [{ ...payload, role: "dispatch" }];
    if (event.recipientUserId) {
      payloads.push({ ...payload, userId: event.recipientUserId });
    } else if (event.clientId) {
      payloads.push({ ...payload, userId: event.clientId });
    }
    return payloads;
  }
  if (event.type === "stripe_payment_complete" || event.type === "client_cash_payment_requested" || event.type === "guard_cash_payout_requested") {
    return [{ ...payload, role: "dispatch" }];
  }
  if (event.type === "support_ticket") {
    return [{ ...payload, role: "dispatch" }];
  }
  if (event.type === "dispute_update") {
    const payloads = [{ ...payload, role: "dispatch" }];
    if (event.guardId) payloads.push({ ...payload, userId: event.guardId });
    if (event.clientId) payloads.push({ ...payload, userId: event.clientId });
    else if (event.recipientUserId) payloads.push({ ...payload, userId: event.recipientUserId });
    return payloads;
  }
  if (event.type === "staff_message" || event.type === "job_submitted" || event.type === "guard_pending_approval" || event.type === "client_pending_approval" || event.type === "credential_pending" || event.type === "payment_attention" || event.type === "support_message" && !event.recipientUserId || event.type === "job_chat_message" && !event.recipientUserId) {
    return [{ ...payload, role: "dispatch" }];
  }
  if (event.type === "guard_message") {
    return [{ ...payload, role: "guard" }];
  }
  if (event.type === "client_message") {
    return [{ ...payload, role: "client" }];
  }
  if (event.type === "guard_en_route") {
    const payloads = [{ ...payload, role: "dispatch" }];
    if (event.requestId) {
      const { clientId } = await loadJobParticipants(db, event.requestId);
      if (clientId) payloads.push({ ...payload, userId: clientId });
    } else if (event.recipientUserId) {
      payloads.push({ ...payload, userId: event.recipientUserId });
    }
    return payloads;
  }
  if (event.type === "guard_checkin" || event.type === "guard_clockout" || event.type === "guard_arrived" || event.type === "guard_break_start" || event.type === "guard_break_end" || event.type === "guard_left_site") {
    const payloads = [{ ...payload, role: "dispatch" }];
    if (event.requestId) {
      const { clientId, guardId } = await loadJobParticipants(db, event.requestId);
      if (clientId) payloads.push({ ...payload, userId: clientId });
      if (event.type === "guard_left_site" && guardId) {
        payloads.push({
          ...payload,
          userId: guardId,
          title: "You left the job site",
          body: event.location ? `You moved away from ${event.location} during your shift` : "You left the job site during your active shift"
        });
      }
    } else if (event.recipientUserId) {
      payloads.push({ ...payload, userId: event.recipientUserId });
    }
    return payloads;
  }
  return [payload];
}

// api/_push/eventAuth.ts
var STAFF_ROLES = /* @__PURE__ */ new Set(["moderator", "administrator", "director", "owner", "staff", "auditor"]);
function isStaffSession(session) {
  return STAFF_ROLES.has(session.platformRole) || STAFF_ROLES.has(session.role);
}
async function isJobParticipant(db, requestId, userId) {
  const { data } = await db.from("security_requests").select("client_id, assigned_guard_id").eq("id", requestId).maybeSingle();
  if (!data) return false;
  return data.client_id === userId || data.assigned_guard_id === userId;
}
async function isSupportTicketParticipant(db, ticketId, userId) {
  const { data } = await db.from("support_tickets").select("user_id").eq("id", ticketId).maybeSingle();
  return data?.user_id === userId;
}
async function authorizePushEvent(db, session, event) {
  const { type } = event;
  switch (type) {
    case "test":
      return "Test notifications must use /api/push/test";
    case "staff_message":
      return isStaffSession(session) ? null : "Only staff can send this notification type";
    case "client_pending_approval":
      if (isStaffSession(session)) return null;
      if (session.platformRole === "client") return null;
      return "Only staff or the registering client can notify about pending approval";
    case "guard_pending_approval":
      if (isStaffSession(session)) return null;
      if (session.platformRole === "guard" && (!event.guardId || event.guardId === session.userId)) {
        return null;
      }
      return "Only staff or the registering guard can notify about pending approval";
    case "credential_pending":
      if (isStaffSession(session)) return null;
      if (session.platformRole === "guard" && event.guardId === session.userId) return null;
      return "Only staff or the submitting guard can send credential review notifications";
    case "job_submitted":
      if (isStaffSession(session)) return null;
      if (session.platformRole === "client") return null;
      if (event.requestId && await isJobParticipant(db, event.requestId, session.userId)) {
        return null;
      }
      return "Only staff or the submitting client can notify about new jobs";
    case "guard_application":
      if (isStaffSession(session)) return null;
      if (session.platformRole === "guard" && event.guardId === session.userId) return null;
      return "Only staff or the applying guard can send application notifications";
    case "crew_lead_request":
      if (isStaffSession(session)) return null;
      if (session.platformRole === "guard" && event.guardId === session.userId) return null;
      return "Only staff or the requesting guard can send crew lead requests";
    case "guard_message":
      if (isStaffSession(session)) return null;
      if (session.platformRole === "guard") return null;
      return "Only staff or active guards can post to guard chat";
    case "client_message":
      if (isStaffSession(session)) return null;
      if (session.platformRole === "client") return null;
      return "Only staff or active clients can post to client chat";
    case "guard_checkin":
    case "guard_clockout":
    case "guard_arrived":
    case "guard_en_route":
    case "guard_left_site":
    case "guard_break_start":
    case "guard_break_end":
    case "missed_checkin":
      if (isStaffSession(session)) return null;
      if (event.guardId && event.guardId === session.userId) return null;
      if (event.requestId && await isJobParticipant(db, event.requestId, session.userId)) {
        return null;
      }
      return "Not authorized to report shift events for this job";
    case "job_open_to_guards":
      if (isStaffSession(session)) return null;
      if (session.platformRole === "client") return null;
      if (event.requestId && await isJobParticipant(db, event.requestId, session.userId)) {
        return null;
      }
      return "Only staff or the job client can notify guards of open positions";
    case "client_cash_payment_requested":
      if (isStaffSession(session)) return null;
      if (session.platformRole === "client") return null;
      if (event.requestId && await isJobParticipant(db, event.requestId, session.userId)) {
        return null;
      }
      return "Only staff or the job client can send cash payment request notifications";
    case "guard_cash_payout_requested":
      if (isStaffSession(session)) return null;
      if (session.platformRole === "guard") return null;
      return "Only staff or guards can send payout request notifications";
    case "stripe_payment_complete":
      return isStaffSession(session) ? null : "Only staff can send payment completion notifications";
    case "payment_attention":
      if (isStaffSession(session)) return null;
      if (session.platformRole === "guard") return null;
      if (event.requestId && await isJobParticipant(db, event.requestId, session.userId)) {
        return null;
      }
      return "Only staff, guards, or job participants can send payment attention notifications";
    case "assignment":
      if (isStaffSession(session)) return null;
      if (event.guardId && event.guardId === session.userId) return null;
      if (event.recipientUserId && event.recipientUserId === session.userId) return null;
      if (event.requestId && await isJobParticipant(db, event.requestId, session.userId)) {
        return null;
      }
      return "Not authorized to send assignment notifications for this job";
    case "emergency_alert":
      if (isStaffSession(session)) return null;
      if (event.requestId && await isJobParticipant(db, event.requestId, session.userId)) {
        return null;
      }
      if (event.ticketId && await isSupportTicketParticipant(db, event.ticketId, session.userId)) {
        return null;
      }
      return "Not authorized to send emergency alerts for this context";
    case "support_message":
      if (isStaffSession(session)) return null;
      if (event.recipientUserId && event.recipientUserId === session.userId) return null;
      if (event.ticketId && await isSupportTicketParticipant(db, event.ticketId, session.userId)) {
        return null;
      }
      return "Not authorized to send support messages for this ticket";
    case "job_chat_message":
      if (isStaffSession(session)) return null;
      if (event.requestId && await isJobParticipant(db, event.requestId, session.userId)) {
        return null;
      }
      return "Not authorized to send job chat messages for this job";
    case "support_ticket":
      if (isStaffSession(session)) return null;
      if (event.ticketId && await isSupportTicketParticipant(db, event.ticketId, session.userId)) {
        return null;
      }
      return "Not authorized to file this support ticket";
    case "support_ticket_status":
      return isStaffSession(session) ? null : "Only staff can send support status updates";
    case "client_invoice_ready":
      return isStaffSession(session) ? null : "Only staff can send client invoice notifications";
    case "account_update":
      return isStaffSession(session) ? null : "Only staff can send account update notifications";
    case "payout_ready":
      return isStaffSession(session) ? null : "Only staff can send payout ready notifications";
    case "job_status_update":
      if (isStaffSession(session)) return null;
      if (session.platformRole === "client" || session.platformRole === "guard") {
        if (event.requestId && await isJobParticipant(db, event.requestId, session.userId)) {
          return null;
        }
      }
      return "Not authorized to send job status updates for this context";
    case "dispute_update":
      if (isStaffSession(session)) return null;
      if (event.ticketId && await isSupportTicketParticipant(db, event.ticketId, session.userId)) {
        return null;
      }
      if (event.requestId && await isJobParticipant(db, event.requestId, session.userId)) {
        return null;
      }
      return "Not authorized to send dispute updates for this context";
    case "guard_trusted_status":
    case "client_trusted_status":
      return isStaffSession(session) ? null : "Only staff can send trusted status notifications";
    case "job_relisted":
      if (isStaffSession(session)) return null;
      if (event.recipientUserId && event.recipientUserId === session.userId) return null;
      if (event.requestId && await isJobParticipant(db, event.requestId, session.userId)) {
        return null;
      }
      return "Not authorized to send job re-list notifications";
    case "job_schedule_changed":
      if (isStaffSession(session)) return null;
      if (event.recipientUserId && event.recipientUserId === session.userId) return null;
      if (event.requestId && await isJobParticipant(db, event.requestId, session.userId)) {
        return null;
      }
      return "Not authorized to send schedule change notifications for this job";
    case "pre_shift_briefing":
      if (isStaffSession(session)) return null;
      if (session.platformRole === "guard" && event.recipientUserId === session.userId && event.guardId === session.userId) {
        return null;
      }
      if (event.requestId && await isJobParticipant(db, event.requestId, session.userId)) {
        return null;
      }
      return "Not authorized to send pre-shift briefing reminders for this job";
    case "team_chat_message":
      if (isStaffSession(session)) return null;
      if (event.recipientUserId && event.recipientUserId === session.userId) return null;
      if (event.requestId && await isJobParticipant(db, event.requestId, session.userId)) {
        return null;
      }
      return "Not authorized to send crew chat notifications for this job";
    case "standing_crew_invite":
      if (isStaffSession(session)) return null;
      if (session.platformRole === "guard" && event.recipientUserId) return null;
      return "Only guards can send standing crew invitations";
    default:
      return "Unknown notification type";
  }
}

// api/_push/accountSessionAuth.ts
var STAFF_PLATFORM_ROLES = /* @__PURE__ */ new Set([
  "owner",
  "director",
  "administrator",
  "moderator",
  "staff",
  "auditor"
]);
function resolvePlatformRole(input) {
  if (input.legacyRole === "client") return "client";
  if (input.isStaff && input.staffRole) {
    switch (input.staffRole) {
      case "Founder":
      case "Owner":
        return "owner";
      case "Director":
        return "director";
      case "Administrator":
        return "administrator";
      case "Moderator":
        return "moderator";
    }
  }
  if (input.legacyRole === "auditor") return "moderator";
  if (input.legacyRole === "staff") return "administrator";
  return "guard";
}
async function verifyStaffSession(db, userId, email) {
  let { data, error } = await db.from("staff").select("id, email, staff_role").eq("id", userId).maybeSingle();
  if (!data && !error) {
    const byEmail = await db.from("staff").select("id, email, staff_role").eq("email", email).maybeSingle();
    data = byEmail.data ?? null;
    error = byEmail.error ?? null;
  }
  if (!data && error?.code === "42P01") return null;
  if (!data || data.email?.toLowerCase() !== email) return null;
  const platformRole = resolvePlatformRole({
    isStaff: true,
    staffRole: data.staff_role ?? void 0,
    legacyRole: "staff"
  });
  return { userId: data.id, email, role: platformRole, platformRole };
}
async function verifyFieldGuardSession(db, userId, email, credentialsRole) {
  let { data, error } = await db.from("guards").select("id, email, is_staff, staff_role, migrated_to_staff_at").eq("id", userId).maybeSingle();
  if (!data && !error) {
    const byEmail = await db.from("guards").select("id, email, is_staff, staff_role, migrated_to_staff_at").eq("email", email).maybeSingle();
    data = byEmail.data ?? null;
    error = byEmail.error ?? null;
  }
  if (!data && error?.code === "42P01") return null;
  if (!data || data.email?.toLowerCase() !== email) return null;
  if (data.migrated_to_staff_at) return null;
  const platformRole = resolvePlatformRole({
    isStaff: data.is_staff,
    staffRole: data.staff_role ?? void 0,
    legacyRole: data.is_staff ? "staff" : "guard"
  });
  if (platformRole !== credentialsRole && credentialsRole !== "staff" && credentialsRole !== "auditor") {
    console.warn(
      `Session role mismatch for ${email}: client sent ${credentialsRole}, db has ${platformRole}`
    );
  }
  return { userId: data.id, email, role: platformRole, platformRole };
}
async function verifyAccountSession(db, credentials) {
  if (!credentials?.userId || !credentials?.email || !credentials?.role) {
    return null;
  }
  const email = credentials.email.trim().toLowerCase();
  const { userId, role } = credentials;
  if (role === "client") {
    let { data } = await db.from("clients").select("id, email").eq("id", userId).maybeSingle();
    if (!data) {
      const byEmail = await db.from("clients").select("id, email").eq("email", email).maybeSingle();
      data = byEmail.data ?? null;
    }
    if (!data || data.email?.toLowerCase() !== email) return null;
    return { userId: data.id, email, role: "client", platformRole: "client" };
  }
  if (STAFF_PLATFORM_ROLES.has(role)) {
    const staffSession = await verifyStaffSession(db, userId, email);
    if (staffSession) return staffSession;
  }
  return verifyFieldGuardSession(db, userId, email, role);
}

// api/_push/sessionAuth.ts
async function verifySession(db, credentials) {
  return verifyAccountSession(db, credentials);
}

// api/_push/handlers.ts
function pushNotConfiguredResponse() {
  return { status: 503, body: { error: "Web Push is not configured. Set VAPID_PUBLIC_KEY and VAPID_PRIVATE_KEY." } };
}
async function dispatchPushEvent(db, event, options) {
  if (!event.type) {
    throw new Error("Notification type is required");
  }
  if (!isPushConfigured()) {
    throw new Error("Web Push is not configured");
  }
  const session = await verifySession(db, event);
  if (!session && !options?.skipAuth) {
    throw new Error("Unauthorized \u2014 invalid session");
  }
  if (session && !options?.skipAuth) {
    const authError = await authorizePushEvent(db, session, {
      type: event.type,
      guardId: event.guardId,
      requestId: event.requestId,
      recipientUserId: event.recipientUserId,
      ticketId: event.ticketId
    });
    if (authError) {
      throw new Error(authError);
    }
  }
  if (event.type === "missed_checkin" && event.requestId) {
    const tier = event.checkinEscalationTier ?? "legacy";
    const dueBucket = event.checkinDueBucket ?? Math.floor(Date.now() / (60 * 60 * 1e3));
    const dedupKey = tier === "legacy" ? missedCheckinDedupKey(event.requestId, dueBucket) : checkInEscalationDedupKey(event.requestId, dueBucket, tier);
    const alreadySent = await claimNotificationDedup(db, dedupKey, "missed_checkin");
    if (alreadySent) {
      return { sent: 0, failed: 0 };
    }
  }
  const excludeUserId = event.type === "guard_message" || event.type === "client_message" || event.type === "staff_message" ? session?.userId : void 0;
  const payloads = await buildEventDispatchPayloads(db, {
    ...event,
    type: event.type,
    excludeUserId,
    clientId: event.clientId,
    priority: event.priority
  });
  let sent = 0;
  let failed = 0;
  for (const payload of payloads) {
    const result = await dispatchPushNotification(db, payload);
    sent += result.sent;
    failed += result.failed;
  }
  return { sent, failed };
}
async function handlePushEvent(db, body) {
  const session = await verifySession(db, body);
  if (!session) {
    return { status: 401, body: { error: "Unauthorized \u2014 invalid session" } };
  }
  if (!body.type) {
    return { status: 400, body: { error: "Notification type is required" } };
  }
  if (!isPushConfigured()) {
    return pushNotConfiguredResponse();
  }
  try {
    const result = await dispatchPushEvent(db, body);
    return { status: 200, body: { ok: true, ...result } };
  } catch (err) {
    const message = err instanceof Error ? err.message : "Push event failed";
    const status = message.startsWith("Unauthorized") || message.includes("Not authorized") ? 403 : 500;
    return { status, body: { error: message } };
  }
}

// api/_push/entries/events.ts
async function getSupabaseAdmin() {
  const url = process.env.SUPABASE_URL || process.env.NEXT_PUBLIC_SUPABASE_URL || process.env.VITE_SUPABASE_URL;
  const serviceKey = process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.SUPABASE_KEY;
  if (!url || !serviceKey) return null;
  const { createClient } = await import("@supabase/supabase-js");
  return createClient(url, serviceKey, {
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
async function handler(req, res) {
  if (applyApiCors(req, res)) return;
  if (req.method !== "POST") {
    return res.status(405).json({ error: "Method not allowed" });
  }
  try {
    const db = await getSupabaseAdmin();
    if (!db) {
      return res.status(503).json({ error: "Database is not configured" });
    }
    const result = await handlePushEvent(db, req.body ?? {});
    return res.status(result.status).json(result.body);
  } catch (err) {
    const message = err instanceof Error ? err.message : "Push event failed";
    console.error("Push events error:", message, err);
    return res.status(500).json({ error: message });
  }
}
export {
  handler as default
};
