// Generated by scripts/bundle-push-handlers.mjs — do not edit.
// @ts-nocheck

// api/_push/config.ts
function isPushConfigured() {
  return !!(process.env.VAPID_PUBLIC_KEY?.trim() && process.env.VAPID_PRIVATE_KEY?.trim());
}

// api/_push/dedup.ts
var DEDUP_TTL_MS = 25 * 60 * 60 * 1e3;

// api/_push/routing.ts
function pushRoleToPlatformRole(pushRole) {
  switch (pushRole) {
    case "guard":
      return "guard";
    case "client":
      return "client";
    case "dispatch":
    case "admin":
      return "administrator";
    default:
      return "administrator";
  }
}
function resolveNotificationUrl(type, options = {}) {
  switch (type) {
    case "missed_checkin":
    case "guard_checkin":
    case "guard_clockout":
    case "guard_break_start":
    case "guard_break_end":
      return options.requestId ? `/staff/jobs?j=${encodeURIComponent(options.requestId)}` : "/staff/jobs";
    case "assignment":
      return options.requestId ? `/guard/my-jobs?jc=${encodeURIComponent(options.requestId)}` : "/guard/my-jobs";
    case "emergency_alert":
      if (options.requestId) {
        return `/staff/jobs?j=${encodeURIComponent(options.requestId)}`;
      }
      if (options.ticketId) {
        return `/staff/support?st=${encodeURIComponent(options.ticketId)}`;
      }
      return "/staff/incidents";
    case "support_message":
      return options.ticketId ? `/staff/support?st=${encodeURIComponent(options.ticketId)}` : "/staff/support";
    case "job_chat_message":
      return options.requestId ? `/staff/messages?mtab=jobs&jc=${encodeURIComponent(options.requestId)}` : "/staff/messages?mtab=jobs";
    case "staff_message":
      return "/staff/messages?mtab=team";
    case "guard_message":
      return "/guard/guard-chat";
    case "job_submitted":
      return options.requestId ? `/staff/jobs?j=${encodeURIComponent(options.requestId)}` : "/staff/approvals?aq=job-offers";
    case "guard_application":
      return options.requestId ? `/staff/jobs?j=${encodeURIComponent(options.requestId)}` : "/staff/approvals?aq=applications";
    case "guard_pending_approval":
      return options.guardId ? `/staff/guards?g=${encodeURIComponent(options.guardId)}` : "/staff/approvals?aq=accounts";
    case "client_pending_approval":
      return "/staff/approvals?aq=accounts";
    case "credential_pending":
      return options.guardId ? `/staff/approvals?aq=credentials&g=${encodeURIComponent(options.guardId)}` : "/staff/approvals?aq=credentials";
    case "payment_attention":
      return options.requestId ? `/staff/payments?j=${encodeURIComponent(options.requestId)}` : "/staff/payments";
    case "support_ticket":
    case "support_ticket_status":
      return options.ticketId ? `/staff/messages?mtab=support&st=${encodeURIComponent(options.ticketId)}` : "/staff/messages?mtab=support";
    case "dispute_update":
      return options.ticketId ? `/staff/disputes?st=${encodeURIComponent(options.ticketId)}` : "/staff/disputes";
    case "guard_trusted_status":
      return options.guardId ? `/guard/profile?g=${encodeURIComponent(options.guardId)}` : "/guard/profile";
    case "client_trusted_status":
      return "/client/profile";
    case "job_relisted":
      return options.requestId ? `/client/requests?jc=${encodeURIComponent(options.requestId)}` : "/client/requests";
    case "job_schedule_changed":
      return options.requestId ? `/guard/my-jobs?jc=${encodeURIComponent(options.requestId)}` : "/guard/my-jobs";
    case "team_chat_message":
      return options.requestId ? `/staff/messages?mtab=team&jc=${encodeURIComponent(options.requestId)}` : "/staff/messages?mtab=team";
    case "test":
      return "/";
    default:
      return "/";
  }
}
function resolveNotificationUrlForRole(type, role, options = {}) {
  const isStaff = role === "moderator" || role === "administrator" || role === "director" || role === "owner";
  switch (type) {
    case "support_message":
      if (role === "client") {
        return options.ticketId ? `/client/support?st=${encodeURIComponent(options.ticketId)}` : "/client/support";
      }
      if (role === "guard") {
        return options.ticketId ? `/guard/support?st=${encodeURIComponent(options.ticketId)}` : "/guard/support";
      }
      return options.ticketId ? `/staff/support?st=${encodeURIComponent(options.ticketId)}` : "/staff/support";
    case "job_chat_message":
      if (role === "client") {
        return options.requestId ? `/client/map?jc=${encodeURIComponent(options.requestId)}&chat=1` : "/client/messages";
      }
      if (role === "guard") {
        return options.requestId ? `/guard/my-jobs?jc=${encodeURIComponent(options.requestId)}&chat=1` : "/guard/my-jobs";
      }
      return options.requestId ? `/staff/messages?mtab=jobs&jc=${encodeURIComponent(options.requestId)}` : "/staff/messages?mtab=jobs";
    case "emergency_alert":
      if (role === "client") {
        return options.requestId ? `/client/map?jc=${encodeURIComponent(options.requestId)}` : "/client/map";
      }
      if (role === "guard") {
        return options.requestId ? `/guard/my-jobs?jc=${encodeURIComponent(options.requestId)}` : "/guard/my-jobs";
      }
      if (options.requestId) {
        return `/staff/jobs?j=${encodeURIComponent(options.requestId)}`;
      }
      if (options.ticketId) {
        return `/staff/support?st=${encodeURIComponent(options.ticketId)}`;
      }
      return "/staff/incidents";
    case "missed_checkin":
    case "guard_checkin":
    case "guard_clockout":
    case "guard_break_start":
    case "guard_break_end":
      if (role === "guard") {
        return options.requestId ? `/guard/my-jobs?jc=${encodeURIComponent(options.requestId)}` : "/guard/my-jobs";
      }
      if (role === "client") {
        return options.requestId ? `/client/map?jc=${encodeURIComponent(options.requestId)}` : "/client/map";
      }
      return options.requestId ? `/staff/jobs?j=${encodeURIComponent(options.requestId)}` : "/staff/jobs";
    case "staff_message":
      return "/staff/messages?mtab=team";
    case "guard_message":
      return "/guard/guard-chat";
    case "support_ticket":
    case "support_ticket_status":
      if (role === "client") {
        return options.ticketId ? `/client/support?st=${encodeURIComponent(options.ticketId)}` : "/client/support";
      }
      if (role === "guard") {
        return options.ticketId ? `/guard/support?st=${encodeURIComponent(options.ticketId)}` : "/guard/support";
      }
      return options.ticketId ? `/staff/messages?mtab=support&st=${encodeURIComponent(options.ticketId)}` : "/staff/messages?mtab=support";
    case "dispute_update":
      if (role === "client") {
        return options.ticketId ? `/client/support?st=${encodeURIComponent(options.ticketId)}` : "/client/support";
      }
      if (role === "guard") {
        return options.ticketId ? `/guard/support?st=${encodeURIComponent(options.ticketId)}` : "/guard/support";
      }
      return options.ticketId ? `/staff/disputes?st=${encodeURIComponent(options.ticketId)}` : "/staff/disputes";
    case "assignment":
      if (role === "client") {
        return options.requestId ? `/client/requests?jc=${encodeURIComponent(options.requestId)}` : "/client/requests";
      }
      return options.requestId ? `/guard/my-jobs?jc=${encodeURIComponent(options.requestId)}` : "/guard/my-jobs";
    case "guard_trusted_status":
      return "/guard/profile";
    case "client_trusted_status":
      return "/client/profile";
    case "job_relisted":
      return options.requestId ? `/client/requests?jc=${encodeURIComponent(options.requestId)}` : "/client/requests";
    case "job_schedule_changed":
      return options.requestId ? `/guard/my-jobs?jc=${encodeURIComponent(options.requestId)}` : "/guard/my-jobs";
    case "team_chat_message":
      if (role === "guard") {
        return options.requestId ? `/guard/messages?jc=${encodeURIComponent(options.requestId)}` : "/guard/messages";
      }
      return options.requestId ? `/staff/messages?mtab=team&jc=${encodeURIComponent(options.requestId)}` : "/staff/messages?mtab=team";
    default:
      if (isStaff) return resolveNotificationUrl(type, options);
      if (role === "client") return "/client/home";
      if (role === "guard") return "/guard/map";
      return resolveNotificationUrl(type, options);
  }
}
function rolesForNotificationType(type) {
  switch (type) {
    case "missed_checkin":
    case "guard_checkin":
    case "guard_clockout":
    case "guard_break_start":
    case "guard_break_end":
      return ["dispatch", "admin"];
    case "assignment":
      return ["guard"];
    case "emergency_alert":
      return ["guard", "client", "dispatch", "admin"];
    case "support_message":
      return ["dispatch", "admin", "client", "guard"];
    case "job_chat_message":
      return ["client", "guard", "dispatch", "admin"];
    case "staff_message":
      return ["dispatch", "admin"];
    case "guard_message":
      return ["guard"];
    case "job_submitted":
    case "guard_application":
    case "guard_pending_approval":
    case "client_pending_approval":
    case "credential_pending":
    case "payment_attention":
      return ["dispatch", "admin"];
    case "support_ticket":
      return ["dispatch", "admin"];
    case "support_ticket_status":
      return ["client", "guard"];
    case "dispute_update":
      return ["dispatch", "admin", "client", "guard"];
    case "guard_trusted_status":
      return ["guard"];
    case "client_trusted_status":
      return ["client"];
    case "job_relisted":
      return ["client"];
    case "job_schedule_changed":
      return ["guard"];
    case "team_chat_message":
      return ["guard", "dispatch", "admin"];
    case "test":
      return [];
    default:
      return ["guard", "dispatch"];
  }
}
function buildNotificationData(type, options = {}) {
  const urlOptions = {
    guardId: options.guardId,
    requestId: options.requestId,
    ticketId: options.ticketId
  };
  const url = options.url ?? (options.role ? resolveNotificationUrlForRole(type, options.role, urlOptions) : resolveNotificationUrl(type, urlOptions));
  return {
    type,
    url,
    siteId: options.siteId,
    guardId: options.guardId,
    requestId: options.requestId,
    ticketId: options.ticketId,
    priority: options.priority ?? (type === "emergency_alert" ? "high" : "normal")
  };
}

// api/_push/delivery.ts
var PREF_COLUMN = {
  assignment: "assignment",
  guard_checkin: "guard_checkin",
  guard_clockout: "guard_clockout",
  guard_break_start: "guard_break_start",
  guard_break_end: "guard_break_end",
  missed_checkin: "missed_checkin",
  emergency_alert: "emergency_alert",
  support_message: "support_message",
  job_chat_message: "job_chat_message",
  staff_message: "staff_message",
  guard_message: "guard_message",
  job_submitted: "job_submitted",
  guard_application: "guard_application",
  guard_pending_approval: "guard_pending_approval",
  client_pending_approval: "client_pending_approval",
  credential_pending: "credential_pending",
  payment_attention: "payment_attention",
  support_ticket: "support_ticket",
  support_ticket_status: "support_ticket_status",
  dispute_update: "dispute_update",
  guard_trusted_status: "guard_trusted_status",
  client_trusted_status: "client_trusted_status",
  job_relisted: "job_relisted",
  job_schedule_changed: "assignment",
  team_chat_message: "team_chat_message"
};
async function isTypeEnabledForUser(db, userId, type) {
  const column = PREF_COLUMN[type];
  if (!column) return true;
  const { data, error } = await db.from("notification_preferences").select(column).eq("user_id", userId).maybeSingle();
  if (error || !data) return true;
  return data[column] !== false;
}
var MAX_RETRIES = 2;
var RETRY_DELAY_MS = 500;
var vapidConfigured = false;
var webPushModule = null;
async function getWebPush() {
  if (!webPushModule) {
    const mod = await import("web-push");
    webPushModule = "default" in mod && mod.default ? mod.default : mod;
  }
  return webPushModule;
}
async function ensureVapidConfigured() {
  const publicKey = process.env.VAPID_PUBLIC_KEY?.trim();
  const privateKey = process.env.VAPID_PRIVATE_KEY?.trim();
  const subject = process.env.VAPID_SUBJECT?.trim() || "mailto:support@guardr.co";
  if (!publicKey || !privateKey) return false;
  if (vapidConfigured) return true;
  const webpush = await getWebPush();
  webpush.setVapidDetails(subject, publicKey, privateKey);
  vapidConfigured = true;
  return true;
}
function isInQuietHours(quietStart, quietEnd, now = /* @__PURE__ */ new Date()) {
  if (!quietStart || !quietEnd) return false;
  const toMinutes = (time) => {
    const [h, m] = time.split(":").map(Number);
    return h * 60 + m;
  };
  const current = now.getHours() * 60 + now.getMinutes();
  const start = toMinutes(quietStart);
  const end = toMinutes(quietEnd);
  if (start === end) return false;
  if (start < end) return current >= start && current < end;
  return current >= start || current < end;
}
async function sleep(ms) {
  await new Promise((resolve) => setTimeout(resolve, ms));
}
async function sendToSubscription(subscription, payload, attempt = 0) {
  if (!await ensureVapidConfigured()) {
    return { ok: false, endpoint: subscription.endpoint };
  }
  try {
    const webpush = await getWebPush();
    await webpush.sendNotification(
      {
        endpoint: subscription.endpoint,
        keys: { p256dh: subscription.p256dh, auth: subscription.auth }
      },
      JSON.stringify(payload),
      {
        TTL: 60 * 60,
        urgency: payload.priority === "high" ? "high" : "normal"
      }
    );
    return { ok: true };
  } catch (err) {
    const statusCode = err && typeof err === "object" && "statusCode" in err ? Number(err.statusCode) : void 0;
    if (attempt < MAX_RETRIES && statusCode !== 404 && statusCode !== 410) {
      await sleep(RETRY_DELAY_MS * (attempt + 1));
      return sendToSubscription(subscription, payload, attempt + 1);
    }
    return { ok: false, statusCode, endpoint: subscription.endpoint };
  }
}
async function removeInvalidSubscriptions(db, endpoints) {
  if (!endpoints.length) return;
  await db.from("push_subscriptions").delete().in("endpoint", endpoints);
}
async function deliverToSubscriptions(db, subscriptions, payload) {
  if (!subscriptions.length) return { sent: 0, failed: 0 };
  if (!await ensureVapidConfigured()) return { sent: 0, failed: subscriptions.length };
  const prefCache = /* @__PURE__ */ new Map();
  const filtered = [];
  for (const sub of subscriptions) {
    if (payload.excludeUserId && sub.user_id === payload.excludeUserId) {
      continue;
    }
    if (!sub.user_id) {
      filtered.push(sub);
      continue;
    }
    let enabled = prefCache.get(sub.user_id);
    if (enabled === void 0) {
      enabled = await isTypeEnabledForUser(db, sub.user_id, payload.type);
      prefCache.set(sub.user_id, enabled);
    }
    if (enabled) filtered.push(sub);
  }
  if (!filtered.length) return { sent: 0, failed: 0 };
  const urlOptions = {
    guardId: payload.guardId,
    requestId: payload.requestId,
    ticketId: payload.ticketId
  };
  let sent = 0;
  let failed = 0;
  const staleEndpoints = [];
  for (const sub of filtered) {
    if (payload.type !== "emergency_alert" && payload.priority !== "high" && isInQuietHours(sub.quiet_hours_start, sub.quiet_hours_end)) {
      continue;
    }
    const platformRole = pushRoleToPlatformRole(sub.push_role);
    const data = buildNotificationData(payload.type, {
      url: payload.url ?? resolveNotificationUrlForRole(payload.type, platformRole, urlOptions),
      siteId: payload.siteId,
      guardId: payload.guardId,
      requestId: payload.requestId,
      ticketId: payload.ticketId,
      priority: payload.priority,
      role: platformRole
    });
    const message = {
      title: payload.title,
      body: payload.body,
      url: data.url,
      eventType: payload.type,
      data,
      tag: payload.siteId ? `${payload.type}-${payload.siteId}` : payload.type,
      priority: data.priority
    };
    const result = await sendToSubscription(sub, message);
    if (result.ok) {
      sent += 1;
    } else {
      failed += 1;
      if (result.statusCode === 404 || result.statusCode === 410) {
        staleEndpoints.push(result.endpoint);
      }
    }
  }
  await removeInvalidSubscriptions(db, staleEndpoints);
  return { sent, failed };
}
async function sendNotificationToUser(db, userId, payload) {
  const enabled = await isTypeEnabledForUser(db, userId, payload.type);
  if (!enabled) return { sent: 0, failed: 0 };
  const { data: subscriptions, error } = await db.from("push_subscriptions").select("endpoint, p256dh, auth, quiet_hours_start, quiet_hours_end, user_id, push_role").eq("user_id", userId);
  if (error) throw new Error(error.message);
  return deliverToSubscriptions(db, subscriptions ?? [], payload);
}
async function sendNotificationToRole(db, role, payload) {
  const roles = role === "dispatch" ? ["dispatch", "admin"] : [role];
  const { data: subscriptions, error } = await db.from("push_subscriptions").select("endpoint, p256dh, auth, quiet_hours_start, quiet_hours_end, user_id, push_role").in("push_role", roles);
  if (error) throw new Error(error.message);
  return deliverToSubscriptions(db, subscriptions ?? [], payload);
}
async function dispatchPushNotification(db, payload) {
  if (payload.userId) {
    return sendNotificationToUser(db, payload.userId, payload);
  }
  if (payload.role) {
    return sendNotificationToRole(db, payload.role, payload);
  }
  const roles = rolesForNotificationType(payload.type);
  let sent = 0;
  let failed = 0;
  for (const role of roles) {
    const result = await sendNotificationToRole(db, role, payload);
    sent += result.sent;
    failed += result.failed;
  }
  return { sent, failed };
}

// api/_push/sessionAuth.ts
function isInternalPushAuthorized(authHeader) {
  const secret = process.env.PUSH_INTERNAL_SECRET?.trim();
  if (!secret) return false;
  if (!authHeader?.startsWith("Bearer ")) return false;
  return authHeader.slice("Bearer ".length) === secret;
}

// api/_push/handlers.ts
function pushNotConfiguredResponse() {
  return { status: 503, body: { error: "Web Push is not configured. Set VAPID_PUBLIC_KEY and VAPID_PRIVATE_KEY." } };
}
async function handlePushSend(db, authHeader, body) {
  if (!isInternalPushAuthorized(authHeader)) {
    return { status: 401, body: { error: "Unauthorized \u2014 internal push secret required" } };
  }
  if (!body.title || !body.body || !body.type) {
    return { status: 400, body: { error: "title, body, and type are required" } };
  }
  if (!isPushConfigured()) {
    return pushNotConfiguredResponse();
  }
  const result = await dispatchPushNotification(db, body);
  return { status: 200, body: { ok: true, ...result } };
}

// api/_push/entries/send.ts
async function getSupabaseAdmin() {
  const url = process.env.SUPABASE_URL || process.env.NEXT_PUBLIC_SUPABASE_URL || process.env.VITE_SUPABASE_URL;
  const serviceKey = process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.SUPABASE_KEY;
  if (!url || !serviceKey) return null;
  const { createClient } = await import("@supabase/supabase-js");
  return createClient(url, serviceKey, {
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
async function handler(req, res) {
  if (req.method !== "POST") {
    return res.status(405).json({ error: "Method not allowed" });
  }
  try {
    const db = await getSupabaseAdmin();
    if (!db) {
      return res.status(503).json({ error: "Database is not configured" });
    }
    const authHeader = Array.isArray(req.headers.authorization) ? req.headers.authorization[0] : req.headers.authorization;
    const result = await handlePushSend(db, authHeader, req.body ?? {});
    return res.status(result.status).json(result.body);
  } catch (err) {
    const message = err instanceof Error ? err.message : "Push send failed";
    console.error("Push send error:", message, err);
    return res.status(500).json({ error: message });
  }
}
export {
  handler as default
};
