// Generated by scripts/bundle-push-handlers.mjs — do not edit.
// @ts-nocheck

// api/_push/apiCors.ts
var GUARDR_ORIGIN = /^https:\/\/([a-z0-9-]+\.)?guardr\.co$/i;
var CAPACITOR_ORIGIN = /^https:\/\/localhost(?::\d+)?$/i;
function isAllowedApiOrigin(origin) {
  return GUARDR_ORIGIN.test(origin) || CAPACITOR_ORIGIN.test(origin) || /^capacitor:\/\//i.test(origin);
}
function applyApiCors(req, res) {
  const origin = req.headers.origin;
  if (origin && isAllowedApiOrigin(origin)) {
    res.setHeader("Access-Control-Allow-Origin", origin);
    res.setHeader("Access-Control-Allow-Credentials", "true");
    res.setHeader("Vary", "Origin");
  }
  if (req.method === "OPTIONS") {
    res.setHeader("Access-Control-Allow-Methods", "GET, POST, PUT, PATCH, DELETE, OPTIONS");
    res.setHeader("Access-Control-Allow-Headers", "Content-Type, Authorization");
    res.status(204).end();
    return true;
  }
  return false;
}

// lib/push/fcm.ts
var FCM_NATIVE_ENDPOINT_PREFIX = "fcm-native:";
var FCM_NATIVE_KEY_PLACEHOLDER = "native-fcm";
function isFcmNativeEndpoint(endpoint) {
  return endpoint.startsWith(FCM_NATIVE_ENDPOINT_PREFIX);
}
function isFcmNativeSubscription(subscription) {
  if (!subscription.endpoint || !isFcmNativeEndpoint(subscription.endpoint)) return false;
  return subscription.keys?.p256dh === FCM_NATIVE_KEY_PLACEHOLDER && subscription.keys?.auth === FCM_NATIVE_KEY_PLACEHOLDER;
}
function isValidPushSubscriptionPayload(subscription) {
  if (!subscription.endpoint?.trim()) return false;
  if (isFcmNativeSubscription(subscription)) return true;
  const p256dh = subscription.keys?.p256dh?.trim();
  const auth = subscription.keys?.auth?.trim();
  if (!p256dh || !auth) return false;
  if (p256dh === FCM_NATIVE_KEY_PLACEHOLDER || auth === FCM_NATIVE_KEY_PLACEHOLDER) return false;
  return true;
}

// api/_push/dedup.ts
var DEDUP_TTL_MS = 25 * 60 * 60 * 1e3;

// api/_push/routing.ts
function platformRoleToPushRole(role) {
  switch (role) {
    case "guard":
      return "guard";
    case "moderator":
    case "administrator":
    case "director":
    case "owner":
      return "dispatch";
    case "client":
      return "client";
    default:
      return "guard";
  }
}

// api/_push/accountSessionAuth.ts
var STAFF_PLATFORM_ROLES = /* @__PURE__ */ new Set([
  "owner",
  "director",
  "administrator",
  "moderator",
  "staff",
  "auditor"
]);
function resolvePlatformRole(input) {
  if (input.legacyRole === "client") return "client";
  if (input.isStaff && input.staffRole) {
    switch (input.staffRole) {
      case "Founder":
      case "Owner":
        return "owner";
      case "Director":
        return "director";
      case "Administrator":
        return "administrator";
      case "Moderator":
        return "moderator";
    }
  }
  if (input.legacyRole === "auditor") return "moderator";
  if (input.legacyRole === "staff") return "administrator";
  return "guard";
}
async function verifyStaffSession(db, userId, email) {
  let { data, error } = await db.from("staff").select("id, email, staff_role").eq("id", userId).maybeSingle();
  if (!data && !error) {
    const byEmail = await db.from("staff").select("id, email, staff_role").eq("email", email).maybeSingle();
    data = byEmail.data ?? null;
    error = byEmail.error ?? null;
  }
  if (!data && error?.code === "42P01") return null;
  if (!data || data.email?.toLowerCase() !== email) return null;
  const platformRole = resolvePlatformRole({
    isStaff: true,
    staffRole: data.staff_role ?? void 0,
    legacyRole: "staff"
  });
  return { userId: data.id, email, role: platformRole, platformRole };
}
async function verifyFieldGuardSession(db, userId, email, credentialsRole) {
  let { data, error } = await db.from("guards").select("id, email, is_staff, staff_role, migrated_to_staff_at").eq("id", userId).maybeSingle();
  if (!data && !error) {
    const byEmail = await db.from("guards").select("id, email, is_staff, staff_role, migrated_to_staff_at").eq("email", email).maybeSingle();
    data = byEmail.data ?? null;
    error = byEmail.error ?? null;
  }
  if (!data && error?.code === "42P01") return null;
  if (!data || data.email?.toLowerCase() !== email) return null;
  if (data.migrated_to_staff_at) return null;
  const platformRole = resolvePlatformRole({
    isStaff: data.is_staff,
    staffRole: data.staff_role ?? void 0,
    legacyRole: data.is_staff ? "staff" : "guard"
  });
  if (platformRole !== credentialsRole && credentialsRole !== "staff" && credentialsRole !== "auditor") {
    console.warn(
      `Session role mismatch for ${email}: client sent ${credentialsRole}, db has ${platformRole}`
    );
  }
  return { userId: data.id, email, role: platformRole, platformRole };
}
async function verifyAccountSession(db, credentials) {
  if (!credentials?.userId || !credentials?.email || !credentials?.role) {
    return null;
  }
  const email = credentials.email.trim().toLowerCase();
  const { userId, role } = credentials;
  if (role === "client") {
    let { data } = await db.from("clients").select("id, email").eq("id", userId).maybeSingle();
    if (!data) {
      const byEmail = await db.from("clients").select("id, email").eq("email", email).maybeSingle();
      data = byEmail.data ?? null;
    }
    if (!data || data.email?.toLowerCase() !== email) return null;
    return { userId: data.id, email, role: "client", platformRole: "client" };
  }
  if (STAFF_PLATFORM_ROLES.has(role)) {
    const staffSession = await verifyStaffSession(db, userId, email);
    if (staffSession) return staffSession;
  }
  return verifyFieldGuardSession(db, userId, email, role);
}

// api/_push/sessionAuth.ts
async function verifySession(db, credentials) {
  return verifyAccountSession(db, credentials);
}

// api/_push/subscriptions.ts
function subscriptionId(userId, endpoint) {
  let hash = 0;
  for (let i = 0; i < endpoint.length; i += 1) {
    hash = (hash << 5) - hash + endpoint.charCodeAt(i);
    hash |= 0;
  }
  return `push-${userId}-${Math.abs(hash)}`;
}
async function upsertPushSubscription(db, params) {
  const { error } = await db.from("push_subscriptions").upsert(
    {
      id: subscriptionId(params.userId, params.subscription.endpoint),
      user_id: params.userId,
      push_role: params.pushRole,
      endpoint: params.subscription.endpoint,
      p256dh: params.subscription.keys.p256dh,
      auth: params.subscription.keys.auth,
      site_id: params.siteId ?? null,
      quiet_hours_start: params.quietHoursStart ?? null,
      quiet_hours_end: params.quietHoursEnd ?? null,
      updated_at: (/* @__PURE__ */ new Date()).toISOString()
    },
    { onConflict: "endpoint" }
  );
  if (error) {
    if (error.message.includes("push_subscriptions") || error.code === "42P01") {
      throw new Error(
        "push_subscriptions table is missing. Run supabase/complete_schema_setup.sql in the Supabase SQL Editor"
      );
    }
    throw new Error(error.message);
  }
}

// api/_push/handlers.ts
async function handlePushSubscribe(db, body) {
  const session = await verifySession(db, {
    userId: body.userId ?? "",
    email: body.email ?? "",
    role: body.role ?? ""
  });
  if (!session) {
    return { status: 401, body: { error: "Unauthorized \u2014 invalid session" } };
  }
  if (!isValidPushSubscriptionPayload(body.subscription ?? {})) {
    return { status: 400, body: { error: "Valid push subscription is required" } };
  }
  await upsertPushSubscription(db, {
    userId: session.userId,
    pushRole: platformRoleToPushRole(session.platformRole),
    subscription: body.subscription,
    siteId: body.siteId,
    quietHoursStart: body.quietHoursStart,
    quietHoursEnd: body.quietHoursEnd
  });
  return { status: 200, body: { ok: true } };
}

// api/_push/entries/subscribe.ts
async function getSupabaseAdmin() {
  const url = process.env.SUPABASE_URL || process.env.NEXT_PUBLIC_SUPABASE_URL || process.env.VITE_SUPABASE_URL;
  const serviceKey = process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.SUPABASE_KEY;
  if (!url || !serviceKey) return null;
  const { createClient } = await import("@supabase/supabase-js");
  return createClient(url, serviceKey, {
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function readBody(req) {
  const raw = req.body;
  if (!raw) return {};
  if (typeof raw === "string") {
    try {
      return JSON.parse(raw);
    } catch {
      return {};
    }
  }
  return raw;
}
async function handler(req, res) {
  if (applyApiCors(req, res)) return;
  if (req.method !== "POST") {
    return res.status(405).json({ error: "Method not allowed" });
  }
  try {
    const db = await getSupabaseAdmin();
    if (!db) {
      return res.status(503).json({
        error: "Database is not configured. Set SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY on the server."
      });
    }
    const result = await handlePushSubscribe(db, readBody(req));
    return res.status(result.status).json(result.body);
  } catch (err) {
    const message = err instanceof Error ? err.message : "Push subscribe failed";
    console.error("Push subscribe error:", message, err);
    return res.status(500).json({ error: message });
  }
}
export {
  handler as default
};
