// Generated by scripts/bundle-push-handlers.mjs — do not edit.
// @ts-nocheck

// api/_push/apiCors.ts
var GUARDR_ORIGIN = /^https:\/\/([a-z0-9-]+\.)?guardr\.co$/i;
var CAPACITOR_ORIGIN = /^https:\/\/localhost(?::\d+)?$/i;
function isAllowedApiOrigin(origin) {
  return GUARDR_ORIGIN.test(origin) || CAPACITOR_ORIGIN.test(origin) || /^capacitor:\/\//i.test(origin);
}
function applyApiCors(req, res) {
  const origin = req.headers.origin;
  if (origin && isAllowedApiOrigin(origin)) {
    res.setHeader("Access-Control-Allow-Origin", origin);
    res.setHeader("Access-Control-Allow-Credentials", "true");
    res.setHeader("Vary", "Origin");
  }
  if (req.method === "OPTIONS") {
    res.setHeader("Access-Control-Allow-Methods", "GET, POST, PUT, PATCH, DELETE, OPTIONS");
    res.setHeader("Access-Control-Allow-Headers", "Content-Type, Authorization");
    res.status(204).end();
    return true;
  }
  return false;
}

// lib/push/fcm.ts
import { createSign } from "node:crypto";
var FCM_NATIVE_ENDPOINT_PREFIX = "fcm-native:";
var cachedAccessToken = null;
function parseServiceAccountJson() {
  const raw = process.env.FCM_SERVICE_ACCOUNT_JSON?.trim();
  if (!raw) return null;
  try {
    const parsed = JSON.parse(raw);
    if (parsed.project_id && parsed.client_email && parsed.private_key) {
      return {
        project_id: parsed.project_id,
        client_email: parsed.client_email,
        private_key: parsed.private_key
      };
    }
  } catch {
  }
  return null;
}
function isFcmConfigured() {
  return !!process.env.FCM_SERVER_KEY?.trim() || !!parseServiceAccountJson();
}
function isFcmNativeEndpoint(endpoint) {
  return endpoint.startsWith(FCM_NATIVE_ENDPOINT_PREFIX);
}
function fcmTokenFromEndpoint(endpoint) {
  if (!isFcmNativeEndpoint(endpoint)) return null;
  const token = endpoint.slice(FCM_NATIVE_ENDPOINT_PREFIX.length).trim();
  return token || null;
}
function stringifyDataValue(value) {
  if (value == null) return "";
  if (typeof value === "string") return value;
  return JSON.stringify(value);
}
function buildDataPayload(payload) {
  const data = {};
  const nested = payload.data;
  if (nested && typeof nested === "object") {
    for (const [key, value] of Object.entries(nested)) {
      data[key] = stringifyDataValue(value);
    }
  }
  if (payload.url) data.url = stringifyDataValue(payload.url);
  if (payload.eventType) data.eventType = stringifyDataValue(payload.eventType);
  if (payload.priority) data.priority = stringifyDataValue(payload.priority);
  return data;
}
function base64UrlEncode(value) {
  return Buffer.from(value).toString("base64url");
}
async function getFcmAccessToken(serviceAccount) {
  const now = Date.now();
  if (cachedAccessToken && cachedAccessToken.expiresAt > now + 6e4) {
    return cachedAccessToken.token;
  }
  const issuedAt = Math.floor(now / 1e3);
  const header = base64UrlEncode(JSON.stringify({ alg: "RS256", typ: "JWT" }));
  const claim = base64UrlEncode(
    JSON.stringify({
      iss: serviceAccount.client_email,
      scope: "https://www.googleapis.com/auth/firebase.messaging",
      aud: "https://oauth2.googleapis.com/token",
      iat: issuedAt,
      exp: issuedAt + 3600
    })
  );
  const unsigned = `${header}.${claim}`;
  const sign = createSign("RSA-SHA256");
  sign.update(unsigned);
  const signature = sign.sign(serviceAccount.private_key, "base64url");
  const assertion = `${unsigned}.${signature}`;
  try {
    const res = await fetch("https://oauth2.googleapis.com/token", {
      method: "POST",
      headers: { "Content-Type": "application/x-www-form-urlencoded" },
      body: new URLSearchParams({
        grant_type: "urn:ietf:params:oauth:grant-type:jwt-bearer",
        assertion
      })
    });
    const body = await res.json().catch(() => ({}));
    if (!res.ok || !body.access_token) return null;
    cachedAccessToken = {
      token: body.access_token,
      expiresAt: now + (body.expires_in ?? 3600) * 1e3
    };
    return body.access_token;
  } catch {
    return null;
  }
}
async function sendFcmV1Notification(serviceAccount, endpoint, token, payload, attempt = 0) {
  const accessToken = await getFcmAccessToken(serviceAccount);
  if (!accessToken) return { ok: false, endpoint };
  const data = buildDataPayload(payload);
  try {
    const res = await fetch(
      `https://fcm.googleapis.com/v1/projects/${serviceAccount.project_id}/messages:send`,
      {
        method: "POST",
        headers: {
          Authorization: `Bearer ${accessToken}`,
          "Content-Type": "application/json"
        },
        body: JSON.stringify({
          message: {
            token,
            notification: {
              title: String(payload.title ?? "Guardr"),
              body: String(payload.body ?? "")
            },
            data,
            android: {
              priority: payload.priority === "high" ? "high" : "normal",
              notification: {
                channel_id: "guardr_alerts"
              }
            }
          }
        })
      }
    );
    if (res.ok) return { ok: true };
    const body = await res.json().catch(() => ({}));
    const errStatus = body.error?.status;
    if (errStatus === "NOT_FOUND" || errStatus === "UNREGISTERED" || errStatus === "INVALID_ARGUMENT") {
      return { ok: false, statusCode: 410, endpoint };
    }
    if (attempt < 2 && res.status >= 500) {
      await new Promise((resolve) => setTimeout(resolve, 500 * (attempt + 1)));
      return sendFcmV1Notification(serviceAccount, endpoint, token, payload, attempt + 1);
    }
    return { ok: false, statusCode: res.status, endpoint };
  } catch {
    if (attempt < 2) {
      await new Promise((resolve) => setTimeout(resolve, 500 * (attempt + 1)));
      return sendFcmV1Notification(serviceAccount, endpoint, token, payload, attempt + 1);
    }
    return { ok: false, endpoint };
  }
}
async function sendFcmLegacyNotification(endpoint, token, payload, serverKey, attempt = 0) {
  const data = buildDataPayload(payload);
  try {
    const res = await fetch("https://fcm.googleapis.com/fcm/send", {
      method: "POST",
      headers: {
        Authorization: `key=${serverKey}`,
        "Content-Type": "application/json"
      },
      body: JSON.stringify({
        to: token,
        notification: {
          title: String(payload.title ?? "Guardr"),
          body: String(payload.body ?? ""),
          android_channel_id: "guardr_alerts"
        },
        data,
        priority: payload.priority === "high" ? "high" : "normal"
      })
    });
    const body = await res.json().catch(() => ({}));
    if (res.ok && body.success === 1) return { ok: true };
    const errCode = body.results?.[0]?.error;
    if (errCode === "NotRegistered" || errCode === "InvalidRegistration") {
      return { ok: false, statusCode: 410, endpoint };
    }
    if (attempt < 2 && res.status >= 500) {
      await new Promise((resolve) => setTimeout(resolve, 500 * (attempt + 1)));
      return sendFcmLegacyNotification(endpoint, token, payload, serverKey, attempt + 1);
    }
    return { ok: false, statusCode: res.status, endpoint };
  } catch {
    if (attempt < 2) {
      await new Promise((resolve) => setTimeout(resolve, 500 * (attempt + 1)));
      return sendFcmLegacyNotification(endpoint, token, payload, serverKey, attempt + 1);
    }
    return { ok: false, endpoint };
  }
}
async function sendFcmNativeNotification(endpoint, payload, attempt = 0) {
  const token = fcmTokenFromEndpoint(endpoint);
  if (!token) return { ok: false, endpoint };
  const serviceAccount = parseServiceAccountJson();
  if (serviceAccount) {
    return sendFcmV1Notification(serviceAccount, endpoint, token, payload, attempt);
  }
  const serverKey = process.env.FCM_SERVER_KEY?.trim();
  if (!serverKey) return { ok: false, endpoint };
  return sendFcmLegacyNotification(endpoint, token, payload, serverKey, attempt);
}

// api/_push/config.ts
function isPushConfigured() {
  const vapidReady = !!(process.env.VAPID_PUBLIC_KEY?.trim() && process.env.VAPID_PRIVATE_KEY?.trim());
  return vapidReady || isFcmConfigured();
}

// api/_push/dedup.ts
var DEDUP_TTL_MS = 25 * 60 * 60 * 1e3;

// api/_push/routing.ts
function pushRoleToPlatformRole(pushRole) {
  switch (pushRole) {
    case "guard":
      return "guard";
    case "client":
      return "client";
    case "dispatch":
    case "admin":
      return "administrator";
    default:
      return "administrator";
  }
}
function resolveNotificationUrl(type, options = {}) {
  switch (type) {
    case "missed_checkin":
    case "guard_checkin":
    case "guard_clockout":
    case "guard_arrived":
    case "guard_en_route":
    case "guard_left_site":
    case "guard_break_start":
    case "guard_break_end":
      return options.requestId ? `/staff/jobs?j=${encodeURIComponent(options.requestId)}` : "/staff/jobs";
    case "job_open_to_guards":
      return options.requestId ? `/guard/map?jc=${encodeURIComponent(options.requestId)}` : "/guard/map";
    case "client_cash_payment_requested":
    case "guard_cash_payout_requested":
    case "stripe_payment_complete":
      return options.requestId ? `/staff/payments?j=${encodeURIComponent(options.requestId)}` : "/staff/payments";
    case "assignment":
      return options.requestId ? `/guard/my-jobs?jc=${encodeURIComponent(options.requestId)}` : "/guard/my-jobs";
    case "emergency_alert":
      if (options.requestId) {
        return `/staff/jobs?j=${encodeURIComponent(options.requestId)}`;
      }
      if (options.ticketId) {
        return `/staff/support?st=${encodeURIComponent(options.ticketId)}`;
      }
      return "/staff/incidents";
    case "support_message":
      return options.ticketId ? `/staff/support?st=${encodeURIComponent(options.ticketId)}` : "/staff/support";
    case "job_chat_message":
      return options.requestId ? `/staff/messages?mtab=jobs&jc=${encodeURIComponent(options.requestId)}` : "/staff/messages?mtab=jobs";
    case "staff_message":
      return "/staff/messages?mtab=team";
    case "guard_message":
      return "/guard/guard-chat";
    case "client_message":
      return "/client/messages";
    case "job_submitted":
      return options.requestId ? `/staff/jobs?j=${encodeURIComponent(options.requestId)}` : "/staff/jobs";
    case "guard_application":
      return options.requestId ? `/staff/jobs?j=${encodeURIComponent(options.requestId)}` : "/staff/jobs";
    case "crew_lead_request":
      return "/staff/jobs";
    case "guard_pending_approval":
      return options.guardId ? `/staff/applications?g=${encodeURIComponent(options.guardId)}` : "/staff/applications";
    case "client_pending_approval":
      return "/staff/applications";
    case "credential_pending":
      return options.guardId ? `/staff/credentials?g=${encodeURIComponent(options.guardId)}` : "/staff/credentials";
    case "payment_attention":
      return options.requestId ? `/staff/payments?j=${encodeURIComponent(options.requestId)}` : "/staff/payments";
    case "client_invoice_ready":
      return options.requestId ? `/client/invoices?inv=${encodeURIComponent(options.requestId)}` : "/client/invoices";
    case "support_ticket":
    case "support_ticket_status":
      return options.ticketId ? `/staff/messages?st=${encodeURIComponent(options.ticketId)}` : "/staff/messages";
    case "account_update":
      return "/staff/settings";
    case "job_status_update":
      return options.requestId ? `/staff/jobs?j=${encodeURIComponent(options.requestId)}` : "/staff/jobs";
    case "payout_ready":
      return "/guard/earnings";
    case "dispute_update":
      return options.ticketId ? `/staff/disputes?st=${encodeURIComponent(options.ticketId)}` : "/staff/disputes";
    case "guard_trusted_status":
      return options.guardId ? `/guard/profile?g=${encodeURIComponent(options.guardId)}` : "/guard/profile";
    case "client_trusted_status":
      return "/client/profile";
    case "job_relisted":
      return options.requestId ? `/client/requests?jc=${encodeURIComponent(options.requestId)}` : "/client/requests";
    case "job_schedule_changed":
      return options.requestId ? `/guard/my-jobs?jc=${encodeURIComponent(options.requestId)}` : "/guard/my-jobs";
    case "team_chat_message":
      return options.requestId ? `/staff/messages?jc=${encodeURIComponent(options.requestId)}` : "/staff/messages";
    case "standing_crew_invite":
      return "/guard/jobs";
    case "company_placard_expiry":
      return "/staff/settings";
    case "pre_shift_briefing":
      return options.requestId ? `/guard/map?jc=${encodeURIComponent(options.requestId)}` : "/guard/map";
    case "test":
      return "/";
    default:
      return "/";
  }
}
function resolveNotificationUrlForRole(type, role, options = {}) {
  const isStaff = role === "support" || role === "moderator" || role === "administrator" || role === "manager" || role === "director" || role === "owner";
  switch (type) {
    case "guard_arrived":
    case "guard_en_route":
    case "guard_left_site":
      if (role === "client") {
        return options.requestId ? `/client/map?jc=${encodeURIComponent(options.requestId)}` : "/client/map";
      }
      if (role === "guard") {
        return options.requestId ? `/guard/my-jobs?jc=${encodeURIComponent(options.requestId)}` : "/guard/my-jobs";
      }
      return options.requestId ? `/staff/jobs?j=${encodeURIComponent(options.requestId)}` : "/staff/jobs";
    case "job_open_to_guards":
      return options.requestId ? `/guard/map?jc=${encodeURIComponent(options.requestId)}` : "/guard/map";
    case "client_cash_payment_requested":
    case "guard_cash_payout_requested":
    case "stripe_payment_complete":
      if (role === "client") {
        return options.requestId ? `/client/requests?jc=${encodeURIComponent(options.requestId)}` : "/client/requests";
      }
      if (role === "guard") {
        return "/guard/earnings";
      }
      return options.requestId ? `/staff/payments?j=${encodeURIComponent(options.requestId)}` : "/staff/payments";
    case "payment_attention":
      if (role === "client") {
        return options.requestId ? `/client/requests?jc=${encodeURIComponent(options.requestId)}` : "/client/requests";
      }
      if (role === "guard") {
        return "/guard/earnings";
      }
      return options.requestId ? `/staff/payments?j=${encodeURIComponent(options.requestId)}` : "/staff/payments";
    case "support_message":
      if (role === "client") {
        return options.ticketId ? `/client/support?st=${encodeURIComponent(options.ticketId)}` : "/client/support";
      }
      if (role === "guard") {
        return options.ticketId ? `/guard/support?st=${encodeURIComponent(options.ticketId)}` : "/guard/support";
      }
      return options.ticketId ? `/staff/support?st=${encodeURIComponent(options.ticketId)}` : "/staff/support";
    case "job_chat_message":
      if (role === "client") {
        return options.requestId ? `/client/map?jc=${encodeURIComponent(options.requestId)}&chat=1` : "/client/messages";
      }
      if (role === "guard") {
        return options.requestId ? `/guard/my-jobs?jc=${encodeURIComponent(options.requestId)}&chat=1` : "/guard/my-jobs";
      }
      return options.requestId ? `/staff/messages?mtab=jobs&jc=${encodeURIComponent(options.requestId)}` : "/staff/messages?mtab=jobs";
    case "emergency_alert":
      if (role === "client") {
        return options.requestId ? `/client/map?jc=${encodeURIComponent(options.requestId)}` : "/client/map";
      }
      if (role === "guard") {
        return options.requestId ? `/guard/my-jobs?jc=${encodeURIComponent(options.requestId)}` : "/guard/my-jobs";
      }
      if (options.requestId) {
        return `/staff/jobs?j=${encodeURIComponent(options.requestId)}`;
      }
      if (options.ticketId) {
        return `/staff/support?st=${encodeURIComponent(options.ticketId)}`;
      }
      return "/staff/incidents";
    case "missed_checkin":
    case "guard_checkin":
    case "guard_clockout":
    case "guard_break_start":
    case "guard_break_end":
      if (role === "guard") {
        return options.requestId ? `/guard/my-jobs?jc=${encodeURIComponent(options.requestId)}` : "/guard/my-jobs";
      }
      if (role === "client") {
        return options.requestId ? `/client/map?jc=${encodeURIComponent(options.requestId)}` : "/client/map";
      }
      return options.requestId ? `/staff/jobs?j=${encodeURIComponent(options.requestId)}` : "/staff/jobs";
    case "staff_message":
      return "/staff/messages?mtab=team";
    case "guard_message":
      return "/guard/guard-chat";
    case "client_message":
      if (role === "client") return "/client/messages";
      return "/staff/messages?mtab=team";
    case "support_ticket":
    case "support_ticket_status":
      if (role === "client" && options.requestId) {
        return `/client/requests?jc=${encodeURIComponent(options.requestId)}`;
      }
      if (role === "client") {
        return options.ticketId ? `/client/messages?st=${encodeURIComponent(options.ticketId)}` : "/client/messages";
      }
      if (role === "guard") {
        return options.ticketId ? `/guard/messages?st=${encodeURIComponent(options.ticketId)}` : "/guard/messages";
      }
      return options.ticketId ? `/staff/messages?st=${encodeURIComponent(options.ticketId)}` : "/staff/messages";
    case "account_update":
      if (role === "client") return "/client/settings";
      if (role === "guard") return "/guard/settings";
      return "/staff/settings";
    case "job_status_update":
      if (role === "client") {
        return options.requestId ? `/client/requests?jc=${encodeURIComponent(options.requestId)}` : "/client/requests";
      }
      if (role === "guard") {
        return options.requestId ? `/guard/my-jobs?jc=${encodeURIComponent(options.requestId)}` : "/guard/my-jobs";
      }
      return options.requestId ? `/staff/jobs?j=${encodeURIComponent(options.requestId)}` : "/staff/jobs";
    case "client_invoice_ready":
      return options.requestId ? `/client/invoices?inv=${encodeURIComponent(options.requestId)}` : "/client/invoices";
    case "payout_ready":
      return role === "guard" ? "/guard/earnings" : "/staff/payments";
    case "dispute_update":
      if (role === "client") {
        return options.ticketId ? `/client/support?st=${encodeURIComponent(options.ticketId)}` : "/client/support";
      }
      if (role === "guard") {
        return options.ticketId ? `/guard/support?st=${encodeURIComponent(options.ticketId)}` : "/guard/support";
      }
      return options.ticketId ? `/staff/disputes?st=${encodeURIComponent(options.ticketId)}` : "/staff/disputes";
    case "assignment":
    case "guard_application":
      if (role === "client") {
        return options.requestId ? `/client/requests?jc=${encodeURIComponent(options.requestId)}` : "/client/requests";
      }
      if (type === "guard_application") {
        return options.requestId ? `/staff/jobs?j=${encodeURIComponent(options.requestId)}` : "/staff/jobs";
      }
      return options.requestId ? `/guard/my-jobs?jc=${encodeURIComponent(options.requestId)}` : "/guard/my-jobs";
    case "guard_trusted_status":
      return "/guard/profile";
    case "client_trusted_status":
      return "/client/profile";
    case "job_relisted":
      return options.requestId ? `/client/requests?jc=${encodeURIComponent(options.requestId)}` : "/client/requests";
    case "job_schedule_changed":
      return options.requestId ? `/guard/my-jobs?jc=${encodeURIComponent(options.requestId)}` : "/guard/my-jobs";
    case "pre_shift_briefing":
      return options.requestId ? `/guard/map?jc=${encodeURIComponent(options.requestId)}` : "/guard/map";
    case "team_chat_message":
      if (role === "guard") {
        return options.requestId ? `/guard/messages?jc=${encodeURIComponent(options.requestId)}` : "/guard/messages";
      }
      return options.requestId ? `/staff/messages?jc=${encodeURIComponent(options.requestId)}` : "/staff/messages";
    case "standing_crew_invite":
      return "/guard/jobs";
    default:
      if (isStaff) return resolveNotificationUrl(type, options);
      if (role === "client") return "/client/home";
      if (role === "guard") return "/guard/map";
      return resolveNotificationUrl(type, options);
  }
}
function rolesForNotificationType(type) {
  switch (type) {
    case "missed_checkin":
    case "guard_checkin":
    case "guard_clockout":
    case "guard_arrived":
    case "guard_en_route":
    case "guard_left_site":
    case "guard_break_start":
    case "guard_break_end":
      return ["dispatch", "admin"];
    case "job_open_to_guards":
      return ["guard"];
    case "client_cash_payment_requested":
    case "guard_cash_payout_requested":
    case "stripe_payment_complete":
      return ["dispatch", "admin"];
    case "assignment":
      return ["guard"];
    case "guard_application":
      return ["dispatch", "admin"];
    case "crew_lead_request":
      return ["dispatch", "admin"];
    case "emergency_alert":
      return ["guard", "client", "dispatch", "admin"];
    case "support_message":
      return ["dispatch", "admin", "client", "guard"];
    case "job_chat_message":
      return ["client", "guard", "dispatch", "admin"];
    case "staff_message":
      return ["dispatch", "admin"];
    case "guard_message":
      return ["guard"];
    case "client_message":
      return ["client"];
    case "job_submitted":
    case "guard_pending_approval":
    case "client_pending_approval":
    case "credential_pending":
    case "payment_attention":
      return ["dispatch", "admin"];
    case "client_invoice_ready":
      return ["client"];
    case "support_ticket":
      return ["dispatch", "admin"];
    case "support_ticket_status":
      return ["client", "guard"];
    case "dispute_update":
      return ["dispatch", "admin", "client", "guard"];
    case "guard_trusted_status":
      return ["guard"];
    case "client_trusted_status":
      return ["client"];
    case "job_relisted":
      return ["client"];
    case "job_schedule_changed":
      return ["guard"];
    case "pre_shift_briefing":
      return ["guard"];
    case "team_chat_message":
      return ["guard", "dispatch", "admin"];
    case "standing_crew_invite":
      return ["guard"];
    case "company_placard_expiry":
      return ["dispatch", "admin"];
    case "account_update":
      return ["guard", "client", "dispatch", "admin"];
    case "test":
      return [];
    default:
      return ["guard", "dispatch"];
  }
}
function buildNotificationData(type, options = {}) {
  const urlOptions = {
    guardId: options.guardId,
    requestId: options.requestId,
    ticketId: options.ticketId
  };
  const url = options.url ?? (options.role ? resolveNotificationUrlForRole(type, options.role, urlOptions) : resolveNotificationUrl(type, urlOptions));
  return {
    type,
    url,
    siteId: options.siteId,
    guardId: options.guardId,
    requestId: options.requestId,
    ticketId: options.ticketId,
    priority: options.priority ?? (type === "emergency_alert" ? "high" : "normal")
  };
}

// api/_push/delivery.ts
var PREF_COLUMN = {
  assignment: "assignment",
  guard_checkin: "guard_checkin",
  guard_clockout: "guard_clockout",
  guard_arrived: "guard_arrived",
  guard_left_site: "guard_left_site",
  guard_break_start: "guard_break_start",
  guard_break_end: "guard_break_end",
  missed_checkin: "missed_checkin",
  emergency_alert: "emergency_alert",
  support_message: "support_message",
  job_chat_message: "job_chat_message",
  staff_message: "staff_message",
  guard_message: "guard_message",
  client_message: "client_message",
  job_submitted: "job_submitted",
  job_open_to_guards: "job_open_to_guards",
  guard_application: "guard_application",
  guard_pending_approval: "guard_pending_approval",
  client_pending_approval: "client_pending_approval",
  credential_pending: "credential_pending",
  payment_attention: "payment_attention",
  client_invoice_ready: "client_invoice_ready",
  client_cash_payment_requested: "payment_attention",
  guard_cash_payout_requested: "payment_attention",
  stripe_payment_complete: "payment_attention",
  support_ticket: "support_ticket",
  support_ticket_status: "support_ticket_status",
  dispute_update: "dispute_update",
  guard_trusted_status: "guard_trusted_status",
  client_trusted_status: "client_trusted_status",
  job_relisted: "job_relisted",
  job_schedule_changed: "job_schedule_changed",
  team_chat_message: "team_chat_message",
  standing_crew_invite: "standing_crew_invite",
  crew_lead_request: "crew_lead_request",
  pre_shift_briefing: "pre_shift_briefing",
  guard_en_route: "guard_arrived",
  account_update: "support_ticket_status",
  job_status_update: "assignment",
  payout_ready: "assignment",
  company_placard_expiry: "company_placard_expiry"
};
async function isTypeEnabledForUser(db, userId, type) {
  const column = PREF_COLUMN[type];
  if (!column) return true;
  const { data, error } = await db.from("notification_preferences").select(column).eq("user_id", userId).maybeSingle();
  if (error || !data) return true;
  return data[column] !== false;
}
var MAX_RETRIES = 2;
var RETRY_DELAY_MS = 500;
var vapidConfigured = false;
var webPushModule = null;
async function getWebPush() {
  if (!webPushModule) {
    const mod = await import("web-push");
    webPushModule = "default" in mod && mod.default ? mod.default : mod;
  }
  return webPushModule;
}
async function ensureVapidConfigured() {
  const publicKey = process.env.VAPID_PUBLIC_KEY?.trim();
  const privateKey = process.env.VAPID_PRIVATE_KEY?.trim();
  const subject = process.env.VAPID_SUBJECT?.trim() || "mailto:support@guardr.co";
  if (!publicKey || !privateKey) return false;
  if (vapidConfigured) return true;
  const webpush = await getWebPush();
  webpush.setVapidDetails(subject, publicKey, privateKey);
  vapidConfigured = true;
  return true;
}
function isInQuietHours(quietStart, quietEnd, now = /* @__PURE__ */ new Date()) {
  if (!quietStart || !quietEnd) return false;
  const toMinutes = (time) => {
    const [h, m] = time.split(":").map(Number);
    return h * 60 + m;
  };
  const current = now.getHours() * 60 + now.getMinutes();
  const start = toMinutes(quietStart);
  const end = toMinutes(quietEnd);
  if (start === end) return false;
  if (start < end) return current >= start && current < end;
  return current >= start || current < end;
}
async function sleep(ms) {
  await new Promise((resolve) => setTimeout(resolve, ms));
}
async function sendToSubscription(subscription, payload, attempt = 0) {
  if (isFcmNativeEndpoint(subscription.endpoint)) {
    return sendFcmNativeNotification(subscription.endpoint, payload, attempt);
  }
  if (!await ensureVapidConfigured()) {
    return { ok: false, endpoint: subscription.endpoint };
  }
  try {
    const webpush = await getWebPush();
    await webpush.sendNotification(
      {
        endpoint: subscription.endpoint,
        keys: { p256dh: subscription.p256dh, auth: subscription.auth }
      },
      JSON.stringify(payload),
      {
        TTL: 60 * 60,
        urgency: payload.priority === "high" ? "high" : "normal"
      }
    );
    return { ok: true };
  } catch (err) {
    const statusCode = err && typeof err === "object" && "statusCode" in err ? Number(err.statusCode) : void 0;
    if (attempt < MAX_RETRIES && statusCode !== 404 && statusCode !== 410) {
      await sleep(RETRY_DELAY_MS * (attempt + 1));
      return sendToSubscription(subscription, payload, attempt + 1);
    }
    return { ok: false, statusCode, endpoint: subscription.endpoint };
  }
}
async function removeInvalidSubscriptions(db, endpoints) {
  if (!endpoints.length) return;
  await db.from("push_subscriptions").delete().in("endpoint", endpoints);
}
async function deliverToSubscriptions(db, subscriptions, payload) {
  if (!subscriptions.length) return { sent: 0, failed: 0 };
  const webPushReady = await ensureVapidConfigured();
  const fcmReady = isFcmConfigured();
  if (!webPushReady && !fcmReady) return { sent: 0, failed: subscriptions.length };
  const prefCache = /* @__PURE__ */ new Map();
  const filtered = [];
  for (const sub of subscriptions) {
    if (payload.excludeUserId && sub.user_id === payload.excludeUserId) {
      continue;
    }
    if (!sub.user_id) {
      filtered.push(sub);
      continue;
    }
    let enabled = prefCache.get(sub.user_id);
    if (enabled === void 0) {
      enabled = await isTypeEnabledForUser(db, sub.user_id, payload.type);
      prefCache.set(sub.user_id, enabled);
    }
    if (enabled) filtered.push(sub);
  }
  if (!filtered.length) return { sent: 0, failed: 0 };
  const urlOptions = {
    guardId: payload.guardId,
    requestId: payload.requestId,
    ticketId: payload.ticketId
  };
  let sent = 0;
  let failed = 0;
  const staleEndpoints = [];
  for (const sub of filtered) {
    if (payload.type !== "emergency_alert" && payload.priority !== "high" && isInQuietHours(sub.quiet_hours_start, sub.quiet_hours_end)) {
      continue;
    }
    const platformRole = pushRoleToPlatformRole(sub.push_role);
    const data = buildNotificationData(payload.type, {
      url: payload.url ?? resolveNotificationUrlForRole(payload.type, platformRole, urlOptions),
      siteId: payload.siteId,
      guardId: payload.guardId,
      requestId: payload.requestId,
      ticketId: payload.ticketId,
      priority: payload.priority,
      role: platformRole
    });
    const message = {
      title: payload.title,
      body: payload.body,
      url: data.url,
      eventType: payload.type,
      data,
      tag: payload.siteId ? `${payload.type}-${payload.siteId}` : payload.type,
      priority: data.priority
    };
    const result = await sendToSubscription(sub, message);
    if (result.ok) {
      sent += 1;
    } else {
      failed += 1;
      if (result.statusCode === 404 || result.statusCode === 410) {
        staleEndpoints.push(result.endpoint);
      }
    }
  }
  await removeInvalidSubscriptions(db, staleEndpoints);
  return { sent, failed };
}
async function sendNotificationToUser(db, userId, payload) {
  const enabled = await isTypeEnabledForUser(db, userId, payload.type);
  if (!enabled) return { sent: 0, failed: 0 };
  const { data: subscriptions, error } = await db.from("push_subscriptions").select("endpoint, p256dh, auth, quiet_hours_start, quiet_hours_end, user_id, push_role").eq("user_id", userId);
  if (error) throw new Error(error.message);
  return deliverToSubscriptions(db, subscriptions ?? [], payload);
}
async function sendNotificationToRole(db, role, payload) {
  const roles = role === "dispatch" ? ["dispatch", "admin"] : [role];
  const { data: subscriptions, error } = await db.from("push_subscriptions").select("endpoint, p256dh, auth, quiet_hours_start, quiet_hours_end, user_id, push_role").in("push_role", roles);
  if (error) throw new Error(error.message);
  return deliverToSubscriptions(db, subscriptions ?? [], payload);
}
async function dispatchPushNotification(db, payload) {
  if (payload.userId) {
    return sendNotificationToUser(db, payload.userId, payload);
  }
  if (payload.role) {
    return sendNotificationToRole(db, payload.role, payload);
  }
  const roles = rolesForNotificationType(payload.type);
  let sent = 0;
  let failed = 0;
  for (const role of roles) {
    const result = await sendNotificationToRole(db, role, payload);
    sent += result.sent;
    failed += result.failed;
  }
  return { sent, failed };
}

// api/_push/accountSessionAuth.ts
var STAFF_PLATFORM_ROLES = /* @__PURE__ */ new Set([
  "owner",
  "director",
  "manager",
  "administrator",
  "moderator",
  "support",
  "staff",
  "auditor"
]);
function resolvePlatformRole(input) {
  if (input.legacyRole === "client") return "client";
  if (input.isStaff && input.staffRole) {
    switch (input.staffRole) {
      case "Founder":
      case "Owner":
        return "owner";
      case "Director":
        return "director";
      case "Manager":
        return "manager";
      case "Administrator":
        return "administrator";
      case "Moderator":
        return "moderator";
      case "Support":
        return "support";
    }
  }
  if (input.legacyRole === "auditor") return "moderator";
  if (input.legacyRole === "staff") return "administrator";
  return "guard";
}
async function verifyStaffSession(db, userId, email) {
  const emailLower = email.trim().toLowerCase();
  let { data, error } = await db.from("staff").select("id, email, personal_email, staff_role").eq("id", userId).maybeSingle();
  if (!data && !error) {
    const byEmail = await db.from("staff").select("id, email, personal_email, staff_role").or(`email.eq.${emailLower},personal_email.eq.${emailLower}`).maybeSingle();
    data = byEmail.data ?? null;
    error = byEmail.error ?? null;
  }
  if (!data && error?.code === "42P01") return null;
  const matchesWork = data?.email?.toLowerCase() === emailLower;
  const matchesPersonal = data?.personal_email?.toLowerCase() === emailLower;
  if (!data || !matchesWork && !matchesPersonal) return null;
  const platformRole = resolvePlatformRole({
    isStaff: true,
    staffRole: data.staff_role ?? void 0,
    legacyRole: "staff"
  });
  return { userId: data.id, email: emailLower, role: platformRole, platformRole };
}
async function verifyFieldGuardSession(db, userId, email, credentialsRole) {
  let { data, error } = await db.from("guards").select("id, email, is_staff, staff_role, migrated_to_staff_at").eq("id", userId).maybeSingle();
  if (!data && !error) {
    const byEmail = await db.from("guards").select("id, email, is_staff, staff_role, migrated_to_staff_at").eq("email", email).maybeSingle();
    data = byEmail.data ?? null;
    error = byEmail.error ?? null;
  }
  if (!data && error?.code === "42P01") return null;
  if (!data || data.email?.toLowerCase() !== email) return null;
  if (data.migrated_to_staff_at) return null;
  const platformRole = resolvePlatformRole({
    isStaff: data.is_staff,
    staffRole: data.staff_role ?? void 0,
    legacyRole: data.is_staff ? "staff" : "guard"
  });
  if (platformRole !== credentialsRole && credentialsRole !== "staff" && credentialsRole !== "auditor") {
    console.warn(
      `Session role mismatch for ${email}: client sent ${credentialsRole}, db has ${platformRole}`
    );
  }
  return { userId: data.id, email, role: platformRole, platformRole };
}
async function verifyAccountSession(db, credentials) {
  if (!credentials?.userId || !credentials?.email || !credentials?.role) {
    return null;
  }
  const email = credentials.email.trim().toLowerCase();
  const { userId, role } = credentials;
  if (role === "client") {
    let { data } = await db.from("clients").select("id, email").eq("id", userId).maybeSingle();
    if (!data) {
      const byEmail = await db.from("clients").select("id, email").eq("email", email).maybeSingle();
      data = byEmail.data ?? null;
    }
    if (!data || data.email?.toLowerCase() !== email) return null;
    return { userId: data.id, email, role: "client", platformRole: "client" };
  }
  if (STAFF_PLATFORM_ROLES.has(role)) {
    const staffSession = await verifyStaffSession(db, userId, email);
    if (staffSession) return staffSession;
  }
  return verifyFieldGuardSession(db, userId, email, role);
}

// api/_push/sessionAuth.ts
async function verifySession(db, credentials) {
  return verifyAccountSession(db, credentials);
}

// lib/push/routing.ts
function pushRoleToPlatformRole2(pushRole) {
  switch (pushRole) {
    case "guard":
      return "guard";
    case "client":
      return "client";
    case "dispatch":
    case "admin":
      return "administrator";
    default:
      return "administrator";
  }
}
function resolveNotificationUrl2(type, options = {}) {
  switch (type) {
    case "missed_checkin":
    case "guard_checkin":
    case "guard_clockout":
    case "guard_arrived":
    case "guard_en_route":
    case "guard_left_site":
    case "guard_break_start":
    case "guard_break_end":
      return options.requestId ? `/staff/jobs?j=${encodeURIComponent(options.requestId)}` : "/staff/jobs";
    case "job_open_to_guards":
      return options.requestId ? `/guard/map?jc=${encodeURIComponent(options.requestId)}` : "/guard/map";
    case "client_cash_payment_requested":
    case "guard_cash_payout_requested":
    case "stripe_payment_complete":
      return options.requestId ? `/staff/payments?j=${encodeURIComponent(options.requestId)}` : "/staff/payments";
    case "assignment":
      return options.requestId ? `/guard/my-jobs?jc=${encodeURIComponent(options.requestId)}` : "/guard/my-jobs";
    case "emergency_alert":
      if (options.requestId) {
        return `/staff/jobs?j=${encodeURIComponent(options.requestId)}`;
      }
      if (options.ticketId) {
        return `/staff/support?st=${encodeURIComponent(options.ticketId)}`;
      }
      return "/staff/incidents";
    case "support_message":
      return options.ticketId ? `/staff/support?st=${encodeURIComponent(options.ticketId)}` : "/staff/support";
    case "job_chat_message":
      return options.requestId ? `/staff/messages?mtab=jobs&jc=${encodeURIComponent(options.requestId)}` : "/staff/messages?mtab=jobs";
    case "staff_message":
      return "/staff/messages?mtab=team";
    case "guard_message":
      return "/guard/guard-chat";
    case "client_message":
      return "/client/messages";
    case "job_submitted":
      return options.requestId ? `/staff/jobs?j=${encodeURIComponent(options.requestId)}` : "/staff/jobs";
    case "guard_application":
      return options.requestId ? `/staff/jobs?j=${encodeURIComponent(options.requestId)}` : "/staff/jobs";
    case "crew_lead_request":
      return "/staff/jobs";
    case "guard_pending_approval":
      return options.guardId ? `/staff/applications?g=${encodeURIComponent(options.guardId)}` : "/staff/applications";
    case "client_pending_approval":
      return "/staff/applications";
    case "credential_pending":
      return options.guardId ? `/staff/credentials?g=${encodeURIComponent(options.guardId)}` : "/staff/credentials";
    case "payment_attention":
      return options.requestId ? `/staff/payments?j=${encodeURIComponent(options.requestId)}` : "/staff/payments";
    case "client_invoice_ready":
      return options.requestId ? `/client/invoices?inv=${encodeURIComponent(options.requestId)}` : "/client/invoices";
    case "support_ticket":
    case "support_ticket_status":
      return options.ticketId ? `/staff/messages?st=${encodeURIComponent(options.ticketId)}` : "/staff/messages";
    case "account_update":
      return "/staff/settings";
    case "job_status_update":
      return options.requestId ? `/staff/jobs?j=${encodeURIComponent(options.requestId)}` : "/staff/jobs";
    case "payout_ready":
      return "/guard/earnings";
    case "dispute_update":
      return options.ticketId ? `/staff/disputes?st=${encodeURIComponent(options.ticketId)}` : "/staff/disputes";
    case "guard_trusted_status":
      return options.guardId ? `/guard/profile?g=${encodeURIComponent(options.guardId)}` : "/guard/profile";
    case "client_trusted_status":
      return "/client/profile";
    case "job_relisted":
      return options.requestId ? `/client/requests?jc=${encodeURIComponent(options.requestId)}` : "/client/requests";
    case "job_schedule_changed":
      return options.requestId ? `/guard/my-jobs?jc=${encodeURIComponent(options.requestId)}` : "/guard/my-jobs";
    case "team_chat_message":
      return options.requestId ? `/staff/messages?jc=${encodeURIComponent(options.requestId)}` : "/staff/messages";
    case "standing_crew_invite":
      return "/guard/jobs";
    case "company_placard_expiry":
      return "/staff/settings";
    case "pre_shift_briefing":
      return options.requestId ? `/guard/map?jc=${encodeURIComponent(options.requestId)}` : "/guard/map";
    case "test":
      return "/";
    default:
      return "/";
  }
}
function resolveNotificationUrlForRole2(type, role, options = {}) {
  const isStaff = role === "support" || role === "moderator" || role === "administrator" || role === "manager" || role === "director" || role === "owner";
  switch (type) {
    case "guard_arrived":
    case "guard_en_route":
    case "guard_left_site":
      if (role === "client") {
        return options.requestId ? `/client/map?jc=${encodeURIComponent(options.requestId)}` : "/client/map";
      }
      if (role === "guard") {
        return options.requestId ? `/guard/my-jobs?jc=${encodeURIComponent(options.requestId)}` : "/guard/my-jobs";
      }
      return options.requestId ? `/staff/jobs?j=${encodeURIComponent(options.requestId)}` : "/staff/jobs";
    case "job_open_to_guards":
      return options.requestId ? `/guard/map?jc=${encodeURIComponent(options.requestId)}` : "/guard/map";
    case "client_cash_payment_requested":
    case "guard_cash_payout_requested":
    case "stripe_payment_complete":
      if (role === "client") {
        return options.requestId ? `/client/requests?jc=${encodeURIComponent(options.requestId)}` : "/client/requests";
      }
      if (role === "guard") {
        return "/guard/earnings";
      }
      return options.requestId ? `/staff/payments?j=${encodeURIComponent(options.requestId)}` : "/staff/payments";
    case "payment_attention":
      if (role === "client") {
        return options.requestId ? `/client/requests?jc=${encodeURIComponent(options.requestId)}` : "/client/requests";
      }
      if (role === "guard") {
        return "/guard/earnings";
      }
      return options.requestId ? `/staff/payments?j=${encodeURIComponent(options.requestId)}` : "/staff/payments";
    case "support_message":
      if (role === "client") {
        return options.ticketId ? `/client/support?st=${encodeURIComponent(options.ticketId)}` : "/client/support";
      }
      if (role === "guard") {
        return options.ticketId ? `/guard/support?st=${encodeURIComponent(options.ticketId)}` : "/guard/support";
      }
      return options.ticketId ? `/staff/support?st=${encodeURIComponent(options.ticketId)}` : "/staff/support";
    case "job_chat_message":
      if (role === "client") {
        return options.requestId ? `/client/map?jc=${encodeURIComponent(options.requestId)}&chat=1` : "/client/messages";
      }
      if (role === "guard") {
        return options.requestId ? `/guard/my-jobs?jc=${encodeURIComponent(options.requestId)}&chat=1` : "/guard/my-jobs";
      }
      return options.requestId ? `/staff/messages?mtab=jobs&jc=${encodeURIComponent(options.requestId)}` : "/staff/messages?mtab=jobs";
    case "emergency_alert":
      if (role === "client") {
        return options.requestId ? `/client/map?jc=${encodeURIComponent(options.requestId)}` : "/client/map";
      }
      if (role === "guard") {
        return options.requestId ? `/guard/my-jobs?jc=${encodeURIComponent(options.requestId)}` : "/guard/my-jobs";
      }
      if (options.requestId) {
        return `/staff/jobs?j=${encodeURIComponent(options.requestId)}`;
      }
      if (options.ticketId) {
        return `/staff/support?st=${encodeURIComponent(options.ticketId)}`;
      }
      return "/staff/incidents";
    case "missed_checkin":
    case "guard_checkin":
    case "guard_clockout":
    case "guard_break_start":
    case "guard_break_end":
      if (role === "guard") {
        return options.requestId ? `/guard/my-jobs?jc=${encodeURIComponent(options.requestId)}` : "/guard/my-jobs";
      }
      if (role === "client") {
        return options.requestId ? `/client/map?jc=${encodeURIComponent(options.requestId)}` : "/client/map";
      }
      return options.requestId ? `/staff/jobs?j=${encodeURIComponent(options.requestId)}` : "/staff/jobs";
    case "staff_message":
      return "/staff/messages?mtab=team";
    case "guard_message":
      return "/guard/guard-chat";
    case "client_message":
      if (role === "client") return "/client/messages";
      return "/staff/messages?mtab=team";
    case "support_ticket":
    case "support_ticket_status":
      if (role === "client" && options.requestId) {
        return `/client/requests?jc=${encodeURIComponent(options.requestId)}`;
      }
      if (role === "client") {
        return options.ticketId ? `/client/messages?st=${encodeURIComponent(options.ticketId)}` : "/client/messages";
      }
      if (role === "guard") {
        return options.ticketId ? `/guard/messages?st=${encodeURIComponent(options.ticketId)}` : "/guard/messages";
      }
      return options.ticketId ? `/staff/messages?st=${encodeURIComponent(options.ticketId)}` : "/staff/messages";
    case "account_update":
      if (role === "client") return "/client/settings";
      if (role === "guard") return "/guard/settings";
      return "/staff/settings";
    case "job_status_update":
      if (role === "client") {
        return options.requestId ? `/client/requests?jc=${encodeURIComponent(options.requestId)}` : "/client/requests";
      }
      if (role === "guard") {
        return options.requestId ? `/guard/my-jobs?jc=${encodeURIComponent(options.requestId)}` : "/guard/my-jobs";
      }
      return options.requestId ? `/staff/jobs?j=${encodeURIComponent(options.requestId)}` : "/staff/jobs";
    case "client_invoice_ready":
      return options.requestId ? `/client/invoices?inv=${encodeURIComponent(options.requestId)}` : "/client/invoices";
    case "payout_ready":
      return role === "guard" ? "/guard/earnings" : "/staff/payments";
    case "dispute_update":
      if (role === "client") {
        return options.ticketId ? `/client/support?st=${encodeURIComponent(options.ticketId)}` : "/client/support";
      }
      if (role === "guard") {
        return options.ticketId ? `/guard/support?st=${encodeURIComponent(options.ticketId)}` : "/guard/support";
      }
      return options.ticketId ? `/staff/disputes?st=${encodeURIComponent(options.ticketId)}` : "/staff/disputes";
    case "assignment":
    case "guard_application":
      if (role === "client") {
        return options.requestId ? `/client/requests?jc=${encodeURIComponent(options.requestId)}` : "/client/requests";
      }
      if (type === "guard_application") {
        return options.requestId ? `/staff/jobs?j=${encodeURIComponent(options.requestId)}` : "/staff/jobs";
      }
      return options.requestId ? `/guard/my-jobs?jc=${encodeURIComponent(options.requestId)}` : "/guard/my-jobs";
    case "guard_trusted_status":
      return "/guard/profile";
    case "client_trusted_status":
      return "/client/profile";
    case "job_relisted":
      return options.requestId ? `/client/requests?jc=${encodeURIComponent(options.requestId)}` : "/client/requests";
    case "job_schedule_changed":
      return options.requestId ? `/guard/my-jobs?jc=${encodeURIComponent(options.requestId)}` : "/guard/my-jobs";
    case "pre_shift_briefing":
      return options.requestId ? `/guard/map?jc=${encodeURIComponent(options.requestId)}` : "/guard/map";
    case "team_chat_message":
      if (role === "guard") {
        return options.requestId ? `/guard/messages?jc=${encodeURIComponent(options.requestId)}` : "/guard/messages";
      }
      return options.requestId ? `/staff/messages?jc=${encodeURIComponent(options.requestId)}` : "/staff/messages";
    case "standing_crew_invite":
      return "/guard/jobs";
    default:
      if (isStaff) return resolveNotificationUrl2(type, options);
      if (role === "client") return "/client/home";
      if (role === "guard") return "/guard/map";
      return resolveNotificationUrl2(type, options);
  }
}
function buildNotificationData2(type, options = {}) {
  const urlOptions = {
    guardId: options.guardId,
    requestId: options.requestId,
    ticketId: options.ticketId
  };
  const url = options.url ?? (options.role ? resolveNotificationUrlForRole2(type, options.role, urlOptions) : resolveNotificationUrl2(type, urlOptions));
  return {
    type,
    url,
    siteId: options.siteId,
    guardId: options.guardId,
    requestId: options.requestId,
    ticketId: options.ticketId,
    priority: options.priority ?? (type === "emergency_alert" ? "high" : "normal")
  };
}

// lib/push/delivery.ts
var PREF_COLUMN2 = {
  assignment: "assignment",
  guard_checkin: "guard_checkin",
  guard_clockout: "guard_clockout",
  guard_arrived: "guard_arrived",
  guard_left_site: "guard_left_site",
  guard_break_start: "guard_break_start",
  guard_break_end: "guard_break_end",
  missed_checkin: "missed_checkin",
  emergency_alert: "emergency_alert",
  support_message: "support_message",
  job_chat_message: "job_chat_message",
  staff_message: "staff_message",
  guard_message: "guard_message",
  client_message: "client_message",
  job_submitted: "job_submitted",
  job_open_to_guards: "job_open_to_guards",
  guard_application: "guard_application",
  guard_pending_approval: "guard_pending_approval",
  client_pending_approval: "client_pending_approval",
  credential_pending: "credential_pending",
  payment_attention: "payment_attention",
  client_invoice_ready: "client_invoice_ready",
  client_cash_payment_requested: "payment_attention",
  guard_cash_payout_requested: "payment_attention",
  stripe_payment_complete: "payment_attention",
  support_ticket: "support_ticket",
  support_ticket_status: "support_ticket_status",
  dispute_update: "dispute_update",
  guard_trusted_status: "guard_trusted_status",
  client_trusted_status: "client_trusted_status",
  job_relisted: "job_relisted",
  job_schedule_changed: "job_schedule_changed",
  team_chat_message: "team_chat_message",
  standing_crew_invite: "standing_crew_invite",
  crew_lead_request: "crew_lead_request",
  pre_shift_briefing: "pre_shift_briefing",
  guard_en_route: "guard_arrived",
  account_update: "support_ticket_status",
  job_status_update: "assignment",
  payout_ready: "assignment",
  company_placard_expiry: "company_placard_expiry"
};
async function isTypeEnabledForUser2(db, userId, type) {
  const column = PREF_COLUMN2[type];
  if (!column) return true;
  const { data, error } = await db.from("notification_preferences").select(column).eq("user_id", userId).maybeSingle();
  if (error || !data) return true;
  return data[column] !== false;
}
var MAX_RETRIES2 = 2;
var RETRY_DELAY_MS2 = 500;
var vapidConfigured2 = false;
var webPushModule2 = null;
async function getWebPush2() {
  if (!webPushModule2) {
    const mod = await import("web-push");
    webPushModule2 = "default" in mod && mod.default ? mod.default : mod;
  }
  return webPushModule2;
}
async function ensureVapidConfigured2() {
  const publicKey = process.env.VAPID_PUBLIC_KEY?.trim();
  const privateKey = process.env.VAPID_PRIVATE_KEY?.trim();
  const subject = process.env.VAPID_SUBJECT?.trim() || "mailto:support@guardr.co";
  if (!publicKey || !privateKey) return false;
  if (vapidConfigured2) return true;
  const webpush = await getWebPush2();
  webpush.setVapidDetails(subject, publicKey, privateKey);
  vapidConfigured2 = true;
  return true;
}
function isInQuietHours2(quietStart, quietEnd, now = /* @__PURE__ */ new Date()) {
  if (!quietStart || !quietEnd) return false;
  const toMinutes = (time) => {
    const [h, m] = time.split(":").map(Number);
    return h * 60 + m;
  };
  const current = now.getHours() * 60 + now.getMinutes();
  const start = toMinutes(quietStart);
  const end = toMinutes(quietEnd);
  if (start === end) return false;
  if (start < end) return current >= start && current < end;
  return current >= start || current < end;
}
async function sleep2(ms) {
  await new Promise((resolve) => setTimeout(resolve, ms));
}
async function sendToSubscription2(subscription, payload, attempt = 0) {
  if (isFcmNativeEndpoint(subscription.endpoint)) {
    return sendFcmNativeNotification(subscription.endpoint, payload, attempt);
  }
  if (!await ensureVapidConfigured2()) {
    return { ok: false, endpoint: subscription.endpoint };
  }
  try {
    const webpush = await getWebPush2();
    await webpush.sendNotification(
      {
        endpoint: subscription.endpoint,
        keys: { p256dh: subscription.p256dh, auth: subscription.auth }
      },
      JSON.stringify(payload),
      {
        TTL: 60 * 60,
        urgency: payload.priority === "high" ? "high" : "normal"
      }
    );
    return { ok: true };
  } catch (err) {
    const statusCode = err && typeof err === "object" && "statusCode" in err ? Number(err.statusCode) : void 0;
    if (attempt < MAX_RETRIES2 && statusCode !== 404 && statusCode !== 410) {
      await sleep2(RETRY_DELAY_MS2 * (attempt + 1));
      return sendToSubscription2(subscription, payload, attempt + 1);
    }
    return { ok: false, statusCode, endpoint: subscription.endpoint };
  }
}
async function removeInvalidSubscriptions2(db, endpoints) {
  if (!endpoints.length) return;
  await db.from("push_subscriptions").delete().in("endpoint", endpoints);
}
async function deliverToSubscriptions2(db, subscriptions, payload) {
  if (!subscriptions.length) return { sent: 0, failed: 0 };
  const webPushReady = await ensureVapidConfigured2();
  const fcmReady = isFcmConfigured();
  if (!webPushReady && !fcmReady) return { sent: 0, failed: subscriptions.length };
  const prefCache = /* @__PURE__ */ new Map();
  const filtered = [];
  for (const sub of subscriptions) {
    if (payload.excludeUserId && sub.user_id === payload.excludeUserId) {
      continue;
    }
    if (!sub.user_id) {
      filtered.push(sub);
      continue;
    }
    let enabled = prefCache.get(sub.user_id);
    if (enabled === void 0) {
      enabled = await isTypeEnabledForUser2(db, sub.user_id, payload.type);
      prefCache.set(sub.user_id, enabled);
    }
    if (enabled) filtered.push(sub);
  }
  if (!filtered.length) return { sent: 0, failed: 0 };
  const urlOptions = {
    guardId: payload.guardId,
    requestId: payload.requestId,
    ticketId: payload.ticketId
  };
  let sent = 0;
  let failed = 0;
  const staleEndpoints = [];
  for (const sub of filtered) {
    if (payload.type !== "emergency_alert" && payload.priority !== "high" && isInQuietHours2(sub.quiet_hours_start, sub.quiet_hours_end)) {
      continue;
    }
    const platformRole = pushRoleToPlatformRole2(sub.push_role);
    const data = buildNotificationData2(payload.type, {
      url: payload.url ?? resolveNotificationUrlForRole2(payload.type, platformRole, urlOptions),
      siteId: payload.siteId,
      guardId: payload.guardId,
      requestId: payload.requestId,
      ticketId: payload.ticketId,
      priority: payload.priority,
      role: platformRole
    });
    const message = {
      title: payload.title,
      body: payload.body,
      url: data.url,
      eventType: payload.type,
      data,
      tag: payload.siteId ? `${payload.type}-${payload.siteId}` : payload.type,
      priority: data.priority
    };
    const result = await sendToSubscription2(sub, message);
    if (result.ok) {
      sent += 1;
    } else {
      failed += 1;
      if (result.statusCode === 404 || result.statusCode === 410) {
        staleEndpoints.push(result.endpoint);
      }
    }
  }
  await removeInvalidSubscriptions2(db, staleEndpoints);
  return { sent, failed };
}
async function sendNotificationToRole2(db, role, payload) {
  const roles = role === "dispatch" ? ["dispatch", "admin"] : [role];
  const { data: subscriptions, error } = await db.from("push_subscriptions").select("endpoint, p256dh, auth, quiet_hours_start, quiet_hours_end, user_id, push_role").in("push_role", roles);
  if (error) throw new Error(error.message);
  return deliverToSubscriptions2(db, subscriptions ?? [], payload);
}

// lib/push/broadcast.ts
var BROADCAST_ROLES = ["guard", "client", "dispatch", "admin"];
function canSessionBroadcast(platformRole) {
  return platformRole === "owner" || platformRole === "director";
}
async function collectBroadcastRecipientIds(db) {
  const ids = /* @__PURE__ */ new Set();
  const tables = ["clients", "staff", "guards"];
  for (const table of tables) {
    const { data, error } = await db.from(table).select("id");
    if (error) throw new Error(error.message);
    for (const row of data ?? []) {
      if (row?.id) ids.add(String(row.id));
    }
  }
  return [...ids];
}
async function persistBroadcastInbox(db, input) {
  const now = (/* @__PURE__ */ new Date()).toISOString();
  const rows = input.recipientIds.map((userId) => ({
    id: `broadcast-${now}-${userId}`,
    user_id: userId,
    type: "account_update",
    title: input.title,
    body: input.body,
    url: input.url ?? "/",
    metadata: { broadcast: true },
    created_at: now
  }));
  for (let i = 0; i < rows.length; i += 100) {
    const chunk = rows.slice(i, i + 100);
    const { error } = await db.from("user_notifications").upsert(chunk);
    if (error) throw new Error(error.message);
  }
  return rows.length;
}
async function sendPlatformBroadcast(db, input) {
  const title = input.title.trim() || "Guardr";
  const body = input.body.trim();
  const payload = {
    title,
    body,
    type: "account_update",
    url: "/",
    priority: "high"
  };
  let sent = 0;
  let failed = 0;
  for (const role of BROADCAST_ROLES) {
    const result = await sendNotificationToRole2(db, role, payload);
    sent += result.sent;
    failed += result.failed;
  }
  const recipientIds = await collectBroadcastRecipientIds(db);
  const inbox = await persistBroadcastInbox(db, { title, body, url: "/", recipientIds });
  return { sent, failed, inbox };
}

// api/_push/handlers.ts
function pushNotConfiguredResponse() {
  return { status: 503, body: { error: "Web Push is not configured. Set VAPID_PUBLIC_KEY and VAPID_PRIVATE_KEY." } };
}
async function handlePushTest(db, body) {
  const session = await verifySession(db, body);
  if (!session) {
    return { status: 401, body: { error: "Unauthorized \u2014 invalid session" } };
  }
  if (!isPushConfigured()) {
    return pushNotConfiguredResponse();
  }
  if (body.broadcast) {
    if (!canSessionBroadcast(session.platformRole)) {
      return { status: 403, body: { error: "Only Directors and Founders can broadcast" } };
    }
    const message = typeof body.body === "string" ? body.body.trim() : "";
    if (!message) {
      return { status: 400, body: { error: "Broadcast message is required" } };
    }
    const title = typeof body.title === "string" && body.title.trim() ? body.title.trim() : "Guardr";
    const result2 = await sendPlatformBroadcast(db, { title, body: message });
    return { status: 200, body: { ok: true, ...result2 } };
  }
  const data = buildNotificationData("test", { siteId: body.siteId });
  const result = await dispatchPushNotification(db, {
    userId: session.userId,
    title: "Guardr test alert",
    body: "Push notifications are working. You will receive operational alerts here.",
    type: "test",
    url: data.url,
    siteId: body.siteId
  });
  return { status: 200, body: { ok: true, ...result } };
}

// api/_push/entries/test.ts
async function getSupabaseAdmin() {
  const url = process.env.SUPABASE_URL || process.env.NEXT_PUBLIC_SUPABASE_URL || process.env.VITE_SUPABASE_URL;
  const serviceKey = process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.SUPABASE_KEY;
  if (!url || !serviceKey) return null;
  const { createClient } = await import("@supabase/supabase-js");
  return createClient(url, serviceKey, {
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function readBody(req) {
  const raw = req.body;
  if (!raw) return {};
  if (typeof raw === "string") {
    try {
      return JSON.parse(raw);
    } catch {
      return {};
    }
  }
  return raw;
}
async function handler(req, res) {
  if (applyApiCors(req, res)) return;
  if (req.method !== "POST") {
    return res.status(405).json({ error: "Method not allowed" });
  }
  try {
    const db = await getSupabaseAdmin();
    if (!db) {
      return res.status(503).json({ error: "Database is not configured" });
    }
    const result = await handlePushTest(db, readBody(req));
    return res.status(result.status).json(result.body);
  } catch (err) {
    const message = err instanceof Error ? err.message : "Push test failed";
    console.error("Push test error:", message, err);
    return res.status(500).json({ error: message });
  }
}
export {
  handler as default
};
