// Generated by scripts/bundle-push-handlers.mjs — do not edit.
// @ts-nocheck

// api/_push/apiCors.ts
var GUARDR_ORIGIN = /^https:\/\/([a-z0-9-]+\.)?guardr\.co$/i;
var CAPACITOR_ORIGIN = /^https:\/\/localhost(?::\d+)?$/i;
function isAllowedApiOrigin(origin) {
  return GUARDR_ORIGIN.test(origin) || CAPACITOR_ORIGIN.test(origin) || /^capacitor:\/\//i.test(origin);
}
function applyApiCors(req, res) {
  const origin = req.headers.origin;
  if (origin && isAllowedApiOrigin(origin)) {
    res.setHeader("Access-Control-Allow-Origin", origin);
    res.setHeader("Access-Control-Allow-Credentials", "true");
    res.setHeader("Vary", "Origin");
  }
  if (req.method === "OPTIONS") {
    res.setHeader("Access-Control-Allow-Methods", "GET, POST, PUT, PATCH, DELETE, OPTIONS");
    res.setHeader("Access-Control-Allow-Headers", "Content-Type, Authorization");
    res.status(204).end();
    return true;
  }
  return false;
}

// api/_push/dedup.ts
var DEDUP_TTL_MS = 25 * 60 * 60 * 1e3;

// api/_push/handlers.ts
function handlePushVapidPublicKey() {
  const publicKey = process.env.VAPID_PUBLIC_KEY?.trim();
  if (!publicKey) {
    return { status: 503, body: { error: "VAPID public key is not configured" } };
  }
  return { status: 200, body: { publicKey } };
}

// api/_push/entries/vapid-public-key.ts
function handler(req, res) {
  if (applyApiCors(req, res)) return;
  if (req.method !== "GET") {
    return res.status(405).json({ error: "Method not allowed" });
  }
  const result = handlePushVapidPublicKey();
  return res.status(result.status).json(result.body);
}
export {
  handler as default
};
