// Generated by scripts/bundle-push-handlers.mjs — do not edit.
// @ts-nocheck

// api/_push/dedup.ts
var DEDUP_TTL_MS = 25 * 60 * 60 * 1e3;
function companyPlacardExpiryDedupKey(documentType, tier, expiryDate, userId) {
  return `company_placard_expiry:${documentType}:${tier}:${expiryDate}:${userId}`;
}
function companyPlacardMissingDedupKey(documentType, weekBucket, userId) {
  return `company_placard_missing:${documentType}:${weekBucket}:${userId}`;
}
async function claimNotificationDedup(db, dedupKey, notificationType) {
  const { data: existing } = await db.from("push_notification_dedup").select("id").eq("id", dedupKey).maybeSingle();
  if (existing?.id) return true;
  const { error } = await db.from("push_notification_dedup").insert({
    id: dedupKey,
    notification_type: notificationType
  });
  if (error) {
    if (error.code === "23505") return true;
    throw new Error(error.message);
  }
  return false;
}
async function pruneStaleNotificationDedup(db) {
  const cutoff = new Date(Date.now() - DEDUP_TTL_MS).toISOString();
  await db.from("push_notification_dedup").delete().lt("created_at", cutoff);
}

// api/_push/routing.ts
function pushRoleToPlatformRole(pushRole) {
  switch (pushRole) {
    case "guard":
      return "guard";
    case "client":
      return "client";
    case "dispatch":
    case "admin":
      return "administrator";
    default:
      return "administrator";
  }
}
function resolveNotificationUrl(type, options = {}) {
  switch (type) {
    case "missed_checkin":
    case "guard_checkin":
    case "guard_clockout":
    case "guard_arrived":
    case "guard_en_route":
    case "guard_left_site":
    case "guard_break_start":
    case "guard_break_end":
      return options.requestId ? `/staff/jobs?j=${encodeURIComponent(options.requestId)}` : "/staff/jobs";
    case "job_open_to_guards":
      return options.requestId ? `/guard/map?jc=${encodeURIComponent(options.requestId)}` : "/guard/map";
    case "client_cash_payment_requested":
    case "guard_cash_payout_requested":
    case "stripe_payment_complete":
      return options.requestId ? `/staff/payments?j=${encodeURIComponent(options.requestId)}` : "/staff/payments";
    case "assignment":
      return options.requestId ? `/guard/my-jobs?jc=${encodeURIComponent(options.requestId)}` : "/guard/my-jobs";
    case "emergency_alert":
      if (options.requestId) {
        return `/staff/jobs?j=${encodeURIComponent(options.requestId)}`;
      }
      if (options.ticketId) {
        return `/staff/support?st=${encodeURIComponent(options.ticketId)}`;
      }
      return "/staff/incidents";
    case "support_message":
      return options.ticketId ? `/staff/support?st=${encodeURIComponent(options.ticketId)}` : "/staff/support";
    case "job_chat_message":
      return options.requestId ? `/staff/messages?mtab=jobs&jc=${encodeURIComponent(options.requestId)}` : "/staff/messages?mtab=jobs";
    case "staff_message":
      return "/staff/messages?mtab=team";
    case "guard_message":
      return "/guard/guard-chat";
    case "client_message":
      return "/client/messages";
    case "job_submitted":
      return options.requestId ? `/staff/jobs?j=${encodeURIComponent(options.requestId)}` : "/staff/jobs";
    case "guard_application":
      return options.requestId ? `/staff/jobs?j=${encodeURIComponent(options.requestId)}` : "/staff/jobs";
    case "crew_lead_request":
      return "/staff/crews";
    case "guard_pending_approval":
      return options.guardId ? `/staff/applications?g=${encodeURIComponent(options.guardId)}` : "/staff/applications";
    case "client_pending_approval":
      return "/staff/applications";
    case "credential_pending":
      return options.guardId ? `/staff/credentials?g=${encodeURIComponent(options.guardId)}` : "/staff/credentials";
    case "payment_attention":
      return options.requestId ? `/staff/payments?j=${encodeURIComponent(options.requestId)}` : "/staff/payments";
    case "client_invoice_ready":
      return options.requestId ? `/client/invoices?inv=${encodeURIComponent(options.requestId)}` : "/client/invoices";
    case "support_ticket":
    case "support_ticket_status":
      return options.ticketId ? `/staff/messages?st=${encodeURIComponent(options.ticketId)}` : "/staff/messages";
    case "account_update":
      return "/staff/settings";
    case "job_status_update":
      return options.requestId ? `/staff/jobs?j=${encodeURIComponent(options.requestId)}` : "/staff/jobs";
    case "payout_ready":
      return "/guard/earnings";
    case "dispute_update":
      return options.ticketId ? `/staff/disputes?st=${encodeURIComponent(options.ticketId)}` : "/staff/disputes";
    case "guard_trusted_status":
      return options.guardId ? `/guard/profile?g=${encodeURIComponent(options.guardId)}` : "/guard/profile";
    case "client_trusted_status":
      return "/client/profile";
    case "job_relisted":
      return options.requestId ? `/client/requests?jc=${encodeURIComponent(options.requestId)}` : "/client/requests";
    case "job_schedule_changed":
      return options.requestId ? `/guard/my-jobs?jc=${encodeURIComponent(options.requestId)}` : "/guard/my-jobs";
    case "team_chat_message":
      return options.requestId ? `/staff/messages?mtab=team&jc=${encodeURIComponent(options.requestId)}` : "/staff/messages?mtab=team";
    case "standing_crew_invite":
      return "/guard/crew";
    case "company_placard_expiry":
      return "/staff/settings";
    case "pre_shift_briefing":
      return options.requestId ? `/guard/map?jc=${encodeURIComponent(options.requestId)}` : "/guard/map";
    case "test":
      return "/";
    default:
      return "/";
  }
}
function resolveNotificationUrlForRole(type, role, options = {}) {
  const isStaff = role === "moderator" || role === "administrator" || role === "director" || role === "owner";
  switch (type) {
    case "guard_arrived":
    case "guard_en_route":
    case "guard_left_site":
      if (role === "client") {
        return options.requestId ? `/client/map?jc=${encodeURIComponent(options.requestId)}` : "/client/map";
      }
      if (role === "guard") {
        return options.requestId ? `/guard/my-jobs?jc=${encodeURIComponent(options.requestId)}` : "/guard/my-jobs";
      }
      return options.requestId ? `/staff/jobs?j=${encodeURIComponent(options.requestId)}` : "/staff/jobs";
    case "job_open_to_guards":
      return options.requestId ? `/guard/map?jc=${encodeURIComponent(options.requestId)}` : "/guard/map";
    case "client_cash_payment_requested":
    case "guard_cash_payout_requested":
    case "stripe_payment_complete":
      if (role === "client") {
        return options.requestId ? `/client/requests?jc=${encodeURIComponent(options.requestId)}` : "/client/requests";
      }
      if (role === "guard") {
        return "/guard/earnings";
      }
      return options.requestId ? `/staff/payments?j=${encodeURIComponent(options.requestId)}` : "/staff/payments";
    case "payment_attention":
      if (role === "client") {
        return options.requestId ? `/client/requests?jc=${encodeURIComponent(options.requestId)}` : "/client/requests";
      }
      if (role === "guard") {
        return "/guard/earnings";
      }
      return options.requestId ? `/staff/payments?j=${encodeURIComponent(options.requestId)}` : "/staff/payments";
    case "support_message":
      if (role === "client") {
        return options.ticketId ? `/client/support?st=${encodeURIComponent(options.ticketId)}` : "/client/support";
      }
      if (role === "guard") {
        return options.ticketId ? `/guard/support?st=${encodeURIComponent(options.ticketId)}` : "/guard/support";
      }
      return options.ticketId ? `/staff/support?st=${encodeURIComponent(options.ticketId)}` : "/staff/support";
    case "job_chat_message":
      if (role === "client") {
        return options.requestId ? `/client/map?jc=${encodeURIComponent(options.requestId)}&chat=1` : "/client/messages";
      }
      if (role === "guard") {
        return options.requestId ? `/guard/my-jobs?jc=${encodeURIComponent(options.requestId)}&chat=1` : "/guard/my-jobs";
      }
      return options.requestId ? `/staff/messages?mtab=jobs&jc=${encodeURIComponent(options.requestId)}` : "/staff/messages?mtab=jobs";
    case "emergency_alert":
      if (role === "client") {
        return options.requestId ? `/client/map?jc=${encodeURIComponent(options.requestId)}` : "/client/map";
      }
      if (role === "guard") {
        return options.requestId ? `/guard/my-jobs?jc=${encodeURIComponent(options.requestId)}` : "/guard/my-jobs";
      }
      if (options.requestId) {
        return `/staff/jobs?j=${encodeURIComponent(options.requestId)}`;
      }
      if (options.ticketId) {
        return `/staff/support?st=${encodeURIComponent(options.ticketId)}`;
      }
      return "/staff/incidents";
    case "missed_checkin":
    case "guard_checkin":
    case "guard_clockout":
    case "guard_break_start":
    case "guard_break_end":
      if (role === "guard") {
        return options.requestId ? `/guard/my-jobs?jc=${encodeURIComponent(options.requestId)}` : "/guard/my-jobs";
      }
      if (role === "client") {
        return options.requestId ? `/client/map?jc=${encodeURIComponent(options.requestId)}` : "/client/map";
      }
      return options.requestId ? `/staff/jobs?j=${encodeURIComponent(options.requestId)}` : "/staff/jobs";
    case "staff_message":
      return "/staff/messages?mtab=team";
    case "guard_message":
      return "/guard/guard-chat";
    case "client_message":
      if (role === "client") return "/client/messages";
      return "/staff/messages?mtab=team";
    case "support_ticket":
    case "support_ticket_status":
      if (role === "client" && options.requestId) {
        return `/client/requests?jc=${encodeURIComponent(options.requestId)}`;
      }
      if (role === "client") {
        return options.ticketId ? `/client/messages?st=${encodeURIComponent(options.ticketId)}` : "/client/messages";
      }
      if (role === "guard") {
        return options.ticketId ? `/guard/messages?st=${encodeURIComponent(options.ticketId)}` : "/guard/messages";
      }
      return options.ticketId ? `/staff/messages?st=${encodeURIComponent(options.ticketId)}` : "/staff/messages";
    case "account_update":
      if (role === "client") return "/client/settings";
      if (role === "guard") return "/guard/settings";
      return "/staff/settings";
    case "job_status_update":
      if (role === "client") {
        return options.requestId ? `/client/requests?jc=${encodeURIComponent(options.requestId)}` : "/client/requests";
      }
      if (role === "guard") {
        return options.requestId ? `/guard/my-jobs?jc=${encodeURIComponent(options.requestId)}` : "/guard/my-jobs";
      }
      return options.requestId ? `/staff/jobs?j=${encodeURIComponent(options.requestId)}` : "/staff/jobs";
    case "client_invoice_ready":
      return options.requestId ? `/client/invoices?inv=${encodeURIComponent(options.requestId)}` : "/client/invoices";
    case "payout_ready":
      return role === "guard" ? "/guard/earnings" : "/staff/payments";
    case "dispute_update":
      if (role === "client") {
        return options.ticketId ? `/client/support?st=${encodeURIComponent(options.ticketId)}` : "/client/support";
      }
      if (role === "guard") {
        return options.ticketId ? `/guard/support?st=${encodeURIComponent(options.ticketId)}` : "/guard/support";
      }
      return options.ticketId ? `/staff/disputes?st=${encodeURIComponent(options.ticketId)}` : "/staff/disputes";
    case "assignment":
    case "guard_application":
      if (role === "client") {
        return options.requestId ? `/client/requests?jc=${encodeURIComponent(options.requestId)}` : "/client/requests";
      }
      if (type === "guard_application") {
        return options.requestId ? `/staff/jobs?j=${encodeURIComponent(options.requestId)}` : "/staff/jobs";
      }
      return options.requestId ? `/guard/my-jobs?jc=${encodeURIComponent(options.requestId)}` : "/guard/my-jobs";
    case "guard_trusted_status":
      return "/guard/profile";
    case "client_trusted_status":
      return "/client/profile";
    case "job_relisted":
      return options.requestId ? `/client/requests?jc=${encodeURIComponent(options.requestId)}` : "/client/requests";
    case "job_schedule_changed":
      return options.requestId ? `/guard/my-jobs?jc=${encodeURIComponent(options.requestId)}` : "/guard/my-jobs";
    case "pre_shift_briefing":
      return options.requestId ? `/guard/map?jc=${encodeURIComponent(options.requestId)}` : "/guard/map";
    case "team_chat_message":
      if (role === "guard") {
        return options.requestId ? `/guard/messages?tc=${encodeURIComponent(options.requestId)}` : "/guard/messages";
      }
      return options.requestId ? `/staff/messages?mtab=team&jc=${encodeURIComponent(options.requestId)}` : "/staff/messages?mtab=team";
    case "standing_crew_invite":
      return "/guard/crew";
    default:
      if (isStaff) return resolveNotificationUrl(type, options);
      if (role === "client") return "/client/home";
      if (role === "guard") return "/guard/map";
      return resolveNotificationUrl(type, options);
  }
}
function rolesForNotificationType(type) {
  switch (type) {
    case "missed_checkin":
    case "guard_checkin":
    case "guard_clockout":
    case "guard_arrived":
    case "guard_en_route":
    case "guard_left_site":
    case "guard_break_start":
    case "guard_break_end":
      return ["dispatch", "admin"];
    case "job_open_to_guards":
      return ["guard"];
    case "client_cash_payment_requested":
    case "guard_cash_payout_requested":
    case "stripe_payment_complete":
      return ["dispatch", "admin"];
    case "assignment":
      return ["guard"];
    case "guard_application":
      return ["dispatch", "admin"];
    case "crew_lead_request":
      return ["dispatch", "admin"];
    case "emergency_alert":
      return ["guard", "client", "dispatch", "admin"];
    case "support_message":
      return ["dispatch", "admin", "client", "guard"];
    case "job_chat_message":
      return ["client", "guard", "dispatch", "admin"];
    case "staff_message":
      return ["dispatch", "admin"];
    case "guard_message":
      return ["guard"];
    case "client_message":
      return ["client"];
    case "job_submitted":
    case "guard_pending_approval":
    case "client_pending_approval":
    case "credential_pending":
    case "payment_attention":
      return ["dispatch", "admin"];
    case "client_invoice_ready":
      return ["client"];
    case "support_ticket":
      return ["dispatch", "admin"];
    case "support_ticket_status":
      return ["client", "guard"];
    case "dispute_update":
      return ["dispatch", "admin", "client", "guard"];
    case "guard_trusted_status":
      return ["guard"];
    case "client_trusted_status":
      return ["client"];
    case "job_relisted":
      return ["client"];
    case "job_schedule_changed":
      return ["guard"];
    case "pre_shift_briefing":
      return ["guard"];
    case "team_chat_message":
      return ["guard", "dispatch", "admin"];
    case "standing_crew_invite":
      return ["guard"];
    case "company_placard_expiry":
      return ["dispatch", "admin"];
    case "test":
      return [];
    default:
      return ["guard", "dispatch"];
  }
}
function buildNotificationData(type, options = {}) {
  const urlOptions = {
    guardId: options.guardId,
    requestId: options.requestId,
    ticketId: options.ticketId
  };
  const url = options.url ?? (options.role ? resolveNotificationUrlForRole(type, options.role, urlOptions) : resolveNotificationUrl(type, urlOptions));
  return {
    type,
    url,
    siteId: options.siteId,
    guardId: options.guardId,
    requestId: options.requestId,
    ticketId: options.ticketId,
    priority: options.priority ?? (type === "emergency_alert" ? "high" : "normal")
  };
}

// lib/push/fcm.ts
import { createSign } from "node:crypto";
var FCM_NATIVE_ENDPOINT_PREFIX = "fcm-native:";
var cachedAccessToken = null;
function parseServiceAccountJson() {
  const raw = process.env.FCM_SERVICE_ACCOUNT_JSON?.trim();
  if (!raw) return null;
  try {
    const parsed = JSON.parse(raw);
    if (parsed.project_id && parsed.client_email && parsed.private_key) {
      return {
        project_id: parsed.project_id,
        client_email: parsed.client_email,
        private_key: parsed.private_key
      };
    }
  } catch {
  }
  return null;
}
function isFcmConfigured() {
  return !!process.env.FCM_SERVER_KEY?.trim() || !!parseServiceAccountJson();
}
function isFcmNativeEndpoint(endpoint) {
  return endpoint.startsWith(FCM_NATIVE_ENDPOINT_PREFIX);
}
function fcmTokenFromEndpoint(endpoint) {
  if (!isFcmNativeEndpoint(endpoint)) return null;
  const token = endpoint.slice(FCM_NATIVE_ENDPOINT_PREFIX.length).trim();
  return token || null;
}
function stringifyDataValue(value) {
  if (value == null) return "";
  if (typeof value === "string") return value;
  return JSON.stringify(value);
}
function buildDataPayload(payload) {
  const data = {};
  const nested = payload.data;
  if (nested && typeof nested === "object") {
    for (const [key, value] of Object.entries(nested)) {
      data[key] = stringifyDataValue(value);
    }
  }
  if (payload.url) data.url = stringifyDataValue(payload.url);
  if (payload.eventType) data.eventType = stringifyDataValue(payload.eventType);
  if (payload.priority) data.priority = stringifyDataValue(payload.priority);
  return data;
}
function base64UrlEncode(value) {
  return Buffer.from(value).toString("base64url");
}
async function getFcmAccessToken(serviceAccount) {
  const now = Date.now();
  if (cachedAccessToken && cachedAccessToken.expiresAt > now + 6e4) {
    return cachedAccessToken.token;
  }
  const issuedAt = Math.floor(now / 1e3);
  const header = base64UrlEncode(JSON.stringify({ alg: "RS256", typ: "JWT" }));
  const claim = base64UrlEncode(
    JSON.stringify({
      iss: serviceAccount.client_email,
      scope: "https://www.googleapis.com/auth/firebase.messaging",
      aud: "https://oauth2.googleapis.com/token",
      iat: issuedAt,
      exp: issuedAt + 3600
    })
  );
  const unsigned = `${header}.${claim}`;
  const sign = createSign("RSA-SHA256");
  sign.update(unsigned);
  const signature = sign.sign(serviceAccount.private_key, "base64url");
  const assertion = `${unsigned}.${signature}`;
  try {
    const res = await fetch("https://oauth2.googleapis.com/token", {
      method: "POST",
      headers: { "Content-Type": "application/x-www-form-urlencoded" },
      body: new URLSearchParams({
        grant_type: "urn:ietf:params:oauth:grant-type:jwt-bearer",
        assertion
      })
    });
    const body = await res.json().catch(() => ({}));
    if (!res.ok || !body.access_token) return null;
    cachedAccessToken = {
      token: body.access_token,
      expiresAt: now + (body.expires_in ?? 3600) * 1e3
    };
    return body.access_token;
  } catch {
    return null;
  }
}
async function sendFcmV1Notification(serviceAccount, endpoint, token, payload, attempt = 0) {
  const accessToken = await getFcmAccessToken(serviceAccount);
  if (!accessToken) return { ok: false, endpoint };
  const data = buildDataPayload(payload);
  try {
    const res = await fetch(
      `https://fcm.googleapis.com/v1/projects/${serviceAccount.project_id}/messages:send`,
      {
        method: "POST",
        headers: {
          Authorization: `Bearer ${accessToken}`,
          "Content-Type": "application/json"
        },
        body: JSON.stringify({
          message: {
            token,
            notification: {
              title: String(payload.title ?? "Guardr"),
              body: String(payload.body ?? "")
            },
            data,
            android: {
              priority: payload.priority === "high" ? "high" : "normal",
              notification: {
                channel_id: "guardr_alerts"
              }
            }
          }
        })
      }
    );
    if (res.ok) return { ok: true };
    const body = await res.json().catch(() => ({}));
    const errStatus = body.error?.status;
    if (errStatus === "NOT_FOUND" || errStatus === "UNREGISTERED" || errStatus === "INVALID_ARGUMENT") {
      return { ok: false, statusCode: 410, endpoint };
    }
    if (attempt < 2 && res.status >= 500) {
      await new Promise((resolve) => setTimeout(resolve, 500 * (attempt + 1)));
      return sendFcmV1Notification(serviceAccount, endpoint, token, payload, attempt + 1);
    }
    return { ok: false, statusCode: res.status, endpoint };
  } catch {
    if (attempt < 2) {
      await new Promise((resolve) => setTimeout(resolve, 500 * (attempt + 1)));
      return sendFcmV1Notification(serviceAccount, endpoint, token, payload, attempt + 1);
    }
    return { ok: false, endpoint };
  }
}
async function sendFcmLegacyNotification(endpoint, token, payload, serverKey, attempt = 0) {
  const data = buildDataPayload(payload);
  try {
    const res = await fetch("https://fcm.googleapis.com/fcm/send", {
      method: "POST",
      headers: {
        Authorization: `key=${serverKey}`,
        "Content-Type": "application/json"
      },
      body: JSON.stringify({
        to: token,
        notification: {
          title: String(payload.title ?? "Guardr"),
          body: String(payload.body ?? ""),
          android_channel_id: "guardr_alerts"
        },
        data,
        priority: payload.priority === "high" ? "high" : "normal"
      })
    });
    const body = await res.json().catch(() => ({}));
    if (res.ok && body.success === 1) return { ok: true };
    const errCode = body.results?.[0]?.error;
    if (errCode === "NotRegistered" || errCode === "InvalidRegistration") {
      return { ok: false, statusCode: 410, endpoint };
    }
    if (attempt < 2 && res.status >= 500) {
      await new Promise((resolve) => setTimeout(resolve, 500 * (attempt + 1)));
      return sendFcmLegacyNotification(endpoint, token, payload, serverKey, attempt + 1);
    }
    return { ok: false, statusCode: res.status, endpoint };
  } catch {
    if (attempt < 2) {
      await new Promise((resolve) => setTimeout(resolve, 500 * (attempt + 1)));
      return sendFcmLegacyNotification(endpoint, token, payload, serverKey, attempt + 1);
    }
    return { ok: false, endpoint };
  }
}
async function sendFcmNativeNotification(endpoint, payload, attempt = 0) {
  const token = fcmTokenFromEndpoint(endpoint);
  if (!token) return { ok: false, endpoint };
  const serviceAccount = parseServiceAccountJson();
  if (serviceAccount) {
    return sendFcmV1Notification(serviceAccount, endpoint, token, payload, attempt);
  }
  const serverKey = process.env.FCM_SERVER_KEY?.trim();
  if (!serverKey) return { ok: false, endpoint };
  return sendFcmLegacyNotification(endpoint, token, payload, serverKey, attempt);
}

// api/_push/delivery.ts
var PREF_COLUMN = {
  assignment: "assignment",
  guard_checkin: "guard_checkin",
  guard_clockout: "guard_clockout",
  guard_arrived: "guard_arrived",
  guard_left_site: "guard_left_site",
  guard_break_start: "guard_break_start",
  guard_break_end: "guard_break_end",
  missed_checkin: "missed_checkin",
  emergency_alert: "emergency_alert",
  support_message: "support_message",
  job_chat_message: "job_chat_message",
  staff_message: "staff_message",
  guard_message: "guard_message",
  client_message: "client_message",
  job_submitted: "job_submitted",
  job_open_to_guards: "job_open_to_guards",
  guard_application: "guard_application",
  guard_pending_approval: "guard_pending_approval",
  client_pending_approval: "client_pending_approval",
  credential_pending: "credential_pending",
  payment_attention: "payment_attention",
  client_invoice_ready: "client_invoice_ready",
  client_cash_payment_requested: "payment_attention",
  guard_cash_payout_requested: "payment_attention",
  stripe_payment_complete: "payment_attention",
  support_ticket: "support_ticket",
  support_ticket_status: "support_ticket_status",
  dispute_update: "dispute_update",
  guard_trusted_status: "guard_trusted_status",
  client_trusted_status: "client_trusted_status",
  job_relisted: "job_relisted",
  job_schedule_changed: "job_schedule_changed",
  team_chat_message: "team_chat_message",
  standing_crew_invite: "standing_crew_invite",
  crew_lead_request: "crew_lead_request",
  pre_shift_briefing: "pre_shift_briefing",
  guard_en_route: "guard_arrived",
  account_update: "support_ticket_status",
  job_status_update: "assignment",
  payout_ready: "assignment",
  company_placard_expiry: "company_placard_expiry"
};
async function isTypeEnabledForUser(db, userId, type) {
  const column = PREF_COLUMN[type];
  if (!column) return true;
  const { data, error } = await db.from("notification_preferences").select(column).eq("user_id", userId).maybeSingle();
  if (error || !data) return true;
  return data[column] !== false;
}
var MAX_RETRIES = 2;
var RETRY_DELAY_MS = 500;
var vapidConfigured = false;
var webPushModule = null;
async function getWebPush() {
  if (!webPushModule) {
    const mod = await import("web-push");
    webPushModule = "default" in mod && mod.default ? mod.default : mod;
  }
  return webPushModule;
}
async function ensureVapidConfigured() {
  const publicKey = process.env.VAPID_PUBLIC_KEY?.trim();
  const privateKey = process.env.VAPID_PRIVATE_KEY?.trim();
  const subject = process.env.VAPID_SUBJECT?.trim() || "mailto:support@guardr.co";
  if (!publicKey || !privateKey) return false;
  if (vapidConfigured) return true;
  const webpush = await getWebPush();
  webpush.setVapidDetails(subject, publicKey, privateKey);
  vapidConfigured = true;
  return true;
}
function isInQuietHours(quietStart, quietEnd, now = /* @__PURE__ */ new Date()) {
  if (!quietStart || !quietEnd) return false;
  const toMinutes = (time) => {
    const [h, m] = time.split(":").map(Number);
    return h * 60 + m;
  };
  const current = now.getHours() * 60 + now.getMinutes();
  const start = toMinutes(quietStart);
  const end = toMinutes(quietEnd);
  if (start === end) return false;
  if (start < end) return current >= start && current < end;
  return current >= start || current < end;
}
async function sleep(ms) {
  await new Promise((resolve) => setTimeout(resolve, ms));
}
async function sendToSubscription(subscription, payload, attempt = 0) {
  if (isFcmNativeEndpoint(subscription.endpoint)) {
    return sendFcmNativeNotification(subscription.endpoint, payload, attempt);
  }
  if (!await ensureVapidConfigured()) {
    return { ok: false, endpoint: subscription.endpoint };
  }
  try {
    const webpush = await getWebPush();
    await webpush.sendNotification(
      {
        endpoint: subscription.endpoint,
        keys: { p256dh: subscription.p256dh, auth: subscription.auth }
      },
      JSON.stringify(payload),
      {
        TTL: 60 * 60,
        urgency: payload.priority === "high" ? "high" : "normal"
      }
    );
    return { ok: true };
  } catch (err) {
    const statusCode = err && typeof err === "object" && "statusCode" in err ? Number(err.statusCode) : void 0;
    if (attempt < MAX_RETRIES && statusCode !== 404 && statusCode !== 410) {
      await sleep(RETRY_DELAY_MS * (attempt + 1));
      return sendToSubscription(subscription, payload, attempt + 1);
    }
    return { ok: false, statusCode, endpoint: subscription.endpoint };
  }
}
async function removeInvalidSubscriptions(db, endpoints) {
  if (!endpoints.length) return;
  await db.from("push_subscriptions").delete().in("endpoint", endpoints);
}
async function deliverToSubscriptions(db, subscriptions, payload) {
  if (!subscriptions.length) return { sent: 0, failed: 0 };
  const webPushReady = await ensureVapidConfigured();
  const fcmReady = isFcmConfigured();
  if (!webPushReady && !fcmReady) return { sent: 0, failed: subscriptions.length };
  const prefCache = /* @__PURE__ */ new Map();
  const filtered = [];
  for (const sub of subscriptions) {
    if (payload.excludeUserId && sub.user_id === payload.excludeUserId) {
      continue;
    }
    if (!sub.user_id) {
      filtered.push(sub);
      continue;
    }
    let enabled = prefCache.get(sub.user_id);
    if (enabled === void 0) {
      enabled = await isTypeEnabledForUser(db, sub.user_id, payload.type);
      prefCache.set(sub.user_id, enabled);
    }
    if (enabled) filtered.push(sub);
  }
  if (!filtered.length) return { sent: 0, failed: 0 };
  const urlOptions = {
    guardId: payload.guardId,
    requestId: payload.requestId,
    ticketId: payload.ticketId
  };
  let sent = 0;
  let failed = 0;
  const staleEndpoints = [];
  for (const sub of filtered) {
    if (payload.type !== "emergency_alert" && payload.priority !== "high" && isInQuietHours(sub.quiet_hours_start, sub.quiet_hours_end)) {
      continue;
    }
    const platformRole = pushRoleToPlatformRole(sub.push_role);
    const data = buildNotificationData(payload.type, {
      url: payload.url ?? resolveNotificationUrlForRole(payload.type, platformRole, urlOptions),
      siteId: payload.siteId,
      guardId: payload.guardId,
      requestId: payload.requestId,
      ticketId: payload.ticketId,
      priority: payload.priority,
      role: platformRole
    });
    const message = {
      title: payload.title,
      body: payload.body,
      url: data.url,
      eventType: payload.type,
      data,
      tag: payload.siteId ? `${payload.type}-${payload.siteId}` : payload.type,
      priority: data.priority
    };
    const result = await sendToSubscription(sub, message);
    if (result.ok) {
      sent += 1;
    } else {
      failed += 1;
      if (result.statusCode === 404 || result.statusCode === 410) {
        staleEndpoints.push(result.endpoint);
      }
    }
  }
  await removeInvalidSubscriptions(db, staleEndpoints);
  return { sent, failed };
}
async function sendNotificationToUser(db, userId, payload) {
  const enabled = await isTypeEnabledForUser(db, userId, payload.type);
  if (!enabled) return { sent: 0, failed: 0 };
  const { data: subscriptions, error } = await db.from("push_subscriptions").select("endpoint, p256dh, auth, quiet_hours_start, quiet_hours_end, user_id, push_role").eq("user_id", userId);
  if (error) throw new Error(error.message);
  return deliverToSubscriptions(db, subscriptions ?? [], payload);
}
async function sendNotificationToRole(db, role, payload) {
  const roles = role === "dispatch" ? ["dispatch", "admin"] : [role];
  const { data: subscriptions, error } = await db.from("push_subscriptions").select("endpoint, p256dh, auth, quiet_hours_start, quiet_hours_end, user_id, push_role").in("push_role", roles);
  if (error) throw new Error(error.message);
  return deliverToSubscriptions(db, subscriptions ?? [], payload);
}
async function dispatchPushNotification(db, payload) {
  if (payload.userId) {
    return sendNotificationToUser(db, payload.userId, payload);
  }
  if (payload.role) {
    return sendNotificationToRole(db, payload.role, payload);
  }
  const roles = rolesForNotificationType(payload.type);
  let sent = 0;
  let failed = 0;
  for (const role of roles) {
    const result = await sendNotificationToRole(db, role, payload);
    sent += result.sent;
    failed += result.failed;
  }
  return { sent, failed };
}

// api/_push/config.ts
function isPushConfigured() {
  const vapidReady = !!(process.env.VAPID_PUBLIC_KEY?.trim() && process.env.VAPID_PRIVATE_KEY?.trim());
  return vapidReady || isFcmConfigured();
}

// api/_push/companyPlacardExpiry.ts
var NOTIFICATION_TYPE = "company_placard_expiry";
var SETTINGS_URL = "/staff/settings";
var EXECUTIVE_ROLES = ["Founder", "Owner", "Director"];
var PLACARD_CATALOG = [
  { id: "business_entity_registration", title: "Business Entity Registration", required: true },
  { id: "general_liability_insurance", title: "General Liability Insurance (COI)", required: true },
  { id: "professional_liability_insurance", title: "Professional / E&O Liability Insurance", required: false },
  { id: "workers_comp_insurance", title: "Workers' Compensation Insurance", required: false },
  { id: "business_license", title: "City / County Business License", required: false }
];
function docHasContent(row) {
  if (!row) return false;
  return Boolean(
    row.document_number?.trim() || row.issuer?.trim() || row.image_url?.trim() || row.expiry_date?.trim()
  );
}
function daysUntilExpiry(expiryDate, now) {
  const expiry = /* @__PURE__ */ new Date(`${expiryDate}T23:59:59`);
  if (Number.isNaN(expiry.getTime())) return null;
  return (expiry.getTime() - now.getTime()) / (1e3 * 60 * 60 * 24);
}
function expiryAlertTier(expiryDate, hasContent, required, now) {
  if (!hasContent && required) return "missing";
  if (!expiryDate?.trim()) return null;
  const daysUntil = daysUntilExpiry(expiryDate, now);
  if (daysUntil == null) return null;
  if (daysUntil < 0) return "expired";
  if (daysUntil <= 1) return "1";
  if (daysUntil <= 7) return "7";
  if (daysUntil <= 14) return "14";
  if (daysUntil <= 30) return "30";
  if (daysUntil <= 45) return "45";
  return null;
}
function formatDate(isoDate) {
  const date = /* @__PURE__ */ new Date(`${isoDate}T12:00:00`);
  if (Number.isNaN(date.getTime())) return isoDate;
  return date.toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" });
}
function alertCopy(documentTitle, tier, expiryDate) {
  const formattedExpiry = expiryDate ? formatDate(expiryDate) : void 0;
  switch (tier) {
    case "missing":
      return {
        title: "Company placard item needed",
        body: `${documentTitle} is required for the public company placard but has not been uploaded yet.`,
        priority: "high"
      };
    case "expired":
      return {
        title: "Company credential expired",
        body: formattedExpiry ? `${documentTitle} expired on ${formattedExpiry}. Update it in Staff Settings.` : `${documentTitle} has expired. Update it in Staff Settings.`,
        priority: "high"
      };
    case "1":
      return {
        title: "Company credential expires tomorrow",
        body: formattedExpiry ? `${documentTitle} expires on ${formattedExpiry}.` : `${documentTitle} expires within 1 day.`,
        priority: "high"
      };
    case "7":
      return {
        title: "Company credential expiring soon",
        body: formattedExpiry ? `${documentTitle} expires on ${formattedExpiry} (within 7 days).` : `${documentTitle} expires within 7 days.`,
        priority: "high"
      };
    default:
      return {
        title: "Company credential renewal reminder",
        body: formattedExpiry ? `${documentTitle} expires on ${formattedExpiry}.` : `${documentTitle} is approaching its expiry date.`,
        priority: "normal"
      };
  }
}
async function loadExecutiveUserIds(db) {
  const ids = /* @__PURE__ */ new Set();
  const { data: staffRows, error: staffErr } = await db.from("staff").select("id, staff_role, user_status").in("staff_role", EXECUTIVE_ROLES);
  if (staffErr) throw new Error(staffErr.message);
  for (const row of staffRows ?? []) {
    if (row.user_status === "suspended" || row.user_status === "blocked") continue;
    ids.add(String(row.id));
  }
  const { data: guardRows, error: guardErr } = await db.from("guards").select("id, staff_role, user_status, is_staff").eq("is_staff", true).in("staff_role", EXECUTIVE_ROLES);
  if (guardErr) throw new Error(guardErr.message);
  for (const row of guardRows ?? []) {
    if (row.user_status === "suspended" || row.user_status === "blocked") continue;
    ids.add(String(row.id));
  }
  return [...ids];
}
async function persistInboxNotification(db, userId, notificationId, title, body) {
  const now = (/* @__PURE__ */ new Date()).toISOString();
  const { error } = await db.from("user_notifications").upsert(
    {
      id: notificationId,
      user_id: userId,
      type: NOTIFICATION_TYPE,
      title,
      body,
      url: SETTINGS_URL,
      metadata: { source: "company_placard_expiry_cron" },
      created_at: now
    },
    { onConflict: "id" }
  );
  if (error) throw new Error(error.message);
}
async function scanAndNotifyCompanyPlacardExpiry(db) {
  if (!isPushConfigured()) {
    return { scanned: 0, executives: 0, notified: 0, skipped: 0, sent: 0, failed: 0 };
  }
  await pruneStaleNotificationDedup(db);
  const executives = await loadExecutiveUserIds(db);
  if (!executives.length) {
    return { scanned: 0, executives: 0, notified: 0, skipped: 0, sent: 0, failed: 0 };
  }
  const { data: rows, error } = await db.from("company_public_documents").select("*");
  if (error) {
    if (error.code === "42P01") {
      return { scanned: 0, executives: executives.length, notified: 0, skipped: 0, sent: 0, failed: 0 };
    }
    throw new Error(error.message);
  }
  const byType = /* @__PURE__ */ new Map();
  for (const row of rows ?? []) {
    byType.set(row.document_type, row);
  }
  const now = /* @__PURE__ */ new Date();
  const weekBucket = Math.floor(now.getTime() / (7 * 24 * 60 * 60 * 1e3));
  let notified = 0;
  let skipped = 0;
  let sent = 0;
  let failed = 0;
  let scanned = 0;
  for (const catalogItem of PLACARD_CATALOG) {
    const row = byType.get(catalogItem.id);
    const hasContent = docHasContent(row);
    const tier = expiryAlertTier(row?.expiry_date ?? void 0, hasContent, catalogItem.required, now);
    if (!tier) continue;
    scanned += 1;
    const documentTitle = row?.title?.trim() || catalogItem.title;
    const copy = alertCopy(documentTitle, tier, row?.expiry_date);
    for (const userId of executives) {
      const dedupKey = tier === "missing" ? companyPlacardMissingDedupKey(catalogItem.id, weekBucket, userId) : companyPlacardExpiryDedupKey(catalogItem.id, tier, row?.expiry_date ?? "none", userId);
      const alreadySent = await claimNotificationDedup(db, dedupKey, NOTIFICATION_TYPE);
      if (alreadySent) {
        skipped += 1;
        continue;
      }
      const notificationId = dedupKey.replace(/[^a-zA-Z0-9_-]/g, "_").slice(0, 120);
      await persistInboxNotification(db, userId, notificationId, copy.title, copy.body);
      const result = await dispatchPushNotification(db, {
        userId,
        type: NOTIFICATION_TYPE,
        title: copy.title,
        body: copy.body,
        url: SETTINGS_URL,
        priority: copy.priority
      });
      sent += result.sent;
      failed += result.failed;
      notified += 1;
    }
  }
  return {
    scanned,
    executives: executives.length,
    notified,
    skipped,
    sent,
    failed
  };
}

// api/_push/entries/company-placard-expiry.ts
async function getSupabaseAdmin() {
  const url = process.env.SUPABASE_URL || process.env.NEXT_PUBLIC_SUPABASE_URL || process.env.VITE_SUPABASE_URL;
  const serviceKey = process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.SUPABASE_KEY;
  if (!url || !serviceKey) return null;
  const { createClient } = await import("@supabase/supabase-js");
  return createClient(url, serviceKey, {
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
async function handler(req, res) {
  if (req.method !== "GET" && req.method !== "POST") {
    return res.status(405).json({ error: "Method not allowed" });
  }
  const secret = process.env.CRON_SECRET?.trim();
  if (!secret || req.headers.authorization !== `Bearer ${secret}`) {
    return res.status(401).json({ error: "Unauthorized \u2014 cron secret required" });
  }
  try {
    const db = await getSupabaseAdmin();
    if (!db) {
      return res.status(503).json({ error: "Database is not configured" });
    }
    const result = await scanAndNotifyCompanyPlacardExpiry(db);
    return res.status(200).json({ ok: true, ...result });
  } catch (err) {
    const message = err instanceof Error ? err.message : "Company placard expiry cron failed";
    console.error("Company placard expiry cron error:", message, err);
    return res.status(500).json({ error: message });
  }
}
export {
  handler as default
};
