// Generated by scripts/bundle-push-handlers.mjs — do not edit.
// @ts-nocheck

// api/_push/dedup.ts
var DEDUP_TTL_MS = 25 * 60 * 60 * 1e3;
function missedCheckinDedupKey(requestId, hourBucket) {
  return `missed_checkin:${requestId}:${hourBucket}`;
}
async function claimNotificationDedup(db, dedupKey, notificationType) {
  const { data: existing } = await db.from("push_notification_dedup").select("id").eq("id", dedupKey).maybeSingle();
  if (existing?.id) return true;
  const { error } = await db.from("push_notification_dedup").insert({
    id: dedupKey,
    notification_type: notificationType
  });
  if (error) {
    if (error.code === "23505") return true;
    throw new Error(error.message);
  }
  return false;
}
async function pruneStaleNotificationDedup(db) {
  const cutoff = new Date(Date.now() - DEDUP_TTL_MS).toISOString();
  await db.from("push_notification_dedup").delete().lt("created_at", cutoff);
}

// api/_push/routing.ts
function pushRoleToPlatformRole(pushRole) {
  switch (pushRole) {
    case "guard":
      return "guard";
    case "client":
      return "client";
    case "dispatch":
    case "admin":
      return "administrator";
    default:
      return "administrator";
  }
}
function resolveNotificationUrl(type, options = {}) {
  switch (type) {
    case "missed_checkin":
    case "guard_checkin":
    case "guard_clockout":
    case "guard_break_start":
    case "guard_break_end":
      return options.requestId ? `/staff/jobs?j=${encodeURIComponent(options.requestId)}` : "/staff/jobs";
    case "assignment":
      return options.requestId ? `/guard/my-jobs?jc=${encodeURIComponent(options.requestId)}` : "/guard/my-jobs";
    case "emergency_alert":
      if (options.requestId) {
        return `/staff/jobs?j=${encodeURIComponent(options.requestId)}`;
      }
      if (options.ticketId) {
        return `/staff/support?st=${encodeURIComponent(options.ticketId)}`;
      }
      return "/staff/incidents";
    case "support_message":
      return options.ticketId ? `/staff/support?st=${encodeURIComponent(options.ticketId)}` : "/staff/support";
    case "job_chat_message":
      return options.requestId ? `/staff/messages?mtab=jobs&jc=${encodeURIComponent(options.requestId)}` : "/staff/messages?mtab=jobs";
    case "staff_message":
      return "/staff/messages?mtab=team";
    case "guard_message":
      return "/guard/guard-chat";
    case "job_submitted":
      return options.requestId ? `/staff/jobs?j=${encodeURIComponent(options.requestId)}` : "/staff/approvals?aq=job-offers";
    case "guard_application":
      return options.requestId ? `/staff/jobs?j=${encodeURIComponent(options.requestId)}` : "/staff/approvals?aq=applications";
    case "guard_pending_approval":
      return options.guardId ? `/staff/guards?g=${encodeURIComponent(options.guardId)}` : "/staff/approvals?aq=accounts";
    case "client_pending_approval":
      return "/staff/approvals?aq=accounts";
    case "credential_pending":
      return options.guardId ? `/staff/approvals?aq=credentials&g=${encodeURIComponent(options.guardId)}` : "/staff/approvals?aq=credentials";
    case "payment_attention":
      return options.requestId ? `/staff/payments?j=${encodeURIComponent(options.requestId)}` : "/staff/payments";
    case "support_ticket":
    case "support_ticket_status":
      return options.ticketId ? `/staff/messages?mtab=support&st=${encodeURIComponent(options.ticketId)}` : "/staff/messages?mtab=support";
    case "dispute_update":
      return options.ticketId ? `/staff/disputes?st=${encodeURIComponent(options.ticketId)}` : "/staff/disputes";
    case "guard_trusted_status":
      return options.guardId ? `/guard/profile?g=${encodeURIComponent(options.guardId)}` : "/guard/profile";
    case "client_trusted_status":
      return "/client/profile";
    case "job_relisted":
      return options.requestId ? `/client/requests?jc=${encodeURIComponent(options.requestId)}` : "/client/requests";
    case "job_schedule_changed":
      return options.requestId ? `/guard/my-jobs?jc=${encodeURIComponent(options.requestId)}` : "/guard/my-jobs";
    case "team_chat_message":
      return options.requestId ? `/staff/messages?mtab=team&jc=${encodeURIComponent(options.requestId)}` : "/staff/messages?mtab=team";
    case "test":
      return "/";
    default:
      return "/";
  }
}
function resolveNotificationUrlForRole(type, role, options = {}) {
  const isStaff = role === "moderator" || role === "administrator" || role === "director" || role === "owner";
  switch (type) {
    case "support_message":
      if (role === "client") {
        return options.ticketId ? `/client/support?st=${encodeURIComponent(options.ticketId)}` : "/client/support";
      }
      if (role === "guard") {
        return options.ticketId ? `/guard/support?st=${encodeURIComponent(options.ticketId)}` : "/guard/support";
      }
      return options.ticketId ? `/staff/support?st=${encodeURIComponent(options.ticketId)}` : "/staff/support";
    case "job_chat_message":
      if (role === "client") {
        return options.requestId ? `/client/map?jc=${encodeURIComponent(options.requestId)}&chat=1` : "/client/messages";
      }
      if (role === "guard") {
        return options.requestId ? `/guard/my-jobs?jc=${encodeURIComponent(options.requestId)}&chat=1` : "/guard/my-jobs";
      }
      return options.requestId ? `/staff/messages?mtab=jobs&jc=${encodeURIComponent(options.requestId)}` : "/staff/messages?mtab=jobs";
    case "emergency_alert":
      if (role === "client") {
        return options.requestId ? `/client/map?jc=${encodeURIComponent(options.requestId)}` : "/client/coverage";
      }
      if (role === "guard") {
        return options.requestId ? `/guard/my-jobs?jc=${encodeURIComponent(options.requestId)}` : "/guard/my-jobs";
      }
      if (options.requestId) {
        return `/staff/jobs?j=${encodeURIComponent(options.requestId)}`;
      }
      if (options.ticketId) {
        return `/staff/support?st=${encodeURIComponent(options.ticketId)}`;
      }
      return "/staff/incidents";
    case "missed_checkin":
    case "guard_checkin":
    case "guard_clockout":
    case "guard_break_start":
    case "guard_break_end":
      if (role === "guard") {
        return options.requestId ? `/guard/my-jobs?jc=${encodeURIComponent(options.requestId)}` : "/guard/my-jobs";
      }
      if (role === "client") {
        return options.requestId ? `/client/map?jc=${encodeURIComponent(options.requestId)}` : "/client/coverage";
      }
      return options.requestId ? `/staff/jobs?j=${encodeURIComponent(options.requestId)}` : "/staff/jobs";
    case "staff_message":
      return "/staff/messages?mtab=team";
    case "guard_message":
      return "/guard/guard-chat";
    case "support_ticket":
    case "support_ticket_status":
      if (role === "client") {
        return options.ticketId ? `/client/support?st=${encodeURIComponent(options.ticketId)}` : "/client/support";
      }
      if (role === "guard") {
        return options.ticketId ? `/guard/support?st=${encodeURIComponent(options.ticketId)}` : "/guard/support";
      }
      return options.ticketId ? `/staff/messages?mtab=support&st=${encodeURIComponent(options.ticketId)}` : "/staff/messages?mtab=support";
    case "dispute_update":
      if (role === "client") {
        return options.ticketId ? `/client/support?st=${encodeURIComponent(options.ticketId)}` : "/client/support";
      }
      if (role === "guard") {
        return options.ticketId ? `/guard/support?st=${encodeURIComponent(options.ticketId)}` : "/guard/support";
      }
      return options.ticketId ? `/staff/disputes?st=${encodeURIComponent(options.ticketId)}` : "/staff/disputes";
    case "assignment":
      if (role === "client") {
        return options.requestId ? `/client/requests?jc=${encodeURIComponent(options.requestId)}` : "/client/requests";
      }
      return options.requestId ? `/guard/my-jobs?jc=${encodeURIComponent(options.requestId)}` : "/guard/my-jobs";
    case "guard_trusted_status":
      return "/guard/profile";
    case "client_trusted_status":
      return "/client/profile";
    case "job_relisted":
      return options.requestId ? `/client/requests?jc=${encodeURIComponent(options.requestId)}` : "/client/requests";
    case "job_schedule_changed":
      return options.requestId ? `/guard/my-jobs?jc=${encodeURIComponent(options.requestId)}` : "/guard/my-jobs";
    case "team_chat_message":
      if (role === "guard") {
        return options.requestId ? `/guard/messages?jc=${encodeURIComponent(options.requestId)}` : "/guard/messages";
      }
      return options.requestId ? `/staff/messages?mtab=team&jc=${encodeURIComponent(options.requestId)}` : "/staff/messages?mtab=team";
    default:
      if (isStaff) return resolveNotificationUrl(type, options);
      if (role === "client") return "/client/home";
      if (role === "guard") return "/guard/map";
      return resolveNotificationUrl(type, options);
  }
}
function rolesForNotificationType(type) {
  switch (type) {
    case "missed_checkin":
    case "guard_checkin":
    case "guard_clockout":
    case "guard_break_start":
    case "guard_break_end":
      return ["dispatch", "admin"];
    case "assignment":
      return ["guard"];
    case "emergency_alert":
      return ["guard", "client", "dispatch", "admin"];
    case "support_message":
      return ["dispatch", "admin", "client", "guard"];
    case "job_chat_message":
      return ["client", "guard", "dispatch", "admin"];
    case "staff_message":
      return ["dispatch", "admin"];
    case "guard_message":
      return ["guard"];
    case "job_submitted":
    case "guard_application":
    case "guard_pending_approval":
    case "client_pending_approval":
    case "credential_pending":
    case "payment_attention":
      return ["dispatch", "admin"];
    case "support_ticket":
      return ["dispatch", "admin"];
    case "support_ticket_status":
      return ["client", "guard"];
    case "dispute_update":
      return ["dispatch", "admin", "client", "guard"];
    case "guard_trusted_status":
      return ["guard"];
    case "client_trusted_status":
      return ["client"];
    case "job_relisted":
      return ["client"];
    case "job_schedule_changed":
      return ["guard"];
    case "team_chat_message":
      return ["guard", "dispatch", "admin"];
    case "test":
      return [];
    default:
      return ["guard", "dispatch"];
  }
}
function buildNotificationData(type, options = {}) {
  const urlOptions = {
    guardId: options.guardId,
    requestId: options.requestId,
    ticketId: options.ticketId
  };
  const url = options.url ?? (options.role ? resolveNotificationUrlForRole(type, options.role, urlOptions) : resolveNotificationUrl(type, urlOptions));
  return {
    type,
    url,
    siteId: options.siteId,
    guardId: options.guardId,
    requestId: options.requestId,
    ticketId: options.ticketId,
    priority: options.priority ?? (type === "emergency_alert" ? "high" : "normal")
  };
}

// api/_push/eventDispatch.ts
var EVENT_DEFAULTS = {
  guard_checkin: (event) => ({
    title: "Guard check-in",
    body: event.guardName ? `${event.guardName} checked in${event.location ? ` at ${event.location}` : ""}` : "A guard completed a check-in"
  }),
  guard_clockout: (event) => ({
    title: "Guard clock-out",
    body: event.guardName ? `${event.guardName} clocked out${event.location ? ` at ${event.location}` : ""}` : "A guard clocked out"
  }),
  guard_arrived: (event) => ({
    title: "Guard arrived on site",
    body: event.guardName ? `${event.guardName} arrived${event.location ? ` at ${event.location}` : ""}` : "Your guard arrived on site"
  }),
  guard_left_site: (event) => ({
    title: "Guard left job site",
    body: event.guardName ? `${event.guardName} left the job site${event.location ? ` at ${event.location}` : ""}` : "A guard left the job site during an active shift"
  }),
  guard_break_start: (event) => ({
    title: "Guard on break",
    body: event.guardName ? `${event.guardName} started a break${event.location ? ` at ${event.location}` : ""}` : "A guard started a break"
  }),
  guard_break_end: (event) => ({
    title: "Guard back on duty",
    body: event.guardName ? `${event.guardName} ended break and is back on duty${event.location ? ` at ${event.location}` : ""}` : "A guard ended a break"
  }),
  missed_checkin: (event) => ({
    title: "Missed check-in",
    body: event.guardName ? `${event.guardName} missed an hourly check-in` : "A guard missed an hourly check-in"
  }),
  assignment: (event) => ({
    title: "New assignment",
    body: event.body ?? (event.location ? `You have a new assignment at ${event.location}` : "You have a new assignment update")
  }),
  emergency_alert: (event) => ({
    title: "Emergency alert",
    body: event.body || "Immediate attention required on an active shift"
  }),
  support_message: (event) => ({
    title: "Support message",
    body: event.body || "You have a new support message"
  }),
  job_chat_message: (event) => ({
    title: "Job chat",
    body: event.body || "New message on an active job"
  }),
  staff_message: (event) => ({
    title: "Staff chat",
    body: event.body || "New message from the Guardr team"
  }),
  guard_message: (event) => ({
    title: "Guard chat",
    body: event.body || "New message from another guard"
  }),
  job_submitted: (event) => ({
    title: "New job request",
    body: event.body || "A client submitted a job awaiting staff review"
  }),
  guard_application: (event) => ({
    title: "Guard application",
    body: event.body || "A guard applied to an open job offer"
  }),
  guard_pending_approval: (event) => ({
    title: "Guard pending approval",
    body: event.body || "A guard account needs staff review"
  }),
  client_pending_approval: (event) => ({
    title: "Client pending approval",
    body: event.body || "A client account needs staff review"
  }),
  credential_pending: (event) => ({
    title: "Credential review",
    body: event.body || "A guard submitted credentials for review"
  }),
  payment_attention: (event) => ({
    title: "Payment attention",
    body: event.body || "A payment or payout needs staff action"
  }),
  client_cash_payment_requested: (event) => ({
    title: "Client cash payment request",
    body: event.body || "A client requested to pay in cash"
  }),
  guard_cash_payout_requested: (event) => ({
    title: "Guard cash payout request",
    body: event.body || "A guard requested cash payout"
  }),
  stripe_payment_complete: (event) => ({
    title: "Stripe payment received",
    body: event.body || "A card payment completed successfully"
  }),
  job_open_to_guards: (event) => ({
    title: "New job on the map",
    body: event.body || "A paid job is now open for guards"
  }),
  support_ticket: (event) => ({
    title: "Support ticket",
    body: event.body || "A new support ticket needs staff attention"
  }),
  support_ticket_status: (event) => ({
    title: "Support update",
    body: event.body || "Your support ticket status changed"
  }),
  dispute_update: (event) => ({
    title: "Dispute update",
    body: event.body || "A dispute needs your attention"
  }),
  guard_trusted_status: (event) => ({
    title: event.title ?? "Trusted guard update",
    body: event.body || "Your trusted guard status changed"
  }),
  client_trusted_status: (event) => ({
    title: event.title ?? "Trusted client update",
    body: event.body || "Your trusted client status changed"
  }),
  job_relisted: (event) => ({
    title: "Job back on marketplace",
    body: event.body || "A job was re-listed and is open for guards again"
  }),
  job_schedule_changed: (event) => ({
    title: "Shift time changed",
    body: event.body || "Your job schedule was updated"
  }),
  team_chat_message: (event) => ({
    title: "Crew chat",
    body: event.body || "New message in crew chat"
  })
};
function basePayload(event) {
  const fallbackFn = EVENT_DEFAULTS[event.type];
  const fallback = fallbackFn ? fallbackFn(event) : { title: "Guardr alert", body: event.body || "Operational update" };
  return {
    title: event.title ?? fallback.title,
    body: event.body ?? fallback.body,
    type: event.type,
    url: resolveNotificationUrl(event.type, {
      guardId: event.guardId,
      requestId: event.requestId,
      ticketId: event.ticketId
    }),
    guardId: event.guardId,
    requestId: event.requestId,
    ticketId: event.ticketId,
    siteId: event.siteId,
    priority: event.type === "emergency_alert" ? "high" : event.priority ?? "normal",
    excludeUserId: event.excludeUserId
  };
}
async function loadJobParticipants(db, requestId) {
  const { data } = await db.from("security_requests").select("client_id, assigned_guard_id").eq("id", requestId).maybeSingle();
  return {
    clientId: data?.client_id ?? null,
    guardId: data?.assigned_guard_id ?? null
  };
}
async function buildEventDispatchPayloads(db, event) {
  const payload = basePayload(event);
  if (event.type === "assignment") {
    if (event.recipientUserId) {
      return [{ ...payload, userId: event.recipientUserId }];
    }
    if (event.guardId) {
      return [{ ...payload, userId: event.guardId }];
    }
    return [{ ...payload, role: "guard" }];
  }
  if (event.type === "support_message" && event.recipientUserId) {
    return [{ ...payload, userId: event.recipientUserId }];
  }
  if (event.type === "job_chat_message" && event.recipientUserId) {
    return [{ ...payload, userId: event.recipientUserId }];
  }
  if (event.type === "emergency_alert" && event.requestId) {
    const { clientId, guardId } = await loadJobParticipants(db, event.requestId);
    const payloads = [{ ...payload, role: "dispatch" }];
    if (guardId) payloads.push({ ...payload, userId: guardId });
    if (clientId) payloads.push({ ...payload, userId: clientId });
    return payloads;
  }
  if (event.type === "missed_checkin") {
    const payloads = [{ ...payload, role: "dispatch" }];
    if (event.guardId) {
      payloads.push({
        ...payload,
        userId: event.guardId,
        title: "Missed check-in reminder",
        body: event.location ? `You missed your hourly check-in at ${event.location}` : "You missed your hourly check-in \u2014 please check in now"
      });
    }
    return payloads;
  }
  if (event.type === "support_ticket_status" && event.recipientUserId) {
    return [{ ...payload, userId: event.recipientUserId }];
  }
  if ((event.type === "guard_trusted_status" || event.type === "client_trusted_status" || event.type === "job_relisted" || event.type === "job_schedule_changed") && event.recipientUserId) {
    return [{ ...payload, userId: event.recipientUserId }];
  }
  if (event.type === "team_chat_message") {
    if (event.recipientUserId) {
      return [{ ...payload, userId: event.recipientUserId }];
    }
    return [{ ...payload, role: "dispatch" }];
  }
  if (event.type === "job_submitted" && event.recipientUserId) {
    return [{ ...payload, userId: event.recipientUserId }];
  }
  if (event.type === "job_open_to_guards") {
    return [{ ...payload, role: "guard" }];
  }
  if (event.type === "stripe_payment_complete" || event.type === "client_cash_payment_requested" || event.type === "guard_cash_payout_requested") {
    return [{ ...payload, role: "dispatch" }];
  }
  if (event.type === "support_ticket") {
    return [{ ...payload, role: "dispatch" }];
  }
  if (event.type === "dispute_update") {
    const payloads = [{ ...payload, role: "dispatch" }];
    if (event.guardId) payloads.push({ ...payload, userId: event.guardId });
    if (event.clientId) payloads.push({ ...payload, userId: event.clientId });
    else if (event.recipientUserId) payloads.push({ ...payload, userId: event.recipientUserId });
    return payloads;
  }
  if (event.type === "staff_message" || event.type === "job_submitted" || event.type === "guard_application" || event.type === "guard_pending_approval" || event.type === "client_pending_approval" || event.type === "credential_pending" || event.type === "payment_attention" || event.type === "client_cash_payment_requested" || event.type === "guard_cash_payout_requested" || event.type === "stripe_payment_complete" || event.type === "support_message" && !event.recipientUserId || event.type === "job_chat_message" && !event.recipientUserId) {
    return [{ ...payload, role: "dispatch" }];
  }
  if (event.type === "guard_message") {
    return [{ ...payload, role: "guard" }];
  }
  if (event.type === "guard_checkin" || event.type === "guard_clockout" || event.type === "guard_arrived" || event.type === "guard_break_start" || event.type === "guard_break_end" || event.type === "guard_left_site") {
    const payloads = [{ ...payload, role: "dispatch" }];
    if (event.requestId) {
      const { clientId, guardId } = await loadJobParticipants(db, event.requestId);
      if (clientId) payloads.push({ ...payload, userId: clientId });
      if (event.type === "guard_left_site" && guardId) {
        payloads.push({
          ...payload,
          userId: guardId,
          title: "You left the job site",
          body: event.location ? `You moved away from ${event.location} during your shift` : "You left the job site during your active shift"
        });
      }
    } else if (event.recipientUserId) {
      payloads.push({ ...payload, userId: event.recipientUserId });
    }
    return payloads;
  }
  return [payload];
}

// api/_push/delivery.ts
var PREF_COLUMN = {
  assignment: "assignment",
  guard_checkin: "guard_checkin",
  guard_clockout: "guard_clockout",
  guard_break_start: "guard_break_start",
  guard_break_end: "guard_break_end",
  missed_checkin: "missed_checkin",
  emergency_alert: "emergency_alert",
  support_message: "support_message",
  job_chat_message: "job_chat_message",
  staff_message: "staff_message",
  guard_message: "guard_message",
  job_submitted: "job_submitted",
  guard_application: "guard_application",
  guard_pending_approval: "guard_pending_approval",
  client_pending_approval: "client_pending_approval",
  credential_pending: "credential_pending",
  payment_attention: "payment_attention",
  support_ticket: "support_ticket",
  support_ticket_status: "support_ticket_status",
  dispute_update: "dispute_update",
  guard_trusted_status: "guard_trusted_status",
  client_trusted_status: "client_trusted_status",
  job_relisted: "job_relisted",
  job_schedule_changed: "assignment",
  team_chat_message: "team_chat_message"
};
async function isTypeEnabledForUser(db, userId, type) {
  const column = PREF_COLUMN[type];
  if (!column) return true;
  const { data, error } = await db.from("notification_preferences").select(column).eq("user_id", userId).maybeSingle();
  if (error || !data) return true;
  return data[column] !== false;
}
var MAX_RETRIES = 2;
var RETRY_DELAY_MS = 500;
var vapidConfigured = false;
var webPushModule = null;
async function getWebPush() {
  if (!webPushModule) {
    const mod = await import("web-push");
    webPushModule = "default" in mod && mod.default ? mod.default : mod;
  }
  return webPushModule;
}
async function ensureVapidConfigured() {
  const publicKey = process.env.VAPID_PUBLIC_KEY?.trim();
  const privateKey = process.env.VAPID_PRIVATE_KEY?.trim();
  const subject = process.env.VAPID_SUBJECT?.trim() || "mailto:support@guardr.co";
  if (!publicKey || !privateKey) return false;
  if (vapidConfigured) return true;
  const webpush = await getWebPush();
  webpush.setVapidDetails(subject, publicKey, privateKey);
  vapidConfigured = true;
  return true;
}
function isInQuietHours(quietStart, quietEnd, now = /* @__PURE__ */ new Date()) {
  if (!quietStart || !quietEnd) return false;
  const toMinutes = (time) => {
    const [h, m] = time.split(":").map(Number);
    return h * 60 + m;
  };
  const current = now.getHours() * 60 + now.getMinutes();
  const start = toMinutes(quietStart);
  const end = toMinutes(quietEnd);
  if (start === end) return false;
  if (start < end) return current >= start && current < end;
  return current >= start || current < end;
}
async function sleep(ms) {
  await new Promise((resolve) => setTimeout(resolve, ms));
}
async function sendToSubscription(subscription, payload, attempt = 0) {
  if (!await ensureVapidConfigured()) {
    return { ok: false, endpoint: subscription.endpoint };
  }
  try {
    const webpush = await getWebPush();
    await webpush.sendNotification(
      {
        endpoint: subscription.endpoint,
        keys: { p256dh: subscription.p256dh, auth: subscription.auth }
      },
      JSON.stringify(payload),
      {
        TTL: 60 * 60,
        urgency: payload.priority === "high" ? "high" : "normal"
      }
    );
    return { ok: true };
  } catch (err) {
    const statusCode = err && typeof err === "object" && "statusCode" in err ? Number(err.statusCode) : void 0;
    if (attempt < MAX_RETRIES && statusCode !== 404 && statusCode !== 410) {
      await sleep(RETRY_DELAY_MS * (attempt + 1));
      return sendToSubscription(subscription, payload, attempt + 1);
    }
    return { ok: false, statusCode, endpoint: subscription.endpoint };
  }
}
async function removeInvalidSubscriptions(db, endpoints) {
  if (!endpoints.length) return;
  await db.from("push_subscriptions").delete().in("endpoint", endpoints);
}
async function deliverToSubscriptions(db, subscriptions, payload) {
  if (!subscriptions.length) return { sent: 0, failed: 0 };
  if (!await ensureVapidConfigured()) return { sent: 0, failed: subscriptions.length };
  const prefCache = /* @__PURE__ */ new Map();
  const filtered = [];
  for (const sub of subscriptions) {
    if (payload.excludeUserId && sub.user_id === payload.excludeUserId) {
      continue;
    }
    if (!sub.user_id) {
      filtered.push(sub);
      continue;
    }
    let enabled = prefCache.get(sub.user_id);
    if (enabled === void 0) {
      enabled = await isTypeEnabledForUser(db, sub.user_id, payload.type);
      prefCache.set(sub.user_id, enabled);
    }
    if (enabled) filtered.push(sub);
  }
  if (!filtered.length) return { sent: 0, failed: 0 };
  const urlOptions = {
    guardId: payload.guardId,
    requestId: payload.requestId,
    ticketId: payload.ticketId
  };
  let sent = 0;
  let failed = 0;
  const staleEndpoints = [];
  for (const sub of filtered) {
    if (payload.type !== "emergency_alert" && payload.priority !== "high" && isInQuietHours(sub.quiet_hours_start, sub.quiet_hours_end)) {
      continue;
    }
    const platformRole = pushRoleToPlatformRole(sub.push_role);
    const data = buildNotificationData(payload.type, {
      url: payload.url ?? resolveNotificationUrlForRole(payload.type, platformRole, urlOptions),
      siteId: payload.siteId,
      guardId: payload.guardId,
      requestId: payload.requestId,
      ticketId: payload.ticketId,
      priority: payload.priority,
      role: platformRole
    });
    const message = {
      title: payload.title,
      body: payload.body,
      url: data.url,
      eventType: payload.type,
      data,
      tag: payload.siteId ? `${payload.type}-${payload.siteId}` : payload.type,
      priority: data.priority
    };
    const result = await sendToSubscription(sub, message);
    if (result.ok) {
      sent += 1;
    } else {
      failed += 1;
      if (result.statusCode === 404 || result.statusCode === 410) {
        staleEndpoints.push(result.endpoint);
      }
    }
  }
  await removeInvalidSubscriptions(db, staleEndpoints);
  return { sent, failed };
}
async function sendNotificationToUser(db, userId, payload) {
  const enabled = await isTypeEnabledForUser(db, userId, payload.type);
  if (!enabled) return { sent: 0, failed: 0 };
  const { data: subscriptions, error } = await db.from("push_subscriptions").select("endpoint, p256dh, auth, quiet_hours_start, quiet_hours_end, user_id, push_role").eq("user_id", userId);
  if (error) throw new Error(error.message);
  return deliverToSubscriptions(db, subscriptions ?? [], payload);
}
async function sendNotificationToRole(db, role, payload) {
  const roles = role === "dispatch" ? ["dispatch", "admin"] : [role];
  const { data: subscriptions, error } = await db.from("push_subscriptions").select("endpoint, p256dh, auth, quiet_hours_start, quiet_hours_end, user_id, push_role").in("push_role", roles);
  if (error) throw new Error(error.message);
  return deliverToSubscriptions(db, subscriptions ?? [], payload);
}
async function dispatchPushNotification(db, payload) {
  if (payload.userId) {
    return sendNotificationToUser(db, payload.userId, payload);
  }
  if (payload.role) {
    return sendNotificationToRole(db, payload.role, payload);
  }
  const roles = rolesForNotificationType(payload.type);
  let sent = 0;
  let failed = 0;
  for (const role of roles) {
    const result = await sendNotificationToRole(db, role, payload);
    sent += result.sent;
    failed += result.failed;
  }
  return { sent, failed };
}

// api/_push/config.ts
function isPushConfigured() {
  return !!(process.env.VAPID_PUBLIC_KEY?.trim() && process.env.VAPID_PRIVATE_KEY?.trim());
}

// api/_push/missedCheckins.ts
function lastActivityIso(job) {
  const checkIn = job.check_in_audit?.checkedAt;
  if (!checkIn) return null;
  const mids = job.mid_shift_audits ?? [];
  const lastMid = mids.length ? mids[mids.length - 1]?.checkedAt : null;
  return lastMid ?? checkIn;
}
async function scanAndNotifyMissedCheckins(db) {
  if (!isPushConfigured()) {
    return { scanned: 0, notified: 0, skipped: 0, sent: 0, failed: 0 };
  }
  await pruneStaleNotificationDedup(db);
  const { data: jobs, error } = await db.from("security_requests").select("id, location, site_name, assigned_guard_id, check_in_audit, mid_shift_audits").eq("status", "in-progress").not("assigned_guard_id", "is", null);
  if (error) throw new Error(error.message);
  const now = Date.now();
  const hourBucket = Math.floor(now / (60 * 60 * 1e3));
  let notified = 0;
  let skipped = 0;
  let sent = 0;
  let failed = 0;
  const guardIds = [
    ...new Set(
      (jobs ?? []).map((job) => job.assigned_guard_id).filter((id) => Boolean(id))
    )
  ];
  const guardNames = /* @__PURE__ */ new Map();
  if (guardIds.length) {
    const { data: guards } = await db.from("guards").select("id, name").in("id", guardIds);
    for (const guard of guards ?? []) {
      guardNames.set(guard.id, guard.name);
    }
  }
  for (const job of jobs ?? []) {
    const lastActivity = lastActivityIso(job);
    if (!lastActivity || !job.assigned_guard_id) {
      skipped += 1;
      continue;
    }
    const hoursSince = (now - new Date(lastActivity).getTime()) / (60 * 60 * 1e3);
    if (hoursSince < 1) {
      skipped += 1;
      continue;
    }
    const dedupKey = missedCheckinDedupKey(job.id, hourBucket);
    const alreadySent = await claimNotificationDedup(db, dedupKey, "missed_checkin");
    if (alreadySent) {
      skipped += 1;
      continue;
    }
    const guardName = guardNames.get(job.assigned_guard_id);
    const payloads = await buildEventDispatchPayloads(db, {
      type: "missed_checkin",
      guardId: job.assigned_guard_id,
      guardName,
      requestId: job.id,
      siteId: job.site_name || void 0,
      location: job.location || void 0
    });
    for (const payload of payloads) {
      const result = await dispatchPushNotification(db, payload);
      sent += result.sent;
      failed += result.failed;
    }
    notified += 1;
  }
  return {
    scanned: jobs?.length ?? 0,
    notified,
    skipped,
    sent,
    failed
  };
}

// api/_push/entries/missed-checkins.ts
async function getSupabaseAdmin() {
  const url = process.env.SUPABASE_URL || process.env.NEXT_PUBLIC_SUPABASE_URL || process.env.VITE_SUPABASE_URL;
  const serviceKey = process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.SUPABASE_KEY;
  if (!url || !serviceKey) return null;
  const { createClient } = await import("@supabase/supabase-js");
  return createClient(url, serviceKey, {
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
async function handler(req, res) {
  if (req.method !== "GET" && req.method !== "POST") {
    return res.status(405).json({ error: "Method not allowed" });
  }
  const secret = process.env.CRON_SECRET?.trim();
  if (!secret || req.headers.authorization !== `Bearer ${secret}`) {
    return res.status(401).json({ error: "Unauthorized \u2014 cron secret required" });
  }
  try {
    const db = await getSupabaseAdmin();
    if (!db) {
      return res.status(503).json({ error: "Database is not configured" });
    }
    const result = await scanAndNotifyMissedCheckins(db);
    return res.status(200).json({ ok: true, ...result });
  } catch (err) {
    const message = err instanceof Error ? err.message : "Missed check-in cron failed";
    console.error("Missed check-in cron error:", message, err);
    return res.status(500).json({ error: message });
  }
}
export {
  handler as default
};
