import { SecurityGuard, SecurityRequest, Client } from './types';
import { computeGuardPay } from './lib/payments';

export const INITIAL_GUARDS: SecurityGuard[] = [
  {
    id: 'guard-1',
    name: 'Alex Mercer',
    email: 'alex.mercer@guardr.io',
    badgeNumber: 'S-77291',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    phone: '+1 (555) 432-8819',
    bio: 'Ex-Military Police Sergeant with 8+ years in private diplomatic escort and close personal protection. Specialized in high-risk threat assessment and perimeter security.',
    isArmed: true,
    backgroundChecked: true,
    verified: true,
    rating: 4.9,
    jobsCompleted: 34,
    certifications: [
      { id: 'cert-1-1', name: 'State Armed Security Officer Guard Card', issuer: 'Bureau of Security and Investigative Services', number: 'G-228192-A', status: 'verified', issueDate: '2024-01-15', expiryDate: '2027-01-15' },
      { id: 'cert-1-2', name: 'Tactical Combat Casualty Care (TCCC)', issuer: 'NAEMT Association', number: 'T-881-MS', status: 'verified', issueDate: '2025-05-10', expiryDate: '2028-05-10' },
      { id: 'cert-1-3', name: 'Executive Close Protection Certified (ECP)', issuer: 'ASIS International', number: 'ECP-44120', status: 'verified', issueDate: '2024-03-01', expiryDate: '2027-03-01' },
    ],
    experience: [
      { id: 'exp-1-1', title: 'Tactical Team Lead', company: 'Vanguard Security Services', period: '2023 – Present', description: 'Led armed vehicle transport teams and VIP close-protection details for visiting trade ministers and corporate executives.' },
      { id: 'exp-1-2', title: 'Security Operator', company: 'Blackwood Close Protection', period: '2020 – 2023', description: 'Monitored private safehouse perimeters and served as responsive driver for high-net-worth clients.' },
    ],
    hourlyRateRequirement: 55,
    isStaff: true,
    staffRole: 'Director',
    userStatus: 'active',
  },
  {
    id: 'guard-2',
    name: 'Jordan Rivera',
    email: 'jordan.rivera@guardr.io',
    badgeNumber: 'S-48831',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    phone: '+1 (555) 621-4402',
    bio: 'Certified event security specialist with 6 years of experience managing crowds at high-profile concerts, festivals, and sports arenas. CPR/AED trained.',
    isArmed: false,
    backgroundChecked: true,
    verified: true,
    rating: 4.8,
    jobsCompleted: 52,
    certifications: [
      { id: 'cert-2-1', name: 'State Unarmed Guard Card License', issuer: 'Department of Consumer Affairs', number: 'UC-91822', status: 'verified', issueDate: '2023-08-01', expiryDate: '2026-08-01' },
      { id: 'cert-2-2', name: 'First Aid & CPR / AED', issuer: 'American Heart Association', number: 'AHA-221093', status: 'verified', issueDate: '2024-11-12', expiryDate: '2026-11-12' },
      { id: 'cert-2-3', name: 'Vessel / Event Security Officer (VSO)', issuer: 'IAPSO', number: 'VSO-3391', status: 'verified', issueDate: '2023-06-01', expiryDate: '2026-06-01' },
    ],
    experience: [
      { id: 'exp-2-1', title: 'Lead Event Security Officer', company: 'NightShield Events', period: '2022 – Present', description: 'Oversees access control and crowd management at concerts and major festival grounds with up to 12,000 attendees.' },
      { id: 'exp-2-2', title: 'Security Staff', company: 'Metro Arena Group', period: '2019 – 2022', description: 'Managed perimeter checkpoints and handled patron disputes professionally at 200+ events.' },
    ],
    hourlyRateRequirement: 38,
    isStaff: false,
    userStatus: 'active',
  },
  {
    id: 'guard-3',
    name: 'Marcus Webb',
    email: 'marcus.webb@guardr.io',
    badgeNumber: 'S-30017',
    avatar: 'https://images.unsplash.com/photo-1547425260-76bcadfb4f2c?w=150&auto=format&fit=crop&q=80',
    phone: '+1 (555) 788-2290',
    bio: 'Former law enforcement officer (10 years NYPD) transitioning into private security. Expert in de-escalation, asset protection, and long-term commercial patrol.',
    isArmed: true,
    backgroundChecked: true,
    verified: true,
    rating: 5.0,
    jobsCompleted: 18,
    certifications: [
      { id: 'cert-3-1', name: 'State Armed Security Officer Guard Card', issuer: 'NY State Division of Licensing', number: 'NY-A-88821', status: 'verified', issueDate: '2025-01-10', expiryDate: '2028-01-10' },
      { id: 'cert-3-2', name: 'Crisis De-escalation & Mental Health First Responder', issuer: 'CALI Institute', number: 'CR-2291-A', status: 'verified', issueDate: '2024-09-15', expiryDate: '2027-09-15' },
    ],
    experience: [
      { id: 'exp-3-1', title: 'Police Officer', company: 'NYPD – Precinct 27', period: '2013 – 2023', description: 'Handled patrol, crowd control, domestic intervention, and asset seizure operations in high-density urban districts.' },
    ],
    hourlyRateRequirement: 50,
    isStaff: false,
    userStatus: 'active',
  },
  {
    id: 'guard-4',
    name: 'Samira Okonkwo',
    email: 'samira.okonkwo@guardr.io',
    badgeNumber: 'S-11902',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    phone: '+1 (555) 902-4410',
    bio: 'New guard applicant — licensed unarmed officer completing Guardr onboarding.',
    isArmed: false,
    backgroundChecked: true,
    verified: false,
    rating: 0,
    jobsCompleted: 0,
    certifications: [
      { id: 'cert-4-1', name: 'State Unarmed Guard Card License', issuer: 'Department of Consumer Affairs', number: 'UC-44102', status: 'pending', issueDate: '2025-12-01', expiryDate: '2028-12-01' },
    ],
    experience: [],
    hourlyRateRequirement: 32,
    isStaff: false,
    userStatus: 'active',
  },
  {
    id: 'staff-moderator',
    name: 'Casey Nguyen',
    email: 'moderator@guardr.io',
    badgeNumber: 'MOD-1001',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&auto=format&fit=crop&q=80',
    phone: '+1 (555) 411-2200',
    bio: 'Platform Moderator — account approvals, compliance review, and dispute handling.',
    isArmed: false,
    backgroundChecked: true,
    verified: true,
    rating: 5.0,
    jobsCompleted: 0,
    certifications: [],
    experience: [],
    hourlyRateRequirement: 0,
    isStaff: true,
    staffRole: 'Moderator',
    userStatus: 'active',
  },
  {
    id: 'staff-admin',
    name: 'Riley Chen',
    email: 'admin@guardr.io',
    badgeNumber: 'ADM-2001',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
    phone: '+1 (555) 411-3300',
    bio: 'Platform Administrator — daily operations, payouts, fees, and analytics.',
    isArmed: false,
    backgroundChecked: true,
    verified: true,
    rating: 5.0,
    jobsCompleted: 0,
    certifications: [],
    experience: [],
    hourlyRateRequirement: 0,
    isStaff: true,
    staffRole: 'Administrator',
    userStatus: 'active',
  },
];

export const INITIAL_REQUESTS: SecurityRequest[] = [
  {
    id: 'req-demo-1',
    title: 'Corporate Gala — Armed Escort & Perimeter',
    description: 'High-profile private gala for 200+ executives. Requires armed personnel for perimeter control, VIP escort, and access point management. Black tie venue, professional appearance mandatory.',
    clientId: 'client-1',
    clientName: 'Apex Holdings LLC',
    clientLogo: 'AH',
    clientRating: 4.8,
    siteName: 'The Ritz-Carlton',
    address: '151 W Adams St, Chicago IL',
    location: 'The Ritz-Carlton — 151 W Adams St, Chicago IL',
    type: 'event',
    armedRequired: true,
    guardsNeeded: 4,
    uniformRequirements: 'Black suit, white shirt, tie optional',
    equipmentRequirements: 'Radio, flashlight, duty belt',
    siteInstructions: 'Report to loading dock entrance B. Check in with event coordinator.',
    startDate: new Date(Date.now() + 3 * 24 * 3600000).toISOString(),
    endDate: new Date(Date.now() + 3 * 24 * 3600000 + 6 * 3600000).toISOString(),
    durationHours: 6,
    hourlyRate: 55,
    guardPay: computeGuardPay(55),
    platformFeePerHour: 5,
    estimatedPayout: 330,
    status: 'open',
    assignedGuardId: null,
    requiredCertifications: ['State Armed Security Officer Guard Card', 'Executive Close Protection Certified (ECP)'],
    applicants: [],
  },
  {
    id: 'req-demo-2',
    title: 'Music Festival — Event Security Crew',
    description: 'Two-day outdoor music festival. Need unarmed security staff for crowd management, backstage access control, and artist protection corridors. High energy environment.',
    clientId: 'client-2',
    clientName: 'Prism Events Co.',
    clientLogo: 'PE',
    clientRating: 4.6,
    siteName: 'Riverside Amphitheater',
    address: '920 W Riverside Dr, Austin TX',
    location: 'Riverside Amphitheater — 920 W Riverside Dr, Austin TX',
    type: 'event',
    armedRequired: false,
    guardsNeeded: 8,
    uniformRequirements: 'Black polo, black pants, black shoes',
    equipmentRequirements: 'Radio, flashlight',
    siteInstructions: 'Staff entrance on west side. Pick up credentials at security trailer.',
    startDate: new Date(Date.now() + 7 * 24 * 3600000).toISOString(),
    endDate: new Date(Date.now() + 7 * 24 * 3600000 + 10 * 3600000).toISOString(),
    durationHours: 10,
    hourlyRate: 38,
    guardPay: computeGuardPay(38),
    platformFeePerHour: 5,
    estimatedPayout: 380,
    status: 'open',
    assignedGuardId: null,
    requiredCertifications: ['State Unarmed Guard Card License', 'Vessel / Event Security Officer (VSO)'],
    applicants: [],
  },
  {
    id: 'req-demo-3',
    title: 'Commercial Office — Overnight Patrol',
    description: 'Long-term overnight patrol contract for a Class-A office tower. Requires professional conduct, incident logging, and daily activity report submission. Recurring weekly shifts available.',
    clientId: 'client-3',
    clientName: 'PinnacleRE Group',
    clientLogo: 'PR',
    clientRating: 4.9,
    siteName: 'Brickell Tower B',
    address: '400 Brickell Ave, Miami FL',
    location: 'Brickell Tower B — 400 Brickell Ave, Miami FL',
    type: 'patrol',
    armedRequired: false,
    guardsNeeded: 2,
    uniformRequirements: 'Company-branded shirt provided on site',
    equipmentRequirements: 'Radio, flashlight, incident log tablet',
    siteInstructions: 'Lobby security desk. Relief guard arrives at 06:00.',
    startDate: new Date(Date.now() + 1 * 24 * 3600000 + 22 * 3600000).toISOString(),
    endDate: new Date(Date.now() + 2 * 24 * 3600000 + 6 * 3600000).toISOString(),
    durationHours: 8,
    hourlyRate: 35,
    guardPay: computeGuardPay(35),
    platformFeePerHour: 5,
    estimatedPayout: 280,
    status: 'open',
    assignedGuardId: null,
    requiredCertifications: ['State Unarmed Guard Card License', 'First Aid & CPR / AED'],
    applicants: [],
  },
  {
    id: 'req-demo-4',
    title: 'Celebrity VIP Bodyguard Detail',
    description: 'Personal protection detail for visiting performer during 3-city tour stop. Must hold ECP certification and armed permit. Prior close-protection experience required.',
    clientId: 'client-1',
    clientName: 'Apex Holdings LLC',
    clientLogo: 'AH',
    clientRating: 4.8,
    siteName: 'Madison Square Garden',
    address: '4 Pennsylvania Plaza, New York NY',
    location: 'Madison Square Garden — 4 Pennsylvania Plaza, New York NY',
    type: 'bodyguard',
    armedRequired: true,
    guardsNeeded: 2,
    uniformRequirements: 'Dark suit, concealed carry holster',
    equipmentRequirements: 'Radio, earpiece, flashlight',
    siteInstructions: 'Meet artist liaison at VIP entrance 90 minutes before doors.',
    startDate: new Date(Date.now() + 10 * 24 * 3600000).toISOString(),
    endDate: new Date(Date.now() + 10 * 24 * 3600000 + 12 * 3600000).toISOString(),
    durationHours: 12,
    hourlyRate: 75,
    guardPay: computeGuardPay(75),
    platformFeePerHour: 5,
    estimatedPayout: 900,
    status: 'open',
    assignedGuardId: null,
    requiredCertifications: ['State Armed Security Officer Guard Card', 'Executive Close Protection Certified (ECP)', 'First Aid & CPR / AED'],
    applicants: [],
  },
];

export const PREFAB_CERT_LIST = [
  'State Unarmed Guard Card License',
  'State Armed Security Officer Guard Card',
  'First Aid & CPR / AED',
  'Vessel / Event Security Officer (VSO)',
  'Tactical Combat Casualty Care (TCCC)',
  'Executive Close Protection Certified (ECP)',
  'NRA Professional Range Safety Guard License',
  'Crisis De-escalation & Mental Health First Responder',
];

export const INITIAL_CLIENTS: Client[] = [
  {
    id: 'client-1',
    name: 'James Harrington',
    email: 'james@apexholdings.com',
    companyName: 'Apex Holdings LLC',
    phone: '+1 (212) 555-0101',
    avatar: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=150&auto=format&fit=crop&q=80',
    totalRequests: 2,
    approved: true,
    rating: 4.8,
  },
  {
    id: 'client-2',
    name: 'Priya Sharma',
    email: 'priya@prismevents.co',
    companyName: 'Prism Events Co.',
    phone: '+1 (310) 555-0202',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    totalRequests: 1,
    approved: true,
    rating: 4.6,
  },
  {
    id: 'client-3',
    name: 'Derek Boucher',
    email: 'derek@pinnacle-re.com',
    companyName: 'PinnacleRE Group',
    phone: '+1 (305) 555-0303',
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
    totalRequests: 1,
    approved: true,
    rating: 4.9,
  },
];
