import { SecurityGuard, SecurityRequest } from './types';

export const INITIAL_GUARDS: SecurityGuard[] = [
  {
    id: 'guard-1',
    name: 'Alex Mercer',
    email: 'alex.mercer@guardr.io',
    badgeNumber: 'S-77291',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    phone: '+1 (555) 432-8819',
    bio: 'Ex-Military Police Sergeant with 8+ years in private diplomatic escort and close personal protection. Specialized in high-risk threat assessment and perimeter security.',
    isArmed: true,
    backgroundChecked: true,
    verified: true,
    rating: 4.9,
    jobsCompleted: 34,
    certifications: [
      { id: 'cert-1-1', name: 'State Armed Security Officer Guard Card', issuer: 'Bureau of Security and Investigative Services', number: 'G-228192-A', status: 'verified', issueDate: '2024-01-15', expiryDate: '2027-01-15' },
      { id: 'cert-1-2', name: 'Tactical Combat Casualty Care (TCCC)', issuer: 'NAEMT Association', number: 'T-881-MS', status: 'verified', issueDate: '2025-05-10', expiryDate: '2028-05-10' },
      { id: 'cert-1-3', name: 'Executive Close Protection Certified (ECP)', issuer: 'ASIS International', number: 'ECP-44120', status: 'verified', issueDate: '2024-03-01', expiryDate: '2027-03-01' },
    ],
    experience: [
      { id: 'exp-1-1', title: 'Tactical Team Lead', company: 'Vanguard Security Services', period: '2023 – Present', description: 'Led armed vehicle transport teams and VIP close-protection details for visiting trade ministers and corporate executives.' },
      { id: 'exp-1-2', title: 'Security Operator', company: 'Blackwood Close Protection', period: '2020 – 2023', description: 'Monitored private safehouse perimeters and served as responsive driver for high-net-worth clients.' },
    ],
    hourlyRateRequirement: 55,
    isStaff: true,
    userStatus: 'active',
  },
  {
    id: 'guard-2',
    name: 'Jordan Rivera',
    email: 'jordan.rivera@guardr.io',
    badgeNumber: 'S-48831',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    phone: '+1 (555) 621-4402',
    bio: 'Certified event security specialist with 6 years of experience managing crowds at high-profile concerts, festivals, and sports arenas. CPR/AED trained.',
    isArmed: false,
    backgroundChecked: true,
    verified: true,
    rating: 4.8,
    jobsCompleted: 52,
    certifications: [
      { id: 'cert-2-1', name: 'State Unarmed Guard Card License', issuer: 'Department of Consumer Affairs', number: 'UC-91822', status: 'verified', issueDate: '2023-08-01', expiryDate: '2026-08-01' },
      { id: 'cert-2-2', name: 'First Aid & CPR / AED', issuer: 'American Heart Association', number: 'AHA-221093', status: 'verified', issueDate: '2024-11-12', expiryDate: '2026-11-12' },
      { id: 'cert-2-3', name: 'Vessel / Event Security Officer (VSO)', issuer: 'IAPSO', number: 'VSO-3391', status: 'verified', issueDate: '2023-06-01', expiryDate: '2026-06-01' },
    ],
    experience: [
      { id: 'exp-2-1', title: 'Lead Event Security Officer', company: 'NightShield Events', period: '2022 – Present', description: 'Oversees access control and crowd management at concerts and major festival grounds with up to 12,000 attendees.' },
      { id: 'exp-2-2', title: 'Security Staff', company: 'Metro Arena Group', period: '2019 – 2022', description: 'Managed perimeter checkpoints and handled patron disputes professionally at 200+ events.' },
    ],
    hourlyRateRequirement: 38,
    isStaff: false,
    userStatus: 'active',
  },
  {
    id: 'guard-3',
    name: 'Marcus Webb',
    email: 'marcus.webb@guardr.io',
    badgeNumber: 'S-30017',
    avatar: 'https://images.unsplash.com/photo-1547425260-76bcadfb4f2c?w=150&auto=format&fit=crop&q=80',
    phone: '+1 (555) 788-2290',
    bio: 'Former law enforcement officer (10 years NYPD) transitioning into private security. Expert in de-escalation, asset protection, and long-term commercial patrol.',
    isArmed: true,
    backgroundChecked: true,
    verified: true,
    rating: 5.0,
    jobsCompleted: 18,
    certifications: [
      { id: 'cert-3-1', name: 'State Armed Security Officer Guard Card', issuer: 'NY State Division of Licensing', number: 'NY-A-88821', status: 'verified', issueDate: '2025-01-10', expiryDate: '2028-01-10' },
      { id: 'cert-3-2', name: 'Crisis De-escalation & Mental Health First Responder', issuer: 'CALI Institute', number: 'CR-2291-A', status: 'verified', issueDate: '2024-09-15', expiryDate: '2027-09-15' },
    ],
    experience: [
      { id: 'exp-3-1', title: 'Police Officer', company: 'NYPD – Precinct 27', period: '2013 – 2023', description: 'Handled patrol, crowd control, domestic intervention, and asset seizure operations in high-density urban districts.' },
    ],
    hourlyRateRequirement: 50,
    isStaff: false,
    userStatus: 'active',
  },
];

export const INITIAL_REQUESTS: SecurityRequest[] = [
  {
    id: 'req-demo-1',
    title: 'Corporate Gala — Armed Escort & Perimeter',
    description: 'High-profile private gala for 200+ executives. Requires armed personnel for perimeter control, VIP escort, and access point management. Black tie venue, professional appearance mandatory.',
    clientId: 'client-demo',
    clientName: 'Apex Holdings LLC',
    clientLogo: 'AH',
    location: 'The Ritz-Carlton, Downtown Chicago',
    type: 'event',
    armedRequired: true,
    startDate: new Date(Date.now() + 3 * 24 * 3600000).toISOString().replace(/\.\d+Z$/, ''),
    endDate: new Date(Date.now() + 3 * 24 * 3600000 + 6 * 3600000).toISOString().replace(/\.\d+Z$/, ''),
    durationHours: 6,
    hourlyRate: 55,
    estimatedPayout: 330,
    status: 'open',
    assignedGuardId: null,
    requiredCertifications: ['State Armed Security Officer Guard Card', 'Executive Close Protection Certified (ECP)'],
    applicants: [],
  },
  {
    id: 'req-demo-2',
    title: 'Music Festival — Event Security Crew',
    description: 'Two-day outdoor music festival. Need unarmed security staff for crowd management, backstage access control, and artist protection corridors. High energy environment.',
    clientId: 'client-demo-2',
    clientName: 'Prism Events Co.',
    clientLogo: 'PE',
    location: 'Riverside Amphitheater, Austin TX',
    type: 'event',
    armedRequired: false,
    startDate: new Date(Date.now() + 7 * 24 * 3600000).toISOString().replace(/\.\d+Z$/, ''),
    endDate: new Date(Date.now() + 7 * 24 * 3600000 + 10 * 3600000).toISOString().replace(/\.\d+Z$/, ''),
    durationHours: 10,
    hourlyRate: 38,
    estimatedPayout: 380,
    status: 'open',
    assignedGuardId: null,
    requiredCertifications: ['State Unarmed Guard Card License', 'Vessel / Event Security Officer (VSO)'],
    applicants: [],
  },
  {
    id: 'req-demo-3',
    title: 'Commercial Office — Overnight Patrol',
    description: 'Long-term overnight patrol contract for a Class-A office tower. Requires professional conduct, incident logging, and daily activity report submission. Recurring weekly shifts available.',
    clientId: 'client-demo-3',
    clientName: 'PinnacleRE Group',
    clientLogo: 'PR',
    location: '400 Brickell Ave, Miami FL',
    type: 'patrol',
    armedRequired: false,
    startDate: new Date(Date.now() + 1 * 24 * 3600000 + 22 * 3600000).toISOString().replace(/\.\d+Z$/, ''),
    endDate: new Date(Date.now() + 2 * 24 * 3600000 + 6 * 3600000).toISOString().replace(/\.\d+Z$/, ''),
    durationHours: 8,
    hourlyRate: 35,
    estimatedPayout: 280,
    status: 'open',
    assignedGuardId: null,
    requiredCertifications: ['State Unarmed Guard Card License', 'First Aid & CPR / AED'],
    applicants: [],
  },
  {
    id: 'req-demo-4',
    title: 'Celebrity VIP Bodyguard Detail',
    description: 'Personal protection detail for visiting performer during 3-city tour stop. Must hold ECP certification and armed permit. Prior close-protection experience required.',
    clientId: 'client-demo-4',
    clientName: 'Stellar Artist Management',
    clientLogo: 'SA',
    location: 'Madison Square Garden, New York NY',
    type: 'bodyguard',
    armedRequired: true,
    startDate: new Date(Date.now() + 10 * 24 * 3600000).toISOString().replace(/\.\d+Z$/, ''),
    endDate: new Date(Date.now() + 10 * 24 * 3600000 + 12 * 3600000).toISOString().replace(/\.\d+Z$/, ''),
    durationHours: 12,
    hourlyRate: 75,
    estimatedPayout: 900,
    status: 'open',
    assignedGuardId: null,
    requiredCertifications: ['State Armed Security Officer Guard Card', 'Executive Close Protection Certified (ECP)', 'First Aid & CPR / AED'],
    applicants: [],
  },
];

export const PREFAB_CERT_LIST = [
  'State Unarmed Guard Card License',
  'State Armed Security Officer Guard Card',
  'First Aid & CPR / AED',
  'Vessel / Event Security Officer (VSO)',
  'Tactical Combat Casualty Care (TCCC)',
  'Executive Close Protection Certified (ECP)',
  'NRA Professional Range Safety Guard License',
  'Crisis De-escalation & Mental Health First Responder',
];
